### ISSUE TITLE
Code styling functions.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/iRail#101]
Not all functions have a visibility attribute. But it is required in the PSR-2.

**Comment by pietercolpaert** [comment]
I don't understand this issue. What are code styling functions?

**Comment by Tjoosten** [comment]
some functions are like `function methodName() { }` according to psr-2 they should something like `public function MethodName() { }`

**Comment by pietercolpaert** [comment]
Isn't that for classes?

**Comment by Tjoosten** [comment]
Nope it needs to be done on functions.

**Comment by Tjoosten** [comment]
Can be fixed with styleCi maybe

**Comment by Tjoosten** [comment]
This can be closed StyleCi fixed this one. @pietercolpaert
