### ISSUE TITLE
Error 502 for "la louviere centre"

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#114]
It is currently impossible to get any result for search including "La louvière centre".
According to the user, the issue appeared "a few days ago", so it looks like this was working before the changes.

Example URL: http://api.irail.be/connections.php?to=OBOURG&from=LA%20LOUVIERE%20CENTRE&date=240815&time=1407&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true

Thank a lot.

**Comment by pietercolpaert** [comment]
Somehow, the NMBS/SNCB is now returning the string `La Louviere- Centre` in the response. We fail on the extra space that's inserted. Will fix asap.

**Comment by pietercolpaert** [comment]
Thanks for filing this issue @ChristopheVersieux! You're the best :-)
