### ISSUE TITLE
Too many 502 errors from server.

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#129]
Hello all,

The amount of feedback I receive from users getting 502 errors while making a query to the API is really concerning me and the quality of my app, and I wanted to address all these issues. I cannot unfortunately make a copy of iRail on my side and make it run, so, I will leave all the links resulting in server error here:

http://api.irail.be/vehicle.php/?id=1758&lang=en&date=021215&time=0848&format=JSON
http://api.irail.be/vehicle.php/?id=3468&lang=fr&date=261115&time=1901&format=JSON
http://api.irail.be/vehicle.php/?id=1779&lang=en&date=021215&time=0913&format=JSON
http://api.irail.be/vehicle.php/?id=7861&lang=fr&date=041215&time=1157&format=JSON

An alternative would be to add some Analytics to the application and making public weekly/monthly report of all the issues if it could help.

**Comment by brechtvdv** [comment]
It's now almost everytime a problem because the route just doesn't drive on the day of request.
We should make a different error message for that case with error code 503?

**Comment by pietercolpaert** [comment]
Return a 404 instead and make sure betrains catches this correctly?

**Comment by ChristopheVersieux** [comment]
Hi Pieter,

I follow these reports at a day to day basis, and the requests are always
correct regarding date and time. They are all easy to reproduce.
502 errors with valid data are real.

BeTrains catches the errors this way for easier reporting:
if (result.getHeaders().code() == 502)

https://github.com/iRail/BeTrains-for-Android/blob/master/BeTrains/src/main/java/tof/cv/mpp/InfoTrainFragment.java#L225

**Comment by ChristopheVersieux** [comment]
Note: adding &fast=true will make the request to succeed. I guess that this is the famous "text to id" issue.

**Comment by brechtvdv** [comment]
Yes, in that case it's a 'text to id' issue :/ Will fix it when I have time!

**Comment by brechtvdv** [comment]
This commit should also fix some 'text to ID' issues, as it tries to parse the ID from a station URL
