### ISSUE TITLE
Display service alerts

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#149]
Wouldn't it be nice to have service alerts for Connections, Vehicles and Liveboards? This would give a better idea of what's going on during strikes etc.

Example of a service message on the NMBS website:
![screen shot 2015-12-30 at 18 40 37](https://cloud.githubusercontent.com/assets/995815/12056840/b58448c4-af3b-11e5-8737-e7113bd0c5c6.png)

An `alert` object would contain a `header` and a `description`.

Structure, based on the data we have from NMBS:
```
Connections
|-- connection
    |-- departure
    |-- arrival
    |-- vias
    |-- alerts
        |-- alert

Liveboard
|-- station
|-- departures
    |-- departure
        |-- alerts
            |-- alert

Vehicle
|-- vehicle
|-- alerts
    |-- alert
|-- stops
```

Since this addition could have some impact on client side download speed (especially for liveboard and connection requests), these service alerts would be opt-in only.
E.g. `/liveboard/?station=brussel-zuid&alerts=true`

Thoughts and comments welcome!

**Comment by pietercolpaert** [comment]
I doubt whether it would take that much more time... But opt-in only is fine for me!

**Comment by jncn** [comment]
Probably not a very big difference, but every kb counts, especially when you're on a moving train 😉
`/liveboard/?station=brussel-zuid&alerts=true` = 35kb
`/liveboard/?station=brussel-zuid` = 11kb

**Comment by pietercolpaert** [comment]
@jncn You might want to recheck that with GZIP enabled ;)

**Comment by jncn** [comment]
@pietercolpaert Is this supported on api.rail.be? How do I get access?

**Comment by pietercolpaert** [comment]
It's supported on api.irail.be indeed by putting it in front of a varnish.

![screenshot from 2015-12-31 14 46 06](https://cloud.githubusercontent.com/assets/347073/12064854/78e99f1c-afcd-11e5-96e2-5d45f5180406.png)

`php -S` is for development purposes and doesn't have gzip afaik. Let's compare when development is in production

**Comment by pietercolpaert** [comment]
It's in production
