### ISSUE TITLE
malformed JSON in logs

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#152]
Hello, I don't know if the logs (http://api.irail.be/logs/#) issues should be reported here, but the JSON is not correct
![capture](https://cloud.githubusercontent.com/assets/356214/12413229/aca2d99e-be8d-11e5-9756-b17821d51e35.PNG)

Not really a big issue, but annoying...

**Comment by pietercolpaert** [comment]
Hi @ChristopheVersieux: this was first done on purpose... But I feel your pain and we should indeed fix it to become a valid JSON array.

Thanks for the feedback! Will fix soon
