### ISSUE TITLE
Confusion between name // standartname ?

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#158]
Hello team,

I thought that I understood correctly the difference between name and standartname in the API, until a Flemish user made me noticed that Gent was missing in the app. That's because I use 'name' field for flemish users (Brussels, for instance is localized)
Link: http://api.irail.be/stations.php?format=json&lan=nl

name: "Ghent-Sint-Pieters",
standardname: "Gent-Sint-Pieters"

I then looked into stations.csv, but the name is correct (Gent) and Ghent is only used in English)
https://github.com/iRail/stations/blob/master/stations.csv#L204

Did I missed something?

**Comment by jncn** [comment]
@ChristopheVersieux The URL you posted (pasted?) is wrong. Should be http://api.irail.be/stations.php?format=json&lang=nl with `lang` as argument (not `lan`).

**Comment by ChristopheVersieux** [comment]
Was indeed 'lang' in the app, analysis here was based on 'lan', sorry....
feedback was updated without any reason from the user, I think it might be a non-issue...
