### ISSUE TITLE
Scrape mobile site instead of full site

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#161]
The mobile NMBS site has a lot less and cleaner HTML, so it's probably a good idea to scrape that one instead of the full site. For instance, #92 would be a lot easier to fix.
N.B. At the moment we only scrape HTML for `vehicle`.
Please have a look: http://mobile.b-rail.be/
Thoughts?

**Comment by pietercolpaert** [comment]
Looks easier indeed! @brechtvdv any comments on this?

**Comment by pietercolpaert** [comment]
Found a way to GET permalinks like this: http://www.belgianrail.be/jpm/sncb-nmbs-routeplanner/trainsearch.exe/nox?ld=std&trainname=P8008&date=20/07/16&productClassFilter=69 

Template is: `http://www.belgianrail.be/jpm/sncb-nmbs-routeplanner/trainsearch.exe/nox?ld=std&trainname={route id}&date={dd}/{mm}/{yy}&productClassFilter=69`

Then scraping the site looks straightforward.

Pay attention however to:
 * [ ] Canceled trains: how  does that get indicated
 * [ ] When a train crosses midnight, be sure to add 1 day to the date
 * [ ] real-time location of train should be updated: #92 
 * [ ] also show arrival info: #202

**Comment by pietercolpaert** [comment]
Just noticed there are no alerts in the mobile site... It might be better to scrape the full website after all and just enhance it. @brechtvdv: your thoughts on that?

**Comment by pietercolpaert** [comment]
Closing this in favor of the full website for which we already have code, and which contains more information (e.g., alerts)
