### ISSUE TITLE
Error message from the API still ink to iRail@list.iRail.be

### ISSUE THREAD

**Issue by ghost** [iRail/iRail#163]
Maybe we should change the following error message ?
I was planning to display the error for the users, but I guess you won't be happy to see the list "spammed"by reports?

http://api.irail.be/connections.php?to=Brussel-Nat-Luchthaven/Bruxelles-Nat-A%C3%A9roport&from=MONS&date=280416&time=0825&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true

{
error: 500,
message: "Could not get data. Please report this problem to iRail@list.iRail.be."
}

**Comment by pietercolpaert** [comment]
That's how BeTrains does it now though... What would you suggest? (sorry for late response)

**Comment by pietercolpaert** [comment]
@ghost any suggestion on an alternative error message?

**Comment by Haroenv** [comment]
Maybe like https://github.com/iRail/iRail/blob/master/api/data/NMBS/stations.php#L103 and do `'Could not get data. Please report this issue at https://github.com/irail/stations/issues/new'`?

**Comment by pietercolpaert** [comment]
That's a good suggestion! Can be pull requested what I'm concerned!

**Comment by pietercolpaert** [comment]
This issue is fixed by #215. Will put in production soon!
