### ISSUE TITLE
Vehicle timestamps wrong for trains going past midnight

### ISSUE THREAD

**Issue by Ben-Baert** [iRail/iRail#164]
I'm not sure whether this has been mentioned yet. I did a quick search and couldn't find anything...

For trains leaving before midnight and going past midnight, the timestamp 'resets' upon passing midnight.

e.g. IC545
Tienen: 23:49: 1462398540
Leuven: 00:01: 1462312860

**Comment by pietercolpaert** [comment]
Ouch! Thanks for noticing! Will fix asap!

**Comment by pietercolpaert** [comment]
For example, occurs between Tienen and Leuven here: http://api.irail.be/vehicle/?id=BE.NMBS.IC545&format=JSON
