### ISSUE TITLE
When calling vehicule, API returns Brussels South for all stations

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#165]
Hello,

When looking at at a TGV, all stations are returned as Brussels South:

http://api.irail.be/vehicle/?id=BE.NMBS.TGV9828&format=JSON

If I add fast=true, API will return correct stations names:

http://api.irail.be/vehicle/?id=BE.NMBS.TGV9828&format=JSON&fast=true

in both cases, all ID are id: "BE.NMBS.008814001" which seems to be the issue. I guess that all stations outside Belgium are wrong.

Could you at least fix the naming issue so the users are not lost ?

![capture](https://cloud.githubusercontent.com/assets/356214/15464267/988bb446-20ce-11e6-9807-2f2e48111a91.PNG)

**Comment by jncn** [comment]
I've fixed this one in ea240f1 - #167

**Comment by ChristopheVersieux** [comment]
Note: now, we get a 500 error, for the url without fast= true. 
Adding fast=true still gives results.

{
error: 500,
message: "Could not get data. Please report this problem to iRail@list.iRail.be."
}

**Comment by jncn** [comment]
@ChristopheVersieux  Hmm, not good. Only some trains have this problem, though. Will look at it tonight.

These still work:
http://api.irail.be/vehicle/?id=BE.NMBS.ic1710&format=JSON
http://api.irail.be/vehicle/?id=BE.NMBS.tha9327&format=JSON
http://api.irail.be/vehicle/?id=BE.NMBS.tha9352&format=JSON

**Comment by ChristopheVersieux** [comment]
OK, maybe this is just an issue with TGV?
http://api.irail.be/vehicle/?id=BE.NMBS.TGV9828&format=JSON

Thanks

**Comment by pietercolpaert** [comment]
@jncn Did you track down the problem? Anything idea how to fix this?

**Comment by jncn** [comment]
Apparently this error was (as far as I know) only there with trains stopping at Charles de Gaulle TGV station.

**Comment by ChristopheVersieux** [comment]
@pietercolpaert http://api.irail.be/vehicle/?id=BE.NMBS.TGV9828&format=JSON without fast=true still reports an error 500. 
Should I wait for the fix to be pushed in prod, or is it still an issue?

**Comment by pietercolpaert** [comment]
@ChristopheVersieux you were too fast :p Now it's in production and your link seems to work!

**Comment by ChristopheVersieux** [comment]
Usually you are always faster than me ;-)
Thank a lot to both of you for the fix!
