### ISSUE TITLE
Adding train perturbation info. Would it be hard?

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#166]
Hello,
I just noticed that NMBS displays live info about issues on their search results.
How hard would it be to add these in the API?

![capture](https://cloud.githubusercontent.com/assets/356214/15533566/7bf711ac-2265-11e6-9f35-457cd60c3346.PNG)

**Comment by brechtvdv** [comment]
The info from the API is not fetched from the mobile version of the website,
but it's even easier because it's already there in the HTML.

How do you want the XML to look like?
e.g.:
```xml
<perturbations>
<perturbation>
<title></title>
<description></description>
<perturbation>
</perturbations>
```

**Comment by ChristopheVersieux** [comment]
Ok, I used mobile in the example, because of https://github.com/iRail/iRail/issues/161

But yeah a structure Perturbation list that has children with title and description seems a good thing.

PS: this will add a lot of value to the API I am sure!

**Comment by brechtvdv** [comment]
Makes sense, I'll have a look at the mobile version while I'm checking the pertubation list.

**Comment by jncn** [comment]
Uhm guys, don't want to spoil the party, but this is in production since last year 😉
See #149 and #150. Enjoy!

**Comment by pietercolpaert** [comment]
Right, Just add alerts=true ;)

**Comment by ChristopheVersieux** [comment]
Awesome, always ahead of the requests ;-)
Why do I never heard of such great news? Sorry and thanks a lot, guys, I will still spend some hours on the app!
