### ISSUE TITLE
JSON failed in tests because special "tabs" in it when alerts=true

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#169]
Hello,

This bug is maybe just an enhancement, as it seems to work in the app, but the json with alert contains special chars that might fail in a JSON parser.

I have tested this url in JSONLINT.com: http://api.irail.be/connections.php?to=liege-guillemins&from=mons&date=070616&time=0911&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true&alerts=true#

![jsonlint](https://cloud.githubusercontent.com/assets/356214/15849562/7dcadf94-2c93-11e6-81cd-3b5d12722ffe.PNG)

This also fail in my many chrome extentions to display pretty JSON.

After some research, it seems that the feed has some tabs characters in it, as seen in Notepad++:

![tabs](https://cloud.githubusercontent.com/assets/356214/15849644/d9e596a2-2c93-11e6-9a62-968f59158d64.PNG)

Is that a bug that should be fixed in API?

Shouldn't the tabs be escaped according to specs?

![escape](https://cloud.githubusercontent.com/assets/356214/15849799/863e8990-2c94-11e6-8c21-baf233358220.PNG)

**Comment by pietercolpaert** [comment]
Thanks! will fix!

**Comment by Haroenv** [comment]
Relevant line is on https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php#L231 which should be escaped

**Comment by Haroenv** [comment]
@pietercolpaert; this error should be closed now (it didn't automatically because my PR was closed, not merged)

**Comment by pietercolpaert** [comment]
It wasn't closed automatically yet because it's not in production (master branch) yet. Will be put in production tomorrow! Closing for now :)
