### ISSUE TITLE
API request: http://api.irail.be/vehicle/?id=BE.NMBS.IC429

### ISSUE THREAD

**Issue by StanCallewaert** [iRail/iRail#179]
A 404 error is returned when a request to this url (http://api.irail.be/vehicle/?id=BE.NMBS.IC429) is made. Although the train number actually exists.

**Comment by pietercolpaert** [comment]
The current limitation of the iRail API's vehicle request is that you can only request vehicles for the current day. Yesterday, IC429 was indeed not driving, today however, it is.

**Comment by pietercolpaert** [comment]
Closing this in favor of #161
