### ISSUE TITLE
Post request for user feedback data

### ISSUE THREAD

**Issue by StanCallewaert** [iRail/iRail#181]
## POST (https://api.irail.be/feedback/occupancy):

A JSON example of how a post request should look like is shown below:
```
{
  "connection": "http://irail.be/connections/8871308/20160722/IC4516",
  "vehicle":"http://api.irail.be/vehicle/?id=BE.NMBS.IC4516",
  "from":"http://irail.be/stations/NMBS/008871308",
  "to":"http://irail.be/stations/NMBS/008872009",
  "occupancy":"http://api.irail.be/terms/medium",
  "departureTime":"20160722T1642"
}
```

The departureTime is the datetime when the train leaves the **from station** in an ISO 8601 format.

Occupancy must be one of the following values: "https://api.irail.be/terms/low", "https://api.irail.be/terms/medium", "https://api.irail.be/terms/high".

**Comment by ChristopheVersieux** [comment]
May I suggest to use an numeric value instead of a text?
I think it is always better to compare numeric values rather than text in clients in order to avoid issues.
Also this might help if the range changes.

**Comment by pietercolpaert** [comment]
@ChristopheVersieux I actually recommended using a text string instead of a numeric value, as it's otherwise unclear what the value actually means. To be discussed...

**Comment by ChristopheVersieux** [comment]
OK, it was just a suggestion as we could have imagined different scales in the future (occupancy = 3 max_occupancy =5)

But whatever, I will gladly work on it with any format.

**Comment by StanCallewaert** [comment]
Now the occupancy will even be a URI, this means that we can have a thorough description of what the definition of each value is.

**Comment by pietercolpaert** [comment]
@ChristopheVersieux After discussion here in the Spitsgids HQ, we will keep on using a URI/term instead of a number. The reason for this is that we need to be sure that what e.g., Railer means with a certain feedback is exactly the same as what BeTrains intended to say.

**Comment by StanCallewaert** [comment]
@jncn We changed up the post request to make sure we know about which train people are giving feedback. E.g. when somebody post feedback for a train his occupancy two days after it drove, we still need to know that it was the train of 2 days ago and not the one of the day he posted the feedback.
