### ISSUE TITLE
Change connections get request (add occupancy)

### ISSUE THREAD

**Issue by StanCallewaert** [iRail/iRail#182]
## GET (http://api.irail.be/connections/?...)

A possible XML response of a GET request to the URL above is shown below:

<pre>
&lt;connections version="1.1" timestamp="1468224822"&gt;
  &lt;connection id="0"&gt;
    &lt;departure delay="0" canceled="0"&gt;
      &lt;station id="BE.NMBS.008883006" locationX="4.137662" locationY="50.605079" URI="http://irail.be/stations/NMBS/008883006" standardname="Braine-le-Comte"&gt;Braine-le-Comte&lt;/station&gt;
      &lt;time formatted="2016-07-16T10:22:00"&gt;1468657320&lt;/time&gt;
      &lt;vehicle&gt;BE.NMBS.S23760&lt;/vehicle&gt;
      &lt;platform normal="1"&gt;4&lt;/platform&gt;
      &lt;direction&gt;Leuven&lt;/direction&gt;
      <b>&lt;occupancy URI="https://api.irail.be/terms/high"&gt;high&lt;/occupancy&gt;</b>
    &lt;/departure&gt;
    &lt;arrival delay="0" canceled="0"&gt;
      &lt;station id="BE.NMBS.008833001" locationX="4.715866" locationY="50.88228" URI="http://irail.be/stations/NMBS/008833001" standardname="Leuven"&gt;Leuven&lt;/station&gt;
      &lt;time formatted="2016-07-16T11:48:00"&gt;1468662480&lt;/time&gt;
      &lt;vehicle&gt;BE.NMBS.S23760&lt;/vehicle&gt;
      &lt;platform normal="1"&gt;B&lt;/platform&gt;
      &lt;direction&gt;Leuven&lt;/direction&gt;
    &lt;/arrival&gt;
    &lt;duration&gt;5160&lt;/duration&gt;
    <b>&lt;occupency URI="https://api.irail.be/terms/high"&gt;high&lt;/occupency&gt;</b>
    &lt;vias number="1"&gt;
      &lt;via id="0"&gt;
        &lt;arrival delay="0" canceled="0"&gt;
          &lt;time formatted="2016-07-16T11:06:00"&gt;1468659960&lt;/time&gt;
          &lt;platform normal="1"&gt;9&lt;/platform&gt;
        &lt;/arrival&gt;
        &lt;departure delay="0" canceled="0"&gt;
          &lt;time formatted="2016-07-16T11:12:00"&gt;1468660320&lt;/time&gt;
          &lt;platform normal="1"&gt;14&lt;/platform&gt;
          <b>&lt;occupancy URI="https://api.irail.be/terms/low"&gt;low&lt;/occupancy&gt;</b>
        &lt;/departure&gt;
        &lt;timeBetween&gt;360&lt;/timeBetween&gt;
        &lt;station id="BE.NMBS.008814001" locationX="4.336531" locationY="50.835707" URI="http://irail.be/stations/NMBS/008814001" standardname="Brussel-Zuid/Bruxelles-Midi"&gt;Brussels-South/Brussels-Midi&lt;/station&gt;
        &lt;vehicle&gt;BE.NMBS.IC3710&lt;/vehicle&gt;
        &lt;direction&gt;Brussels Airport - Zaventem&lt;/direction&gt;
      &lt;/via&gt;
    &lt;/vias&gt;
  &lt;/connection&gt;
  ...
&lt;/connections&gt;
</pre>

Occupancy can be following values: "https://api.irail.be/terms/unknown", "https:/api.irail.be/terms/low", "https://api.irail.be/terms/medium", "https://api.irail.be/terms/high".

**Comment by jncn** [comment]
I'd suggest to implement `occupancy` inside `via` > `departure`, instead of in the root of `via`.

**Comment by StanCallewaert** [comment]
@jncn This intention here is that the value of the occupency is about the whole ride an not only about the departure. Let's see what @pietercolpaert thinks about this.

**Comment by jncn** [comment]
@StanCallewaert Fair enough, but it's inconsistent with `connection` or `liveboard` > `departure`. 

And now I think about it, it actually is only about the departure. For the next section of your trip, the value could be something totally different. 
e.g. Change trains in Brussel-Centraal in the morning, on to a train to Eupen. Will be very crowded only until Brussel-Noord, which is the next stop.

**Comment by StanCallewaert** [comment]
Now the occupancy will even be a URI, this means that we can have a thorough description of what the definition of each value is.

**Comment by jncn** [comment]
Cool, but dirtier to implement 😉
Is it an option to keep this consistent with `station`, like this:
` <occupancy URI="https://api.irail.be/feedback/low.html">low</occupancy>`

**Comment by StanCallewaert** [comment]
@jncn But if you get on in Kortrijk to get to Brussels it will not be crowded at all until you get to Ghent. There are more examples of it but you make a good poin. I will discuss it with my colleagues.

**Comment by StanCallewaert** [comment]
@jncn You are right about the URI part, I'll change it immediately!

**Comment by StanCallewaert** [comment]
Hi @jncn, after a small discussion we decided to indeed put the occupancy of a via in the departure block as you suggested. Since we are now using the departure connection to indicate the occupancy for a trip it makes a lot of sence!
