### ISSUE TITLE
Make sure a regular user has write permissions to execute 'composer install'

### ISSUE THREAD

**Issue by StanCallewaert** [iRail/iRail#185]
As an intermediate solution the README.md file says 'sudo composer install'. This is however an ugly/hacky command. Therefore, one should make sure the write permissions are fixed. Until now, this error log comes up if somebody tries to 'composer install' the project:
```
[ErrorException]                                                             
  file_put_contents(/.../iRail/vendor/composer/autoload_namespaces.php): failed to open stream: Permission denied
```

**Comment by pietercolpaert** [comment]
This is because you did a composer install earlier with `sudo`. It's thus not really an issue of the iRail code...
