### ISSUE TITLE
Add methods to filter transport options

### ISSUE THREAD

**Issue by seppestas** [iRail/iRail#199]
The official NMBS app provides a way to filter transport options, including the types of train, when searching for routes and displaying station info. This is a very handy feature, since HSTs like Thalys require you to have a special ticket, meaning you don't typically use them on your daily commute.

Related Twitter thread: https://twitter.com/iRail/status/755668155217899520

It would be nice if the iRail API also exposes this functionality in the "Querying for a route from one station to another" and "Departures and Arrivals in a certain station" endpoints.

By looking what the app sends to the NMBS server at http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/mgate.exe, I found this can be done by changing the `value` of `jnyFltrL` in `svcReqL` (whatever that mumble-jumble means, I'm sure some of you guys know) in the request body of the request when searching for routes:

Request body with every transport option enabled:

```
...
"jnyFltrL": [
    {
        "mode": "INC",
        "type": "PROD",
        "value": "1861"
    }
],
...
```

Request body with HST disabled:

```
...
"jnyFltrL": [
    {
        "mode": "INC",
        "type": "PROD",
        "value": "1860"
    }
],
...
```

**Comment by pietercolpaert** [comment]
Thanks for the issue!

I'm not sure however we need to implement this: is it such a pain to just hit the middle button in the pebble app to skip international trains? And if so, shouldn't the NextTrain folks just skip these on their side?

If we decide to implement it on our side, then it can be implemented here: https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php#L96. We can then introduce a new parameter `&typeOfTransport=nointernationaltrains` or something similar.

**Comment by seppestas** [comment]
Pressing the button in the Next Train Pebble app is not a big pain, but the problem with that is that you don't see the train type in the app. So you don't know you have to skip until you go and look at the information on the platform, which kind of defeats the purpose of the app.

The endpoint used by iRail seems to be different than the one used by the official iPhone app. Do you know the mapping of the binary value that should be put in the `$trainsonly` variable / `prod` field?

IMO it might be nice to have some kind of `allow_transport` and `disallowed_transport` parameter. This way it is easier to just say: give me all trains except for HST trains.

**Comment by seppestas** [comment]
Based on the requests sent by the NMBS website, it seems like the first bit (from the left) indicates international trains.

I'm looking in to having a `trains_no_international` option for the `$typeOfTransport` parameter.
