### ISSUE TITLE
Integrate connection identifiers in the responses

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#219]
In the responses, when a departure is given, we can link this departure to the connection URI. A connection URI is created as follows:

```
http://irail.be/connections/{departurestationid}/{date}/{route id}
```
 * The departure station id is given without 00 up front. This would be a good example for for instance Ghent Sint Pieters: `8892007`
 * The date is provided in the timezone  `Europe/Brussels`! The date is provided in the format: YYYYMMDD (without dashes). For example: `20160712`
 * The route id is for instance `P8008`.

@StanCallewaert - can you mention this issue when you pull request something that fixes this?

**Comment by StanCallewaert** [comment]
This can be closed

**Comment by pietercolpaert** [comment]
Thanks!
