### ISSUE TITLE
sometimes vehicle info returns invalid JSON string

### ISSUE THREAD

**Issue by bertBruynooghe** [iRail/iRail#22]
colon is missing before last item:

http://api.irail.be/liveboard/?arrdep=ARR&fast=true&station=Brussel-Zuid&lang=nl&format=jsonp&callback=define&time=1731&date=01102012

returned 
define({"version":"1.1","timestamp":"1326207718","station":"Brussel Zuid","stationinfo":{"id":"BE.NMBS.008814001","locationX":"4.336922","locationY":"50.836782","name":"Brussel Zuid","standardname":"Brussels South"},"arrivals":{"number":"23","arrival":[{"id":"0","delay":"0","station":"Jemeppe-Sur-Sambre","stationinfo":{"name":"Jemeppe-Sur-Sambre"},"time":"1326211920","vehicle":"BE.NMBS.P8722","platform":"21","platforminfo":{"name":"21","normal":"1"},"left":"0"},{"id":"1","delay":"0","station":"Oostende","stationinfo":{"name":"Oostende"},"time":"1326212040","vehicle":"BE.NMBS.P8005","platform":"15","platforminfo":{"name":"15","normal":"1"},"left":"0"},{"id":"2","delay":"0","station":"Gent-Sint-Pieters","stationinfo":{"name":"Gent-Sint-Pieters"},"time":"1326212100","vehicle":"BE.NMBS.P8014","platform":"10","platforminfo":{"name":"10","normal":"1"},"left":"0"},{"id":"3","delay":"0","station":"Leuven","stationinfo":{"name":"Leuven"},"time":"1326212160","vehicle":"BE.NMBS.CR3766","platform":"14","platforminfo":{"name":"14","normal":"1"},"left":"0"},{"id":"4","delay":"0","station":"Nijvel","stationinfo":{"name":"Nijvel"},"time":"1326212220","vehicle":"BE.NMBS.L6387","platform":"21","platforminfo":{"name":"21","normal":"1"},"left":"0"},{"id":"5","delay":"0","station":"Brussel-Zuid","stationinfo":{"name":"Brussel-Zuid"},"time":"1326212280","vehicle":"BE.NMBS.CR6587","platform":"17","platforminfo":{"name":"17","normal":"1"},"left":"0"},{"id":"6","delay":"0","station":"Sint-Niklaas","stationinfo":{"name":"Sint-Niklaas"},"time":"1326212340","vehicle":"BE.NMBS.IC2315","platform":"8","platforminfo":{"name":"8","normal":"1"},"left":"0"},{"id":"7","delay":"0","station":"Louvain-La-Neuve-Univ.","stationinfo":{"name":"Louvain-La-Neuve-Univ."},"time":"1326212340","vehicle":"BE.NMBS.IR3916","platform":"13","platforminfo":{"name":"13","normal":"1"},"left":"0"},{"id":"8","delay":"0","station":"Antwerpen-Centraal","stationinfo":{"name":"Antwerpen-Centraal"},"time":"1326212400","vehicle":"BE.NMBS.IR2816","platform":"20","platforminfo":{"name":"20","normal":"1"},"left":"0"},{"id":"9","delay":"0","station":"Moeskroen","stationinfo":{"name":"Moeskroen"},"time":"1326212460","vehicle":"BE.NMBS.P8513","platform":"9","platforminfo":{"name":"9","normal":"1"},"left":"0"},{"id":"10","delay":"0","station":"Oudenaarde","stationinfo":{"name":"Oudenaarde"},"time":"1326212460","vehicle":"BE.NMBS.P8906","platform":"","platforminfo":{"name":"","normal":"1"},"left":"0"},{"id":"11","delay":"0","station":"Brussel-Zuid","stationinfo":{"name":"Brussel-Zuid"},"time":"1326212520","vehicle":"BE.NMBS.IC3437","platform":"","platforminfo":{"name":"","normal":"1"},"left":"0"},{"id":"12","delay":"0","station":"Knokke","stationinfo":{"name":"Knokke"},"time":"1326212640","vehicle":"BE.NMBS.IC1538","platform":"15","platforminfo":{"name":"15","normal":"1"},"left":"0"},{"id":"13","delay":"0","station":"Essen","stationinfo":{"name":"Essen"},"time":"1326212700","vehicle":"BE.NMBS.IC4516","platform":"18","platforminfo":{"name":"18","normal":"1"},"left":"0"},{"id":"14","delay":"0","station":"Geraardsbergen","stationinfo":{"name":"Geraardsbergen"},"time":"1326212760","vehicle":"BE.NMBS.CR1588","platform":"7","platforminfo":{"name":"7","normal":"1"},"left":"0"},{"id":"15","delay":"0","station":"Luik-Guillemins","stationinfo":{"name":"Luik-Guillemins"},"time":"1326212820","vehicle":"BE.NMBS.IC1716","platform":"6","platforminfo":{"name":"6","normal":"1"},"left":"0"},{"id":"16","delay":"0","station":"Brussel-Zuid","stationinfo":{"name":"Brussel-Zuid"},"time":"1326212820","vehicle":"BE.NMBS.IC2137","platform":"13","platforminfo":{"name":"13","normal":"1"},"left":"0"},{"id":"17","delay":"0","station":"Kortrijk","stationinfo":{"name":"Kortrijk"},"time":"1326212880","vehicle":"BE.NMBS.IR3139","platform":"20","platforminfo":{"name":"20","normal":"1"},"left":"0"},{"id":"18","delay":"0","station":"Brussel-Nat-Luchthaven","stationinfo":{"name":"Brussel-Nat-Luchthaven"},"time":"1326212880","vehicle":"BE.NMBS.IR3516","platform":"","platforminfo":{"name":"","normal":"1"},"left":"0"},{"id":"19","delay":"0","station":"Quievrain","stationinfo":{"name":"Quievrain"},"time":"1326212940","vehicle":"BE.NMBS.IC1738","platform":"10","platforminfo":{"name":"10","normal":"1"},"left":"0"},{"id":"20","delay":"0","station":"Gent-Sint-Pieters","stationinfo":{"name":"Gent-Sint-Pieters"},"time":"1326213000","vehicle":"BE.NMBS.IR3538","platform":"","platforminfo":{"name":"","normal":"1"},"left":"0"},{"id":"21","delay":"0","station":"Antwerpen-Centraal","stationinfo":{"name":"Antwerpen-Centraal"},"time":"1326213000","vehicle":"BE.NMBS.IR3115","platform":"17","platforminfo":{"name":"17","normal":"1"},"left":"0"}{"id":"21","delay":"0","station":"Antwerpen-Centraal","stationinfo":{"name":"Antwerpen-Centraal"},"time":"1326213000","vehicle":"BE.NMBS.IR3115","platform":"17","platforminfo":{"name":"17","normal":"1"},"left":"0"}]}})

**Comment by pietercolpaert** [comment]
Seems like a new error popped up right now, but the JSON is valid... Closing in favor of fixing #61
