### ISSUE TITLE
Sometimes, connections URI is not correct

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#224]
You use `substr($vehicle, strrpos($vehicle, '.')+1)` in the logic to create a URI for a connection. However, in e.g., the vehicleinformation.php file, the `$vehicle` comes from the GET parameter and may not contain a `BE.NMBS.` before it. If it doesn't, the `strrpos` will return 0, and the +1 will make sure 1 letter is cut off from the vehicle id.

Example: http://api.spitsgids.be/vehicle.php?id=P8008 → and check the connections URI

@StanCallewaert: can you fix this?

**Comment by StanCallewaert** [comment]
This can issue can be closed.
