### ISSUE TITLE
Response header message on error is wrong

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#236]
The response code now should be in the body as it's now the header message (which should be Bad Request when 400 is returned-

**Comment by pietercolpaert** [comment]
Seems like this is a long standing problem in the iRail API, not just for the POST requests.

**Comment by Bertware** [comment]
@pietercolpaert What do you mean exactly with this issue / has this been resolved in the meanwhile? Error messages include the response code and error message, HTTP header code is set as well.
