### ISSUE TITLE
When requesting Departures, account for delays

### ISSUE THREAD

**Issue by ikbenmartijn** [iRail/iRail#24]
Example:
Train A leaves at 9:20 and has a delay of 7 minutes
Train B leaves at 9:25
Train C leaves at 9:30

Request at 9:19 will show A, B and C
Request at 9:20 will show A, B and C
Requests from 9:21 until 9:25 will show B and C, while A still hasn't departed
Request from 9:26 until 9:30 will show C while train A was still arriving/departing until 9:27

**Comment by pietercolpaert** [comment]
I believe this is fixed on the side of SNCB/NMBS now. Could you double check? Thanks in advance!

**Comment by jncn** [comment]
This has been fixed for a while, indeed!
