### ISSUE TITLE
Feedback API does not save Feedback when param 'to' is given.

### ISSUE THREAD

**Issue by SerkanYildiz** [iRail/iRail#244]
Today, I tried to give feedback and help the community with data about the trains. But something really weird happened. My feedback didn't count. There was just a questionmark? So, I decided to clone the api, the last version if irail/hyperRail to figure out.
So, this is where the weirdness is I think. Let's take a look in this code 
![weird stuff](https://cloud.githubusercontent.com/assets/299328/17234375/b23fd4fa-5538-11e6-9ba1-399dbb55cbf2.png)

I added some debug code like var_dump etc to check what the actual value of those vars are. $errorCheck remains ALWAYS 0 (my case is the train from Brussels-North to Genk)
Because it remains a 0 and I have given a to= parameter, there is no Feedback registration somewhere. I checked MongoDB, and there is no collection named Feedback. So I think this confirms that there is no insert happening. Can @StanCallewaert or you @pietercolpaert look into this?

**Comment by StanCallewaert** [comment]
Hello @SerkanYildiz, I think I fixed your issue with this pull request: https://github.com/iRail/iRail/pull/246. Could you check it?

**Comment by pietercolpaert** [comment]
@SerkanYildiz Can you confirm this issue is fixed now? Put it in production

**Comment by jncn** [comment]
Don't think is fixed... At least nothing changes when I post.

**Comment by Bertware** [comment]
The 'to' parameter isn't supported for now. Every request to spitsgids is about 1 departure, the to parameter will be ignored until we can bring it back in a clean and robust way. See https://docs.irail.be
