### ISSUE TITLE
Cronjob doesn't work

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#245]
Cronjob to generate data for an extra day doesn't work

@StanCallewaert: would you be able to give this a quick look?

**Comment by StanCallewaert** [comment]
Hi @pietercolpaert, I've notice you created this issue during the weekend. For now, there is no structural train data. This means that the script won't generate data on Friday at 3:30 AM and Saturday at 3:30 AM for now.

Could you check if it generated data on Sunday?

**Comment by Haroenv** [comment]
since this was merged, is this issue fixed?

**Comment by pietercolpaert** [comment]
Nee


Op di 9 aug. 2016 21:10 schreef Haroen Viaene <notifications@github.com>:

**Comment by pietercolpaert** [comment]
It appears like this issue was not fixed yet

**Comment by ChristopheVersieux** [comment]
Is that the source of all the "unknow" as result for occupancy?

**Comment by pietercolpaert** [comment]
Yes it is! Fixing as we speak!

**Comment by pietercolpaert** [comment]
This works now for the next day: https://irail.be/route?to=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008814001&from=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008892007&date=170816&time=0816&timeSel=depart
