### ISSUE TITLE
Add overview page for all of the terms

### ISSUE THREAD

**Issue by Haroenv** [iRail/iRail#250]
Right now I don't really see a description/list of the three occupancy terms. I'd suggest that http://api.irail.be/terms/index.html would contain something like this:

```
<h1>iRail terminology</h1>
<p>Terminology used throughout the iRail project can be found here:</p>
<section id="occupancy">
  <h2>Occupancy</h2>
  <ul>
    <li><a href="http://api.irail.be/terms/unknown">terms/unknown</a>. Unknown: there is insufficient information to define an occupancy level.</li>
    <li><a href="http://api.irail.be/terms/low">terms/low</a>. Low occupancy: there are plenty of seats left</li>
    <li><a href="http://api.irail.be/terms/medium">terms/medium</a>. Medium occupancy: it is hard to find a seat and it is difficult to sit together.</li>
    <li><a href="http://api.irail.be/terms/high">terms/high</a>. High occupancy: there are no seats left and people have to stand up</li>
  </ul>
</section>
```

and each of the individual terms also having a link to /terms/.

I however don't find these files in this repository, this is probably because the terms are currently added manually and not tracked in this repository. I think it could be useful to either put static files here, or generate them from a database (or with a static site generator, maybe even a server-side redirect to some github pages site with these terms). What is your opinion?

**Comment by pietercolpaert** [comment]
Files can be found here: https://github.com/iRail/iRail/tree/master/api/terms

**Comment by Haroenv** [comment]
If I understand it correctly, this isn't in production yet?

**Comment by pietercolpaert** [comment]
Not yet in master. Will do next time I put something in production!

https://github.com/iRail/iRail/compare/development?expand=1
