### ISSUE TITLE
Return connection URI and occupancy in vehicle overview

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#257]
Make sure e.g.,
http://api.irail.be/vehicle/?id=BE.NMBS.IC545&format=XML

shows the occupancy  and the URI of a connection

**Comment by jncn** [comment]
Can someone fix this please?

**Comment by pietercolpaert** [comment]
Will do. There is a pull request but this doesn't fix it properly. Will try to make time for this asap!

**Comment by jncn** [comment]
@pietercolpaert Thanks a lot! Once these are fixed, I'll Railer will be released 😉

**Comment by pietercolpaert** [comment]
@jncn sorry for the late notice, but this has now been fixed! \o/

**Comment by jncn** [comment]
Thanks!
