### ISSUE TITLE
Trains with dual destinations should be 1 train instead of 2

### ISSUE THREAD

**Issue by ikbenmartijn** [iRail/iRail#26]
Example: P8004 rides in weekdays.
Train departs in Schaarbeek, has destinations De Panne/Kortrijk. Train is split up in Gent Sint-Pieters.

When seeing this train in Departures from Brussel-Centraal: this train is mentioned twice.
- as a train to De Panne - Platform X - Hour Y - Vehicle id Z
- as a train to Kortrijk - Platform X - Hour Y - Vehicle id Z

So to do this cleaner, add parameters to the Vehicle-object:

split_in : station-object (id, name, location)
destinations:
 --- departure-object 1 (vehicle, time, station-object, ...)
 --- departure-object 2 (vehicle, time, station-object, ...)
 --- ...

**Comment by pietercolpaert** [comment]
I'm afraid this is an issue in the back-end of the SNCB. We will not fix this.
