### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#260]
Apparently the HTTPS certificate has expired. This means you get a message like this when using irail.be, but even worse: no search results in the future version of Railer (or any other iOS app using HTTPS).

![img_0469](https://cloud.githubusercontent.com/assets/995815/18242319/090aea46-7356-11e6-91d6-906d7d6aabfe.jpg)

**Comment by pietercolpaert** [comment]
Forwarded this issue to our friends of @skyscrapers. They'll answer in a timely fashion so hang on!

**Comment by SamClinckspoor** [comment]
@jncn @pietercolpaert 
We use lets-encrypt on iRail, unfortunately it doesn't reload NGINX when renewing the certificate.

We have reloaded NGINX manually and will implement a solution to handle this automatically in the future.

**Comment by pietercolpaert** [comment]
Thanks @SamClinckspoor!
