### ISSUE TITLE
Inconsistent station name in liveboards when &fast=true

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#265]
Current value for a train's station attribute (json view) on requesting a liveboard.

* A liveboard without fast, for a train to Schaarbeek:
    
    station": "Schaarbeek/Schaerbeek",

* A liveboard with &fast=true, for a train to Schaarbeek: 

    "station": "Schaarbeek / Schaerbeek",

The problem:
* The fast value contains spaces. The normal value, and the value in stations.csv, do not. These spaces prevent the value from being parsed/compared to stations from stations.csv.

Proposed solution:
* Only return station names which are present in stations.csv. In this case, remove the spaces.

This was tested on train BE.NMBS.S61559 in a liveboard for Brussels-South

**Comment by pietercolpaert** [comment]
The function of fast=false is exactly to align each station name with an ID in stations.csv. This however is pretty slow. We should speed up that script in fact...

**Comment by Bertware** [comment]
I'll work without fast at the moment, and look into the api code when I have some spare time. Perhaps we could fix the source data? This would mean no processing is required when a query is made.

**Comment by pietercolpaert** [comment]
Source data is the SNCB website. Feel free to ask them to be consistent with their station names! :p

**Comment by Bertware** [comment]
Hmmm, I want this fixed within 10 years or so, so contacting doesn't seem a useful idea.

The best solution is a 1-on-1 lookup. This means `getStationFromName()` would be able to return instantly.
I see 2 possible implementations for this. 
* add to stations.csv. This seems a possibility, as it is relevant information whenever the stations need to be matched to a NMBS site.
* Create a lookup file or sqlite database. One table with two columns (old name / new name) would allow quick querying, after which we can load the new station. An alternative for a database would be to use a lookup.csv file, and load it into an array which is kept in memory, so we can use `station[NMBS name] ` to get the correct station object. This last one would have serious advantages, as it'd mean we'd only have to refresh the cache with a cron job, but all lookups would be instant, without even querying stations.

**Comment by Bertware** [comment]
The solution in https://github.com/iRail/stations/issues/111 provides a workaround for this issue, as the lookups will be so fast that `&fast=true` won't be needed anymore.
