### ISSUE TITLE
Add properties to Vehicle object

### ISSUE THREAD

**Issue by ikbenmartijn** [iRail/iRail#27]
For each stop show:
- delay
- delay forecast for future stops
Delays are only visible in Departures/Arrivals for now. It's more logical to keep delays attached to the Vehicle object.

- has_arrived (BOOL)
- has_left (BOOL)
These two properties make it easier to determine if a (delayed) train is currently parked in a station or on it's way to another.

**Comment by jncn** [comment]
Vehicles do show delays and platforms for each stop.
I don't think `has_arrived` and `has_left ` are needed once #92 is fixed.

**Comment by pietercolpaert** [comment]
Will close this as a duplicate of #92. Delay right now has been fixed
