### ISSUE TITLE
format=json doesn’t use correct format for numbers

### ISSUE THREAD

**Issue by Haroenv** [iRail/iRail#270]
Latitude and longitude should preferably be sent as numbers, instead of strings.

**Comment by Haroenv** [comment]
http://stackoverflow.com/a/6608413/3185307

`JSON_NUMERIC_CHECK` could be a solution

**Comment by pietercolpaert** [comment]
We had this remark before, but we are afraid that it would break existing applications right now so decided not to change this...

**Comment by Haroenv** [comment]
Won't apps that expect a string and parse it as a number just parse the number as a number?

**Comment by pietercolpaert** [comment]
Is this this big of a deal to risk possible breaks in existing applications? Not sure about whether they would actually break...

**Comment by Haroenv** [comment]
Not sure either. I guess we can continue parsing as number as consumer.

**Comment by pietercolpaert** [comment]
Ok that I close this issue?
