### ISSUE TITLE
There are some NFC tags in the trains... How should we play with them?

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#278]
Hi,

This is not really related to the API and the dev, but I received this interesting tip from one of my user:

> I've asked if there is a "list" of all tags id, still waiting for this.
> The tags are made for both driver and other train staff to identify where there are to there mobile phone, tablet, etc...
> They will stay there normally "forever" in newly ordered trains/infrastructure they might be included as already present. 
> I'll try to save a tag :-) never did, just tryed to scanned them, and that is working perfectly...
> So i if there is an id inside is would be a technical material identification...
> I'll send you this evening some info if i don't forget :-)
> regards.

What do you think about this?
Any idea? omething cool we should develop around them?

**Comment by Bertware** [comment]
As far as I know, these tags are available on both sides of every vehicle.
In theory, this could allow us to post the occupancy per vehicle (scan the tag, an occupancy dialog pops up, you select the occupancy and it's saved to the correct train).
This could improve the user experience on posting data, as you don't need to search your train anymore.

However, the ids of these tags can't be mapped to trains, as these ids are for internal use only. As long as this data is closed (not accessible by the public) this mapping cannot be provided by irail. If it were available, I would be willing to implement a query (to which train belongs this tag) and list (this train has tags x, y and a).

When we would get this data, we would also be able to deduce the amount of carriages in a train (if every carriage has 2 tags, and a train has 24 tags, it has 12 carriages). Furthermore, we could keep a database of every id and the corresponding carriage. This way we could tell users what wagons will be in their train. But again, we would need the nmbs to publish which ids are in which trains, which I don't see happening anytime soon.

I'll too try to copy a tag, to see what kind of information they contain.

**Comment by barthanssens** [comment]
I assume that a carriage is not always part of the same train.
Then again, using the id tag, you could also implement a fix-my-train (toilet out of order, heating/ventilation issue, damaged seats) and send feedback to the NMBS

**Comment by Bertware** [comment]
Do these tag IDs match any ids in the vehicle composition data? #383

**Comment by ChristopheVersieux** [comment]
Closing as suggestions have been added and it's not really related to irail.

**Comment by ChristopheVersieux** [comment]
Closing as suggestions have been added and it's not really related to irail.
