### ISSUE TITLE
Give a 404 instead of an empty array when wrong parameter given

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#279]
E.g., http://api.irail.be/liveboard/?station=BRUSSEL-CENTRAAL&fast=true&date=033117&time=1221 gives an empty array as the date is wrongly formatted. We should give a 404 instead of a 200 and an empty array

**Comment by Bertware** [comment]
Wouldn't a 400 invalid request, 412 requirement not fulfilled, or 421 unprocessable input be a more fit reply? This would make it clear to developers their request isn't correct. 404 should be only valid input without results IMO.

**Comment by pietercolpaert** [comment]
I can live with using a 400 instead
