### ISSUE TITLE
Delays are not taken into account for calculating connections

### ISSUE THREAD

**Issue by svaningelgem** [iRail/iRail#281]
Hello,

Quite often I have the issue that there is a delay of like 5-10 minutes in BXL North towards Herent.
If I go via Leuven, this delay is not reflected in the connection.

So for (a pure hypothetical) example I would see:
10.00 + 10' -> 10.17 BXL -> Leuven
10.24 -> 10.29 Leuven -> Herent

But this is just impossible. I mean, if a train has a delay, at least on this track (BXL-Leuven) it just can't make up that much lost time (maybe a minute or 2, not much more).
Is it possible to at least have 10' delay in Leuven too in order to find a good connection there?
So what I would expect to see is something like:
10.00 + 10' -> 10.17 + 10' BXL -> Leuven
10.54 -> 10.59 Leuven -> Herent [pure hypothetical train!]

Thanks!

**Comment by Bertware** [comment]
This seems to be an issue related to your application/website (in your case, deduceted from issue 279, beTrains), and not iRail. iRail only provides the nmbs data in API format, we don't alter the data except for some minor cleaning. (e.g. all delays, dates, ... in same format)

**Comment by pietercolpaert** [comment]
@svaningelgem Interesting suggestion! As we don’t control the execution of the route planning algorithm now though, we cannot correct this, as @Bertware stated.

In the future we hope to be able to allow this to be possible though!
