### ISSUE TITLE
Strip HTML tags from json on vehicle page

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#283]
Hello,

The JSON from many trains is not correct, due to some HTML parts in the issue description:

For instance:
https://api.irail.be/vehicle.php/?id=IC3130&lang=en&date=190417&time=1416&format=JSON&alerts=true

> 		"alert": [{
> 					"id": "0",
> 					"header": "Works Brussels-Nord - Brussels-Midi 29/04 - 01/05",
> 					"description": "From Saturday 29/04 to 1/05, trains will not stop at Brussels-Central station following works between Brussels-Nord and Brussels-Midi. <br />There will be major changes to the train service. <br /> <br /><a href="
> 					http: //www.belgianrail.be/jp/download/brail_him/1492504314215_JNM Templates Service train alternatif EN.pdf" target="_blank">Alternative train service Bruxelles-Nord/Brussel-Noord - Bruxelles-Midi/Brussel-Zuid</a>"}]},

The quotes makes the JSON invalid.

**Comment by Bertware** [comment]
This should be fixed by applying strip_tags() to all descriptions in endpoints which support the alert parameter.

**Comment by Haroenv** [comment]
That info is kinda useful though, what about just escaping the " like `\"`?

**Comment by ChristopheVersieux** [comment]
Escaping looks nice, but at the moment I would be happy with any solution that doesn't break the applications built on top of the API :-)
More users are starting to complain, it seems that the issue is bigger right now, maybe the NMBS is adding complexity to their HTML information

**Comment by Bertware** [comment]
Hmmm, I oversaw that the link led to a pdf file. Stripping would only leave the text inside the <a> element. Escaping, could be implemented using json_encode. This is not needed for XML (IIRC), since XML already uses CDATA tags for data like this.

**Comment by Bertware** [comment]
I opened a pull request, which behaves as I described above. @Haroenv please review and feel free to make remarks if you have any :)

**Comment by Bertware** [comment]
Merged & in production
