### ISSUE TITLE
Error 500 on all "vehicle.php" pages

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#285]
Hello,

Since this morning, none of the vehicule requests are working:

https://api.irail.be/vehicle.php/?id=IC1714

> This page isn’t working
> 
> api.irail.be is currently unable to handle this request.
> HTTP ERROR 500

I will also try to investigate, compare with NMBS, and try to send more info.

**Comment by modulebaan** [comment]
It seems to work fine now. Maybe @pietercolpaert can check the logfiles?

**Comment by ChristopheVersieux** [comment]
Yes indeed, it was a temporary issue, maybe related to some issues in the NMBS website (I had multiple feedback that platforms were missing and in the official application/website as well) ...

Anyway, I can close the issue, thanks.
