### ISSUE TITLE
[Question] Fetch stops for a connection

### ISSUE THREAD

**Issue by modulebaan** [iRail/iRail#286]
For github.com/irail/harbour-berail I want to add the ability to show the stops a train has between the departure station and the arrival station for a certain connection.

Is there a way to get it directly from the API or do I need to write a function that filters the stops between those 2 stations based on the vehicle endpoint?

**Comment by modulebaan** [comment]
The online routeplanner supports this:
- Search for a route
- Click on Details
- You can expand the route details and see the stops between the departure and arrival station

Also a map is displayed with the route that's also handy :)

**Comment by Bertware** [comment]
As far as I can see, this looks like one page, but are in fact 3 HTTP requests.

* Search for route (1 request, returns all routes)
* Show details (1 request per route, you can see a small spinner while it loads + shows up in network console)
* Show intermediary stops (1 request per train, again a spinner is visible + shows up in network inspector)

If you get 5 results, for a route with 2 trains, this would mean (1 query + 5 results + (5 results * 2 trains)) = 16 requests to get all intermediary stops for all routes. This can't be done by the API (it would result in too much calls/load for the nmbs, and response times would rise).

The only option would to make another endpoint to get details for a specific journey. This would be quite some work though, whereas [LinkedConnections ](http://linkedconnections.org/)might make your original idea possible in the future (show all intermediary stops in the route results). [LinkedConnections ](http://linkedconnections.org/) should form the new data source in the future, but is still a work in progress at the moment. Therefore I think the best option is to put this on hold until the data source natively supports it.

**Comment by pietercolpaert** [comment]
@modulebaan For now, I’d just write a function on client-side

@Bertware Also over here it would be interesting to study what the effect of Linked Connections would be

**Comment by modulebaan** [comment]
I will do that based on the vehicle endpoint:
- Get departure station and search in the vehicle route
- Loop until a via or arrival station is found
- Repeat for every vehicle in this route
