### ISSUE TITLE
[Question] Time between a via 

### ISSUE THREAD

**Issue by modulebaan** [iRail/iRail#287]
I have a question about the iRail API when I plan a route with a via in it.
If the arrive time at the via or the depart time at the via has a delay, will iRail show then the correct "timeBetween" property?

And if the delay is too big that you miss your via what then?

**Comment by Bertware** [comment]
`timeBetween = $departTime - $arrivalTime;`
(Source: https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php#L355 )
It's a simple time difference, taking delays into account is something that's possible client side.
If the delay is too big, the NMBS won't show the connection. (the API is only a machine-readable version of their routeplanner at the moment)

**Comment by modulebaan** [comment]
Thanks! Then I can add it to BeRail :)
