### ISSUE TITLE
Remove misleading connections from search results

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#289]
When searching for the last train of the day, sometimes a misleading result is showing up.
e.g. Search for Oostende to Antwerpen-Berchem, leaving from 23:00. The first result (23:05, IC522) only arrives the next morning with a 4,5 hour lay over in Ghent-Sint-Pieters.

Of course it is the responsibility from developers to clearly show this in the interface, however I think it would be a lot better if these results didn't show up in the first place, also in other use cases.

Bottomline: Can we implement a rule which omits search results with lay overs from over 90 minutes?

**Comment by Bertware** [comment]
I'd say this is something to check client side, as you can easily compare the departure and arrival date/time (I noticed you already implemented it this way). I can imagine that, when there are serious issues on the rail network, it is possible to have for example a 90 minute layover for "normal" trains.
Just my 2 cents :)

**Comment by pietercolpaert** [comment]
Good point @jncn! Question is: would anyone actually take a train with such a lay over? I would find that hard to believe...

**Comment by jncn** [comment]
I implemented this client side indeed. Nobody would like to take such trains, but I got feedback at the time from someone who accidentally took it, because he didn't check the arrival time...
Anyhow, I'll close this one.
