### ISSUE TITLE
Error 500 while looking for liveboard -> irail.be also struggling.

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#291]
See these urls:
https://api.irail.be/liveboard/?id=BE.NMBS.008892007
=> <error code="500">Could not get data. Please report this issue at https://github.com/irail/irail/issues/new</error>

https://irail.be/stations/NMBS/008881000
=> Indefinite loading

**Comment by Bertware** [comment]
irail.be has stopped working since the liveboard API call returns an error 500. The front end should probably show an error message instead of the infinite loading; 

I cannot trace the origin of the error 500 atm (don't have access to development machine). Anyone with a local setup who can reproduce and check the error in the logfiles?

**Comment by ChristopheVersieux** [comment]
Hello,
All API are broken for more than 24hours now.
Railer, BeTrains and irail are not working

Any idea who can help on that?

**Comment by Bertware** [comment]
@pietercolpaert @brechtvdv who can access the production server to check logs and to apply a hotfix?

**Comment by pietercolpaert** [comment]
I'm on holidays and will only be back next week. Maybe @brechtvdv is available?

**Comment by brechtvdv** [comment]
This should fix it: https://github.com/iRail/iRail/commit/8ec43089d0af3f10e1ea94d8cf5e061f6aa6eebd

**Comment by brechtvdv** [comment]
Sorry for pushing directly on master

**Comment by pietercolpaert** [comment]
@brechtvdv as I'm on holidays, can you access the server and put it in production?

**Comment by brechtvdv** [comment]
Done!

This can be closed.

**Comment by ChristopheVersieux** [comment]
I promised Pieter to write you a poem to thank you ;-)

Roses are red
Violets are blue
NMBS tries to make us afraid
Big Thanks to iRail crew!
