### ISSUE TITLE
NMBS blocked irail user agent

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#292]
NMBS blocked the iRail user agent, causing a total failure as can be seen here: #291 
Block was first discovered at 10-08-2017.

- Why was iRail blocked?
- Why did the NMBS not communicate anything? (suggests NMBS did this on accident?)
- How can we prevent this in the future, or how can we prevent being hit this hard? Are fallback options possible?

**Comment by pietercolpaert** [comment]
Asked SNCB, but no idea on their part. Will close this issue, but will follow up if a reply would follow.
