### ISSUE TITLE
Use of PHP exec should be avoided

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#295]
PHP executes shell code to determine the current version of the API. This should be avoided.
https://github.com/iRail/iRail/blob/master/includes/getVersion.php#L23

- [x] Remove the exec code.
- [x] GetVersion doesn't seem required, and should be removed if possible.

**Comment by Haroenv** [comment]
this seems to be the only place it used to be used https://github.com/iRail/iRail/blob/master/includes/getUA.php
