### ISSUE TITLE
Canceled trains are not indicated in the connection API (and nowhere on the website)

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#30]
This one is in fact 2 bugs.. 

1) When using iRail.be website for a station liveboards, the canceled trains are not shown, while the info is available on the Stations API, see the Android client:

![1](https://cloud.githubusercontent.com/assets/356214/3428719/ec053ef0-0044-11e4-9ce4-1fe9d2dfb362.png)

2) this "canceled" information is not shown in the connection API, giving no clue to the user that his train is in fact canceled, which is a huge problem!

id: "0",
departure: {
    delay: "0",
    station: "Tournai",
    stationinfo: {
        id: "BE.NMBS.008885001",
        locationX: "3.396936",
        locationY: "50.613125",
        name: "Tournai",
        standardname: "Tournai"
    },
    time: "1404125820",
    vehicle: "BE.NMBS.IC912",
    platform: "2",
    platforminfo: {
        name: "2",
        normal: "1"
    },
    direction: {
        id: "BE.NMBS.008841608",
        locationX: "5.62235",
        locationY: "50.6604",
        name: "Herstal",
        standardname: "Herstal"
    }
},
arrival: {
    delay: "0",
    station: "Mons",
    stationinfo: {
        id: "BE.NMBS.008881000",
        locationX: "3.942303",
        locationY: "50.45445",
        name: "Mons",
        standardname: "Mons"
    },
    time: "1404127440",
    vehicle: "BE.NMBS.IC912",
    platform: "2",
    platforminfo: {
        name: "2",
        normal: "1"
    },
    direction: {
        id: "BE.NMBS.008841608",
        locationX: "5.62235",
        locationY: "50.6604",
        name: "Herstal",
        standardname: "Herstal"
    }
},
duration: "1620"

![screenshot_2014-06-30-12-39-03](https://cloud.githubusercontent.com/assets/356214/3428728/17bc52a4-0045-11e4-8f4d-32915292c487.png)

**Comment by jncn** [comment]
I'm looking into this for vehicle info (and connections after that). 
I see some options for the output:
1. `delay="cancelled"`, which is not backwards compatible with some clients
2. `delay=1`, which is backwards compatible, but not very elegant
3. A new bool: `cancelled`
What do you guys suggest?

**Comment by pietercolpaert** [comment]
New boolean looks best to me...

**Comment by ChristopheVersieux** [comment]
I also think boolean is better.
Thanks for looking at this bug!

**Comment by pietercolpaert** [comment]
canceled=0 or 1 now in production!

@ChristopheVersieux Is this something you would still implement in BeTrains?

**Comment by ChristopheVersieux** [comment]
Might do it, just need time to work on it and develop, but as this feature
is missing for a very long time, I have to do it ;-)

**Comment by ChristopheVersieux** [comment]
@pietercolpaert Here it is: https://github.com/iRail/BeTrains-for-Android/commit/1abbe853ad3d05e61b0b10420cbcdc22393ecc2f#diff-c8a381617c875fab9f91659a13f25180

**Comment by pietercolpaert** [comment]
Love!!
