### ISSUE TITLE
Malformed JSON for liveboard when &alerts=true

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#311]
Hello,

Please have a look at this url, the JSON is not correct:
https://api.irail.be/liveboard.php/?id=008814001&date=230917&time=1857&format=JSON&fast=true&lang=en&alerts=true#

![screenshot from 2017-09-23 18-38-39](https://user-images.githubusercontent.com/356214/30775145-a59b932c-a08e-11e7-82ff-626f0a2e7451.png)

**Comment by Bertware** [comment]
Unrelated to #243, but will look into it and fix on Monday.

**Comment by ChristopheVersieux** [comment]
@Bertware Can you quickly remove the perturbations as a workaround while waiting for the full fix? The problem is coming with Brussels and some big cities, I am a little bit afraid to see the flow of bad ratings and uninstall that will happen ;-)

**Comment by Bertware** [comment]
Switch `&alerts=false` resolved this, I'd rather suggest pushing an app update with an updated URL at this moment, since most users will auto-update anyway?

**Comment by ChristopheVersieux** [comment]
Sorry, but application updates take weeks, month. Non geek users are not
interested by updates.

**Comment by Bertware** [comment]
This issue has been resolved in the codebase, however, I can't say anything on if and when this can be deployed to the old server. I can only say that this will be fixed when we switch over to the new server on Monday.

**Comment by pietercolpaert** [comment]
Manually fixed in production for now!

**Comment by ChristopheVersieux** [comment]
![giphy](https://user-images.githubusercontent.com/356214/30780500-6ca4324e-a10c-11e7-9b77-9791e0d9e7bb.gif)

**Comment by Bertware** [comment]
Permanently fixed on the new server now. A similar issue with alerts ( #313 ) has also been resolved already, beTrains is tested on the new server and works completely!
