### ISSUE TITLE
Connections API: could not get data when using optional parameters

### ISSUE THREAD

**Issue by PowerPlop** [iRail/iRail#316]
Example API GET: 

https://api.irail.be/connections/?from=Gent-Sint-Pieters&to=Mechelen&date=31122016&time=1230&timesel=departure

--> Could not get data

https://api.irail.be/connections/?from=Gent-Sint-Pieters&to=Mechelen

--> OK

Am I using a wrong GET statement?

**Comment by Bertware** [comment]
You're trying to look up data way in the past (10 months ago). Can you try if this data is available on the NMBS website?

**Comment by Bertware** [comment]
While your example API request was too long ago, we also noticed an error in the documentation. The documentation has been updated. The correct date format is ddMMyy, so `&date=300917` would be a valid argument to get the connections for tomorrow.

https://api.irail.be/connections/?from=Gent-Sint-Pieters&to=Mechelen&date=300917&time=1230&timesel=departure&format=json&lang=en&fast=false&typeOfTransport=trains&alerts=false&results=6

**Comment by PowerPlop** [comment]
Thanks for the information. The new date format fixes the request!
