### ISSUE TITLE
Liveboards, Connections and vehicle endpoint only work up to 1 week in the past

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#317]
The NMBS only provides information for up to 7 days ago. Returning a 400 bad request or 410 gone error would allow clients to act correctly / detect this. As an alternative, we could return a 500 error with a clear error message. 
At this time an empty liveboard or connections response is returned, or a 404 response in case of a vehicle.

**Comment by pietercolpaert** [comment]
404 is fine. It means:  we could not find any data on our system, but there may be other servers that do know something about this (open world assumption)
