### ISSUE TITLE
New security since new server?

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#322]
Hello,

Sorry, I am not a master in SSL, but since the latests changes on the server, a lot of devices are sending this error message and the application stopped displaying results:

SSLException: Fatal alert received handshake_failure 

From what I read here: https://github.com/square/okhttp/issues/2372#issuecomment-244807676 it might be related to TLS version.
(Sorry, I have no idea what that means)

Is that something you changed on the server? Any idea if this is something from server or the client?

Thanks.

**Comment by Bertware** [comment]
HTTPS is possible over a few protocols, each with their versions. There is both TLS and SSL. TLS has versions 1,1.1,1.2,1.3. SSL has v1, 2 and 3.

We dropped support for unsafe and/or deprecated protocols during our server move. Ensure you are using TLS 1.2. SSL 1,2,3 are not supported anymore, and TLS 1.0 will soon be disabled as well. For example SSL 3 is proven as unsafe.

If the errors started about 5 weeks back, this is the reason. Other clients can access the server without issues, so it's either the http client or the configuration which is causing issues.

**Comment by ChristopheVersieux** [comment]
Thank a lot for the explanation.
The issue is from a few weeks ago, so this is more than probably related.

I will update the client or use another one to fix it.
