### ISSUE TITLE
Unjustified canceled trains

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#323]
For at least a week, some trains are displayed as canceled although they are not (see screenshot).
e.g. IC2435 and IC2436 `https://api.irail.be/connections/?to=doornik&from=brussel-centraal`

<img width="1432" alt="screen shot 2017-10-24 at 16 43 39" src="https://user-images.githubusercontent.com/995815/31946891-b8c2300e-b8db-11e7-9363-a4dcc575ec52.png">

**Comment by Bertware** [comment]
I know where this bug originates in the code, but I don't know what the NMBS data is at that point. It seems to be a temporary thing in the NMBS data, as it's correct now, so I have to see it at the very moment this bug occurs...

**Comment by Bertware** [comment]
If you come accross this again, please add `&debug` to the end of the url. This will store the NMBS data on disk, so we can see the exact response later. Having one of those should be enough to resolve this issue

**Comment by jncn** [comment]
Right now: IC740 `https://api.irail.be/connections/?to=gent-sint-pieter&from=kortrijk`

**Comment by Bertware** [comment]
Got it!

**Comment by Bertware** [comment]
The fix is now in production. I've left the debug switch there for now, in case they add another enum type to their raw data and we need to fix it again.

**Comment by jncn** [comment]
Alright, you're faster than your shadow 🙂 Thanks, @Bertware!
