### ISSUE TITLE
Misunderstanding? Error 404

### ISSUE THREAD

**Issue by Tiraflo** [iRail/iRail#324]
Hello iRail's Team,

First of all, thank you for what you have done so far. I enjoy reading the iRail documentation and retrieving some info about my daily trains.

However, I don't succeed at getting back all the data I would like to. I have no issue while making a REST request for these URIs for example:
http://irail.be/stations/NMBS/?
http://irail.be/stations/NMBS/008811163/?

But when I want to retrieve information regarding vehicles or from liveboard by using the following URIs:
http://irail.be/liveboard/?station=Bordet (based on https://docs.irail.be/#liveboard-liveboard-api)
http://irail.be/vehicle/?id=BE.NMBS.IC4042 (based on https://docs.irail.be/#vehicle-vehicle-api and on a currently driving train)
http://irail.be/vehicle/IC4042/ (based on https://github.com/iRail/iRail/issues/318)
The only thing I obtain is a 404 error.

Perhaps am I doing something wrong? By reading this topic (https://github.com/iRail/iRail/issues/318) I assumed that, maybe, everything is not ready yet but I don't read anything about that in the documentation. Also, I'm not very familiar with REST APIs and so on. Actually, the iRail APIs are "my" first REST APIs... Which could explain my failure.

Best regards,

Tiraflo

**Comment by Bertware** [comment]
Well, this is awkward.. Apparently the documentation doesn't mention the base URL anywhere..

The base URL is https://api.irail.be/

This means the endpoints are https://api.irail.be/stations/ , https://api.irail.be/liveboard/?station=Bordet and https://api.irail.be/vehicle/?id=BE.NMBS.IC4042

As a coincidence, irail.be also hosts the same station list, which could be confusing as this makes one request work and others not.

Insecure requests are automatically upgraded.

I hope this answers your questions

**Comment by Tiraflo** [comment]
Thank you for this quick answer.

I have already seen in the "old" documentation (https://hello.irail.be/api/1-0/) the base URL was https://api.irail.be/ but in the first sections of the new doc, it would seem the base URL is rather http//irail.be (https://docs.irail.be/#header-uri%E2%80%99s):

> The following objects are identified by a URI:
> 
>     Stations: every station has a URI, similar to http://irail.be/stations/NMBS/008814001, where 008814001 is based on an existing identifier used by the NMBS.
> 
>     Vehicles: every vehicle has a URI, which identifies the trip at a certain time which is made by this vehicle. An example URI is http://irail.be/vehicle/IC532.
> 
>     Departures: A departure is a certain train, leaving a certain station, at a certain day. The combination of these 3 fields is unique through time, which makes it perfect as an identifier. Example: http://irail.be/connections/8814001/20171002/IC532.

Anyway, everything goes right now. Thank you a lot.

I also noticed differences between retrieved delay values and delays which can be seen on the SNCB/NMBS website (belgianrail.be) but I'm waiting for deeper investigations before asserting it. If needed, I will create a new topic.

Best regards,

Tiraflo

**Comment by Bertware** [comment]
I tried to clear up the documentation ab it.
Delays should be the same as the delays on the NMBS website or the NMBS application. If there are huge differences, it's probably a bug, as we had to rewrite quite some code last week. All delay and time bugs should've been resolved their though.

**Comment by Tiraflo** [comment]
Thank you for the documentation.
Regarding delays, I'll check and recreate another topic if I see something strange.
According to me, this topic can be closed.
Thank you again for the support.
