### ISSUE TITLE
"Results" parameter is not used in Connections API?

### ISSUE THREAD

**Issue by PowerPlop** [iRail/iRail#327]
When I try to choose the amount of results by using "&results=1", I still get 6 (=default) results.

[https://api.irail.be/connections/?to=mechelen&from=duffel&results=1](https://api.irail.be/connections/?to=mechelen&from=duffel&results=1)

**Comment by Bertware** [comment]
It's a guideline, but the server can choose to ignore this (and it does ignore this value at this moment). Reasons for ignoring this are changes in the codebase (the back-end code for this endpoint has completely changed 2 or 3 times already) and that this affects caching: it's simply faster to get you the 6 results than it is to get you 1 result. However, this might be implemented and put into production at any time, so you can include it in your request just in case. Client code should not be affected by the amount of results we return.

See http://docs.irail.be/#connections-connections-api
 ```
The number of results to return. Default value is 6. This might be used as a guideline for the server, but there is no guarantee the server will return this exact amount of results!
```

**Comment by PowerPlop** [comment]
Thanks for the answer!
I thought the api explanation was describing the default value '6'.
