### ISSUE TITLE
Use mobile API endpoint instead of parsing the NMBS website for vehicle information

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#332]
At this moment, we're parsing the NMBS website for vehicle information. Every now and then this page isn't available for a few seconds, and when the NMBS updates their website, this endpoint will break completely.

Therefore, we should switch to the mobile API, like we did for liveboards and routes. The endpoint for the following requests is http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/mgate.exe.

To overcome the need for a journey ID, we can lookup the journey ID by the train name:

`{"auth":{"aid":"sncb-mobi","type":"AID"},"client":{"id":"SNCB","name":"NMBS","os":"Android 7.0","type":"AND","ua":"SNCB/302240 (Android_7.0) Dalvik/2.1.0 (Linux; U; Android 7.0; HTC One Build/NRD90M)","v":302240},"formatted":false,"lang":"nld","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyMatch","req":{"date":"20171121","input":"ic537","jnyFltrL":[{"mode":"BIT","type":"PROD","value":"10101010000000"}]}}],"ver":"1.11"}`

From this response we can obtain a journey ID, which can be used to obtain the vehicle:

```
{"auth":{"aid":"sncb-mobi","type":"AID"},"client":{"id":"SNCB","name":"NMBS","os":"Android 5.0.2","type":"AND","ua":"SNCB/302132 (Android_5.0.2) Dalvik/2.1.0 (Linux; U; Android 5.0.2; HTC One Build/LRX22G)","v":302132},"lang":"nld",
"svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyDetails","req":{"jid":"1|297|0|80|21112017","getTrainComposition":false}}],"ver":"1.11","formatted":false}
```

Once switched to this data, the vehicle endpoint should be faster, have better availability, and be future-proof

**Comment by szawadski** [comment]
So now I understand why after a certain time, the delays are disappearing from the "vehicle" data.
Do you see any way to recover delays that happened in the past?

**Comment by Bertware** [comment]
We're working on new solutions which will keep historic data, so you can see the delay of a certain train at any time (e.g. the delay of train x stopping in brussels-south at 10:00, at 9:50, 9:51, 9:52, ...) This way you can see how the delays evolve over time. We're still testing though, so it can take a few months before it's finished and available to the public. Stay tuned to our blog at hello.irail.be or follow us at twitter @iRail in order to know when we make progress or put things in production ;)

**Comment by szawadski** [comment]
Great news. Sure I will stay tuned and test it as it becomes public.
BTW, I am impressed by your work. I actually thought it was made by
NMBS/SNCB itself....

**Comment by Bertware** [comment]
Requires a lot of testing in staging (as soon as the current changes in staging has been pushed to master, we can't test everything at once). Otherwise, this should be ready to merge to development and review.
