### ISSUE TITLE
Provide line number in liveboard for departures and arrivals

### ISSUE THREAD

**Issue by drupol** [iRail/iRail#334]
Hello,

Would it be possible to add in the departures, information regarding the train line.

Ex: Train IC1234 from Mons to Brussels: Line 96 ([wikipedia](https://en.wikipedia.org/wiki/Belgian_railway_line_96))

I've checked the sncb site and this information is never show to the visitor.
Therefore, do you think we should hardcode it ourself per station ?

Here's [the full list](https://fr.wikipedia.org/wiki/Liste_des_lignes_de_chemin_de_fer_de_Belgique).

Thanks.

**Comment by drupol** [comment]
Hello,

After some discussion on Gitter, we are using Wikidata and store using the "Exact Match" property the irail station identifier (URL) for each station

We have to make sure that every stations has basically 4 properties:

1. **Part of**: contains lines that pass through the station, in used or not.
2. **Connecting lines**: contains lines that pass through the station, in use only.
3. **Exact match**: an URL (**in HTTP only!**) to the station on irail.be domain. ex: http://irail.be/stations/NMBS/008884541
4. **Adjacent stations**': According to me, adjacent stations are the first stations you find if you go in any directions from the current station.

Then, it's possible to retrieve the list of station associated to a line using a sparql query:

1. http://tinyurl.com/yca8pywf (without aggregation)
2. http://tinyurl.com/yaxk7oaw (with aggregation)

The bad news is that we have to fill in those information ourselves in Wikidata.

In order to speed up the process, I'm using a small tool that I build and available at: https://young-cliffs-90300.herokuapp.com/web
This map shows stations that has been linked to irail.be. A lot has already been done, but there are still some work to do and you are welcome to help.

I've got some questions like:

1. Why some stations like: Ronse, Herne, Viane-Moerbeke, ... are not available in Wikidata? Should we create them ourselves ?

**Comment by pietercolpaert** [comment]
Yes! Creating them ourselves with the right type and line information :)

**Comment by drupol** [comment]
Updating the tools, add a visual marker when a station has no adjacent stations.

**Comment by drupol** [comment]
Most of the stations are done.

![screenshot-young-cliffs-90300 herokuapp com-2017-12-29-08-58-55](https://user-images.githubusercontent.com/252042/34432323-8c68dac0-ec76-11e7-921b-beab5934b85c.png)

Now we need to create the missing stations in Wikipedia and then, in Wikidata.

Useful links:

1. [Lijst van NMBS-stations in België](https://nl.wikipedia.org/wiki/Lijst_van_NMBS-stations_in_Belgi%C3%AB)

**Comment by drupol** [comment]
Ok, all stations from Belgium are covered!

![screenshot-young-cliffs-90300 herokuapp com-2017-12-29-22-54-08](https://user-images.githubusercontent.com/252042/34448156-352de942-eceb-11e7-8d8e-3b12525ed807.png)

Finally!

**Comment by drupol** [comment]
It is also possible, with a simple BFS algo to find the route between two stations, thanks to all these new data (_esp. the adjacent station property_)

![screenshot_20171230_110213](https://user-images.githubusercontent.com/252042/34453312-a3214adc-ed51-11e7-91ec-f8bbccc94755.png)

**Comment by pietercolpaert** [comment]
That’s some great work @drupol! Do you think this issue can now be closed?

**Comment by drupol** [comment]
Sure we can close it now.

As an outcome of this issue, the NodeJS package [irail-api](https://www.npmjs.com/package/irail-api) is able to retrieve stations from iRail, lines and adjacent stations from Wikidata.
