### ISSUE TITLE
Can't retrieve connection

### ISSUE THREAD

**Issue by DylanVanAssche** [iRail/iRail#335]
I'm trying to do a request to the /connections endpoint:
`https://api.irail.be/connections/?from=Vilvoorde&to=Mechelen&date=181217&time=2018&timesel=departure&typeOfTransport=all&format=json&lang=en`

However this fails with the following error:
`{"error":404,"message":"Could not find a station with id 00221082."}`

But when I swap the `from` and `to` parameters the request works perfectly:
`https://api.irail.be/connections/?from=Mechelen&to=Vilvoorde&date=181217&time=2018&timesel=departure&typeOfTransport=all&format=json&lang=en`

`{"version":"1.1","timestamp":"1513624819","connection":[{"id":"0","departure":{"delay":"1260","station":"Mechelen","stationinfo":{"id":"BE.NMBS.008822004","locationX":"4.482785","locationY":"51.017648","@id":"http://irail.be/stations/NMBS/008822004","standardname":"Mechelen","name":"Mechelen"},"time":"1513623840","vehicle ...`

**Comment by Bertware** [comment]
I'll look into this in the first 2 weeks of January (so you have an ETA)

**Comment by DylanVanAssche** [comment]
Thanks! But I'm not in a hurry :)
I discovered that the issue might be this parameter: `typeOfTransport=all`
Without that parameter, everything works fine.

**Comment by Bertware** [comment]
I confirmed this issue earlier, but when trying to research and fix it now, it seems the issue has resolved itself. This means it's likely an issue on the NMBS side, which has been resolved by now.
Can't confirm this anymore, this issue can be reopened should this occur again in the future.
