### ISSUE TITLE
Show more trains within a short timelapse

### ISSUE THREAD

**Issue by gdptfire** [iRail/iRail#341]
I would like to make a suggestion if I may, when searching for a route, when there is a train that leaves the connecting station just minutes after a previous train going to the same destination while having past by the same stations beforehand, the first one  is not displayed.

For example :

Going from Jette to Leuven, the 07:47 train is not displayed when the 07:53 is displayed. Knowing the Belgian railways, it could be useful to know that there is a train leaving 5 minutes earlier leaving you with  more time to connect.

Thanks for your consideration

**Comment by Bertware** [comment]
When searching a route, we 'translate' the request to a format which we can pass on to the NMBS. We then parse the NMBS reply, and reformat it to adhere to our API format. All the results you're seeing are straight from the NMBS. This also means we can't add extra trains, as the Irail API is a "dumb" layer inbetween the NMBS and the user, and doesn't know which trains there are. 

We're currently doing research so we can plan routes on realtime data ourselves, but this is not yet available right now.

**Comment by gdptfire** [comment]
Ok I see.

Thanks so much for the reply and good luck for the future!

Have a nice day

On Feb 14, 2018 14:54, "Bertware" <notifications@github.com> wrote:

When searching a route, we 'translate' the request to a format which we can
pass on to the NMBS. We then parse the NMBS reply, and reformat it to
adhere to our API format. All the results you're seeing are straight from
the NMBS. This also means we can't add extra trains, as the Irail API is a
"dumb" layer inbetween the NMBS and the user, and doesn't know which trains
there are.

We're currently doing research so we can plan routes on realtime data
ourselves, but this is not yet available right now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iRail/iRail/issues/341#issuecomment-365613690>, or mute
the thread
