### ISSUE TITLE
1st Class position

### ISSUE THREAD

**Issue by SteF4444** [iRail/iRail#344]
Hi,

Is it possible to get the position of the first class wagoon for a train ?
Sometimes it's the first wagoon, sometimes the last, and sometimes it's in the middle of the train.
For the 2nd class passengers there is no problems as they can board in approximately all wagon, but for 1st class passengers, it is difficult to know where to stay on the dock as there is only one 1st class wagon. It's important to avoid having to run when the train arrives just because the first class wagon is much farther than where we are.
Can you add this information (as the dock number) in the API ?.

Best regard,
SteF.

**Comment by Bertware** [comment]
Hi Stef,

Unfortunately we do not have this information. If we'd have access to it, I'd be happy to implement this, but the nmbs/sncb does not publish information about which vehicles are used. You could ask the nmbs/sncb if they have plans to release this information, but there are no such plans I'm aware of.

**Comment by SteF4444** [comment]
Hi Bertware,
Thank's for your response.
I think they should have this information anywhere because when I'm waiting for the train, the person which speak over the micro give us sometimes this information.
So they should have it, no !?

Regards,
SteF.
PS: Sorry for my bad english

**Comment by Bertware** [comment]
They definitely have this information. I'd like to publish data on which exact vehicles will be in a train, so you know beforehand which type of train you'll get and how it's configured, but they turned down questions to open it up. (See also #278 )

**Comment by 42wim** [comment]
How can we contact NMBS best to ask again for this information? (please don't tell me to use https://www.belgiantrain.be/nl/support/forms :)
Not only the 1st class position, but also bicycle carriage position and just even what type of train, airco, power outlets would be very useful.

**Comment by Bertware** [comment]
This information will be available through #383 . Closing as this issue is a duplicate now.
