### ISSUE TITLE
Show intermediary stops for routes

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#348]
When planning a journey, e.g. Ghent - Leuven, show for each train in this journey which stops it will pass.
For example:
```
departure: Ghent 12:00
arrival: Leuven 13:00
stops: { Brussels-south 12:30, Brussels Central 12:35, Brussels North 12:40 }
```
This is possible in the latest update of the NMBS application, which means it **_should_** be possible in iRail.

**Comment by DylanVanAssche** [comment]
Wow nice feature!

**Comment by jncn** [comment]
I'd like to see this too 😉

**Comment by jncn** [comment]
Any news on this one? 🙂

**Comment by Bertware** [comment]
I remember seeing it in the code, and found it again:
https://github.com/iRail/iRail/commit/7430dff4d5b81780e37830415c8250e0e2465d35

$rawIntermediateStops holds this data since we rewrote the connections endpoint to get data from another source (see https://github.com/iRail/iRail/issues/319). We should just decide on how to include this in the API response.

**Comment by jncn** [comment]
I'd add a `stops` array (same formatting as in `vehicleinformation`) behind every `departure`. 
E.g.: 
```xml
<connection>
    <departure delay="0" canceled="0" left="0" walking="0">...</departure>
    <stops count="2" vehicleid="IC1234">
        <stop>Same as vehiclestop</stop>
        <stop>Same as vehiclestop</stop>
    </stops>
    <arrival delay="0" canceled="0" arrived="0" walking="0">...</arrival>
    <vias number="1">
        <via id="0">
            <arrival isExtraStop="0" delay="0" canceled="0" arrived="0" walking="0">...</arrival>
            <departure isExtraStop="0" delay="0" canceled="0" left="0" walking="0">...</departure>
            <stops count="2" vehicleid="IC5678">
                <stop>Same as vehiclestop</stop>
                <stop>Same as vehiclestop</stop>
            </stops>
            ...
        </via>
    </vias>
</connection>
```

**Comment by Bertware** [comment]
Seeing this example with the vias makes me remember why I didn't "just implement" it. The response structure, with vias, makes both printing and parsing of those responses needlessly complicated. This way, there are two cases: vias (n > 0), and no vias (n == 0). However, when representing data to the users, we show "legs" of a route, hops between two stations. This way, there aren't any edge cases, you just visualise n legs. In that case, printing and parsing the response is easy, as we would print and parse the intermediate stops per leg. 

I can agree on your proposal to put the first intermediary stops in the connection object, and the intermediary stops for the other legs in each via object. It might be interesting to consider adding a /v2/ api with new representations for easier printing/parsing.

**Comment by jncn** [comment]
Yeah, I agree. In the beginning I also didn't get why the `vias` are constructed like this. However it makes sense that you can just ask for `connection.departure` and `connection.arrival`, even if there are `vias`. 

What's your proposal for this now?

**Comment by Bertware** [comment]
My proposal for now is to follow your proposal, but to start considering a /v2/ version with a new response format (a list of journey legs instead of a list of vias for connections, needlesly complicated json, old, complicated code for e.g. json and xml printing).

**Comment by Bertware** [comment]
@jncn should be available in staging. The first stop is missing the arrival time, the last one misses the departure time. The origin and departure of the leg are included in the list of stops. Would these missing fields be a problem? We could fill them, but I prefer leaving the actual information unchanged.

**Comment by jncn** [comment]
Thanks a lot! I'll do some testing and preparations to add it to Railer 🤩

**Comment by jncn** [comment]
Looks good! If you ask me, you can omit the `departure` and `arrival` stations from `stops`. 
Also can we make loading `stops` optional through a parameter, e.g. `&includeStops=true`, to be sure to be backwards compatible 🙂

**Comment by Bertware** [comment]
Alright, was short on time the past weeks but sitting on a train now, so got some time. I removed the first and last stops so only intermediate stops are shown. I thought about versioning, but in the end it's a lot of hassle (both server-side and client-side, as well as support etc) for a client-side problem. The API has always been backwards compatible by not changing or removing existing fields, but we can add new fields and data if they add value (like in this case). Clients should simply ignore unknown fields to prevent issues.

As far as I'm concerned this is completed and can move to master (and production) after a last round of testing in staging.

@pietercolpaert @DylanVanAssche @ChristopheVersieux @jncn Any last feedback?

**Comment by DylanVanAssche** [comment]
Agreed! Backwards compatibility is needed as you mentioned. Since we won't change existing fields, everything will be fine I guess.

**Comment by jncn** [comment]
Any news on this? I'd love to ship this 🙂 
If it'll be backwards compatible out of the box, the arguments can be omitted. IMO `&newFeatures=true` is a little too vague, because in a few months there'll be other new features.

**Comment by Bertware** [comment]
@jncn were you able to test through Railer? I'd like to deploy it together with #383, which also is being tested in staging at this moment. I was able to test #383 through my app and it seems like we fetch & publish data correctly now (train orientation being incorrect is an NMBS issue which won't stop our release), so I was thinking of deploying in the next week or two. Currently looking at #382 in order to decide if that one will be in the same release as well.

**Comment by jncn** [comment]
Right now, I get an error:
```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/api/output/Xml.php:65) in /var/www/staging.api.irail.be/api/output/Xml.php on line 40 
Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/api/output/Xml.php:65) in /var/www/staging.api.irail.be/api/output/Xml.php on line 41 
Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/api/output/Xml.php:65) in /var/www/staging.api.irail.be/api/output/Xml.php on line 52 
Could not retrieve the right information - please report this problem to iRail@list.iRail.be or try again with other arguments.
```

**Comment by Bertware** [comment]
What query URL are you using?

**Comment by jncn** [comment]
Happens with all, e.g. https://staging.api.irail.be/connections/?lang=nl&to=Leuven&alerts=true&from=Oostende

**Comment by Bertware** [comment]
Looks like it's good we didn't deploy yet, something has changed in the NMBS data, resulting in missing departure/arrival times for intermediate stops. Currently trying to figure out how to fix it.

**Comment by Bertware** [comment]
I've pushed a fix for this issue, but this requires more testing and validation before it can be pushed to master. I'll see if I can find some time in the coming days.

**Comment by jncn** [comment]
Thanks! I'll do testing on my side tomorrow and the coming weekend, probably.

**Comment by Bertware** [comment]
Available on api.irail.be! Create a new issue in case of bugs, problems or enhancements
