### ISSUE TITLE
Probleme with transfert

### ISSUE THREAD

**Issue by PolMrt** [iRail/iRail#350]
Hello 👋
This morning the Api had been down. Since this moment the connections with transfers return a number higher than the real.

For example **Andenne - Bruxelles Luxembourg**

### From iRail

<img width="863" alt="capture d ecran 2018-06-25 a 19 50 01" src="https://user-images.githubusercontent.com/28253868/41866613-fab3ba6a-78b0-11e8-81b9-69d827ca476a.png">

[iRail.be](https://irail.be/route?to=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008811304&from=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008863404&date=250618&time=1949&timeSel=depart)

_Show 2 transfers_

### From SNCB

<img width="931" alt="capture d ecran 2018-06-25 a 20 04 35" src="https://user-images.githubusercontent.com/28253868/41867310-10adc958-78b3-11e8-9381-988da8f73fab.png">

[sncb.be](http://www.belgianrail.be/jp/sncb-horaires/query.exe/fn?S=Andenne&Z=Bruxelles-Luxembourg&date=25/06/2018&time=19:50&start=1&timesel=depart&&REQ0JourneyStopsSID=A=1@O=Andenne@X=5094699@Y=50496760@U=80@L=008863404@B=1@p=1529883783@n=ac.1=GA@&REQ0JourneyStopsZID=A=1@O=Bruxelles-Luxembourg@X=4373675@Y=50838943@U=80@L=008811304@B=1pol@marnette.be=1529883783@n=ac.1=GA@&REQ0JourneyProduct_prod_list=3:0111111111111111&OK#focus)

_Show 1 transfer_

**Comment by Bertware** [comment]
![screenshot_20180625-215404](https://user-images.githubusercontent.com/1094793/41872582-9c793efe-78c2-11e8-87ee-53a1e643a966.png)

**Comment by Bertware** [comment]
Fixed! Please verify and report any strange behaviour on the connections endpoint, NMBS/SNCB changed it a bit and we don't know exactly what changed. When we fixed it this morning we had to change the request a bit and didn't notice the response had changed as well.

Thanks for reporting this @PolMrt, issue contained all the information we needed! :ok_hand:
