### ISSUE TITLE
XX:26 trains from Antwerpen-Centraal to Brussel-Zuid have disappeared

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#356]
A user reports this on Twitter:
> All XX:26 trains from Antwerpen-Centraal to Brussel-Zuid have disappeared from Railer. Only the 6:26 is still present. This has been an issue for some time in the official NMBS app, but only now on Railer as well.

I checked on iRail.be and it seems like this issue is present there as well. The new NMBS website however, does display all XX:26 trains.

Is this related to #346?

**Comment by Bertware** [comment]
Not sure if it's related, but thanks for tagging that issue as I forgot about it. In the other issue we compared to their application (which returned a different result), while in this case we show the same data as the NMBS application, but both are wrong. 

Are these xx:26 trains international trains (Beneluxtrein, Amsterdam-Brussels) or just normal trains?

At this moment we use the same data source as the NMBS application, so if the NMBS application is incorrect, our endpoint will also be incorrect.

**Comment by jncn** [comment]
These are normal trains. The NMBS app is incorrect, but has been for a longer time already. iRail only since recently.

**Comment by Bertware** [comment]
The reason for this is the Thalys train which leaves at :33 and arrives at :08, compared to the regular train leaving at :26 (earlier) and arriving at :10 (later).

Leaving out international trains fixes this issue, however, international trains won't be shown. This is a specific flaw in the NMBS route-planning, as we can't specify to "not use high-speed trains for routes that don't cross the Belgian border"

@pietercolpaert Any suggestions?

**Comment by jncn** [comment]
Sorry, didn't see the edit with the workaround.

Thanks for finding the cause, @Bertware.

Is it possible to exclude international trains from the API results when the `from` and `to` are both in Belgium and `typeoftransport` is not set?

**Comment by jncn** [comment]
Any news on this and my proposal? More and more people are complaining about this. Thanks!

**Comment by Bertware** [comment]
I set up a new staging domain, staging.api.irail.be, where the development branch is hosted. This is an exact clone of api.irail.be, both in server environment, nginx configuration, ... so we can also use this to test new configurations before applying it to the production environment. Please test all endpoints (you can run your app in a debugger and point it to the staging server) to ensure I didn't break anything else. I tested quickly, but might have overlooked stuff as I don't have that much time and had to alter some shared code.

Here you can see how high-speed trains are included or excluded depending on the stations:
https://staging.api.irail.be/connections/?from=Antwerpen-centraal&to=Brussel-zuid&timesel=depart&time=1920&format=xml&date=200918
https://staging.api.irail.be/connections/?from=Antwerpen-centraal&to=Paris-nord&timesel=depart&time=1920&format=xml&date=200918

**Comment by pietercolpaert** [comment]
https://twitter.com/SRoelandt/status/1046466163214110721 → More people noticed. We should get this fix asap into production!

**Comment by jncn** [comment]
Great work @Bertware, thanks!

**Comment by ChristopheVersieux** [comment]
Mhhhh is that possible that this introduced https://github.com/iRail/iRail/issues/363 ?
