### ISSUE TITLE
typeOfTransport=train produce error 404 since 2 days ago fix.

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#363]
Hello
I recently received a lot of bug reports from users.
First one is connection fin Aarschot to Meiser

https://api.irail.be/connections.php?to=Meiser&from=Aarschot&date=021018&time=0724&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true&alerts=true

 {"error":404,"message":"Could not find a station with id 00239948."}

And second one is some search from Eterbeek to Gare du Nord

 {"error":404,"message":"Could not find a station with id 00203117."}

Website seems to be working, maybe some options I shouldn't use?

**Comment by pietercolpaert** [comment]
@Bertware any idea?

**Comment by Bertware** [comment]
Check TYPE_TRANSPORT_ALL in connections.php I can fix it this evening, but you can try reverting that to 1010111. It's the hafas binary vehicle selection

**Comment by pietercolpaert** [comment]
Didn’t get around doing this yet @Bertware -- Would you mind fixing it?

**Comment by ChristopheVersieux** [comment]
Looks good for me, with limited testing...
Thanks!

**Comment by Bertware** [comment]
That link works correctly for me. If there are certain times at which it doesn't work, this means there is a connection we can't parse, independent of the train parameter. Should it happen again, please open a new issue.
