### ISSUE TITLE
HTTP 500 Error on api.irail.be

### ISSUE THREAD

**Issue by digihash** [iRail/iRail#364]
Dear

I'm using the BeTrains app and today it's having trouble with the connection to the server. But I tested on the official NMBS app and the Belgiantrain.be website too and there is also trouble on these platforms.

I received the following:
{"error":500,"message":"Could not get data. Please report this issue at https://github.com/irail/irail/issues/new"}.

Kind Regards
Digihash

**Comment by pietercolpaert** [comment]
I’m afraid this was a general outage. Thanks for notifying us though and sorry for the late response!
