### ISSUE TITLE
'time' param in query not taken into account

### ISSUE THREAD

**Issue by YouriAckx** [iRail/iRail#37]
In `connections` queries, the `time` parameter does not seem to be taken into account:

    youri:Temp $ curl "http://api.irail.be/connections/?to=Ottignies&from=Bruxelles-Nord&typeOfTransport=train&date=191114&time=0730" | xmllint --format - |grep "<time" |head -4
      <time formatted="2014-11-19T07:30:00Z">1416378600</time>
      <time formatted="2014-11-19T08:08:00Z">1416380880</time>
      <time formatted="2014-11-19T07:42:00Z">1416379320</time>
      <time formatted="2014-11-19T08:13:00Z">1416381180</time>

I would expect to see only the 07:30 train, or to receive an error if the query is malformed, rather than all trains on the given `date`.

EDIT: the query returns "some" trains starting from the given `time`. The info is there but the parameter name is misleading (eg `startTime` would be more appropriate).

**Comment by pietercolpaert** [comment]
```
pieter@pieter-werk:~$ curl "http://api.irail.be/connections/?to=Ottignies&from=Bruxelles-Nord&typeOfTransport=train&date=191115&time=0730" | xmllint --format - |grep "<time" |head -n 4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6058  100  6058    0     0  18067      0 --:--:-- --:--:-- --:--:-- 18029
      <time formatted="2015-11-19T07:30:00Z">1447914600</time>
      <time formatted="2015-11-19T08:10:00Z">1447917000</time>
      <time formatted="2015-11-19T07:43:00Z">1447915380</time>
      <time formatted="2015-11-19T08:16:00Z">1447917360</time>
```

Fixed

**Comment by YouriAckx** [comment]
Now I'm confused.

**Comment by pietercolpaert** [comment]
Okay: sorry, misunderstood you earlier. I agree that the parameter name is confusing, yet for backward compatibility reasons we'll have to keep it.

**Comment by YouriAckx** [comment]
... or add `startTime` (or `fromTime` or whatever) as an alias, and deprecate `time`.

+1 for backward compatibility.
