### ISSUE TITLE
Error in /vehicle information

### ISSUE THREAD

**Issue by xivk** [iRail/iRail#372]
On `GET /vehicle/` the and the following query strings:

`?id=BE.NMBS.IC515&date=091118&fast=false&format=json&lang=nl&alerts=true Http status Code:"invalid_response"  Message:"Invalid json" `

`?id=BE.NMBS.IC416&date=091118&fast=false&format=json&lang=nl&alerts=true Http status Code:"invalid_response"  Message:"Invalid json"` 

`?id=BE.NMBS.IC516&date=091118&fast=false&format=json&lang=nl&alerts=true Http status Code:"invalid_response"  Message:"Invalid json"`

We get this response:

`{"error":{"code":"invalid_response","message":"Invalid json"}}`

**Comment by pietercolpaert** [comment]
The response is from the parser you use. The body returned is just invalid JSON.

**Comment by xivk** [comment]
Yep, noticed that while testing, actual json being returned is for example:

`{"version":"1.1","timestamp":"1541776591","vehicle":"BE.NMBS.IC515","vehicleinfo":{"locationX":"3.216726","locationY":"51.197226","name":"BE.NMBS.IC515","shortname":"IC515","@id":"http://irail.be/vehicle/IC515"},"alerts":{"number":"3","alert":[{"id":"0","header":"L 37: Werken aan het spoor tussen Welkenraedt en Pepinster.","description":"Op weekdagen van 2 oktober tot 7 december werkt Infrabel aan het spoor. Sommige IC-treinen Oostende - Brussel - Eupen\/Welkenraedt maken een extra stop in Pepinster. Opgelet! De vertrektijden van deze treinen wijzigen tussen Verviers-Centraal en Eupen (in beide richtingen).De reisplanner houdt al rekening met deze aanpassingen. <a href=\\"http:\/\/www.belgianrail.be\/jp\/download\/brail_him\/1538402042800_NL-09074 Verviers.pdf\\" target=\\"_blank\\">Info NL<\/a>"},{"id":"1","header":"Leuven - Luik-Guillemins: Kabeldiefstal.","description":"Tussen Leuven en Luik-Guillemins:Vertragingen tussen 10 en 30 minuten zijn mogelijk.Onbepaalde duur van de storing.Luister naar de aankondigingen, raadpleeg de infoschermen of plan uw reis via de NMBS-app of nmbs.be voor meer info."},{"id":"2","header":"Gelieve te letten op de spoorwijziging en de aankondigingen in de stations.","description":"Gelieve te letten op de spoorwijziging en de aankondigingen in de stations."}]},"stops":{"number":"12","stop":[{"id":"0","station":"Oostende","stationinfo":{"locationX":"2.925809","locationY":"51.228212","id":"BE.NMBS.008891702","@id":"http://irail.be/stations/NMBS/008891702","standardname":"Oostende","name":"Oostende"},"time":"1541774520","delay":"0","platform":"5","platforminfo":{"name":"5","normal":"1"},"canceled":"1","departureDelay":"0","departureCanceled":"1","scheduledDepartureTime":"1541774520","scheduledArrivalTime":"1541774520","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8891702/20181109/IC515","left":"1","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"1","station":"Brugge","stationinfo":{"locationX":"3.216726","locationY":"51.197226","id":"BE.NMBS.008891009","@id":"http://irail.be/stations/NMBS/008891009","standardname":"Brugge","name":"Brugge"},"time":"1541775480","delay":"240","platform":"1","platforminfo":{"name":"1","normal":"0"},"canceled":"0","departureDelay":"240","departureCanceled":"0","scheduledDepartureTime":"1541775480","scheduledArrivalTime":"1541775360","arrivalDelay":"0","arrivalCanceled":"1","departureConnection":"http://irail.be/connections/8891009/20181109/IC515","left":"1","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"2","station":"Gent-Sint-Pieters","stationinfo":{"locationX":"3.710675","locationY":"51.035896","id":"BE.NMBS.008892007","@id":"http://irail.be/stations/NMBS/008892007","standardname":"Gent-Sint-Pieters","name":"Gent-Sint-Pieters"},"time":"1541776980","delay":"60","platform":"10","platforminfo":{"name":"10","normal":"1"},"canceled":"0","departureDelay":"60","departureCanceled":"0","scheduledDepartureTime":"1541776980","scheduledArrivalTime":"1541776800","arrivalDelay":"120","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8892007/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"3","station":"Brussel-Zuid","stationinfo":{"locationX":"4.336531","locationY":"50.835707","id":"BE.NMBS.008814001","@id":"http://irail.be/stations/NMBS/008814001","name":"Brussel-Zuid","standardname":"Brussel-Zuid/Bruxelles-Midi"},"time":"1541778960","delay":"0","platform":"12","platforminfo":{"name":"12","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541778960","scheduledArrivalTime":"1541778780","arrivalDelay":"60","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8814001/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"4","station":"Brussel-Centraal","stationinfo":{"locationX":"4.356801","locationY":"50.845658","id":"BE.NMBS.008813003","@id":"http://irail.be/stations/NMBS/008813003","name":"Brussel-Centraal","standardname":"Brussel-Centraal/Bruxelles-Central"},"time":"1541779200","delay":"60","platform":"3","platforminfo":{"name":"3","normal":"1"},"canceled":"0","departureDelay":"60","departureCanceled":"0","scheduledDepartureTime":"1541779200","scheduledArrivalTime":"1541779140","arrivalDelay":"60","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8813003/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"5","station":"Brussel-Noord","stationinfo":{"locationX":"4.360846","locationY":"50.859663","id":"BE.NMBS.008812005","@id":"http://irail.be/stations/NMBS/008812005","name":"Brussel-Noord","standardname":"Brussel-Noord/Bruxelles-Nord"},"time":"1541779560","delay":"0","platform":"7","platforminfo":{"name":"7","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541779560","scheduledArrivalTime":"1541779440","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8812005/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/high","name":"high"}},{"id":"6","station":"Leuven","stationinfo":{"locationX":"4.715866","locationY":"50.88228","id":"BE.NMBS.008833001","@id":"http://irail.be/stations/NMBS/008833001","standardname":"Leuven","name":"Leuven"},"time":"1541780820","delay":"0","platform":"3","platforminfo":{"name":"3","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541780820","scheduledArrivalTime":"1541780700","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8833001/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"7","station":"Luik-Guillemins","stationinfo":{"locationX":"5.566695","locationY":"50.62455","id":"BE.NMBS.008841004","@id":"http://irail.be/stations/NMBS/008841004","name":"Luik-Guillemins","standardname":"Liège-Guillemins"},"time":"1541783040","delay":"60","platform":"1","platforminfo":{"name":"1","normal":"1"},"canceled":"0","departureDelay":"60","departureCanceled":"0","scheduledDepartureTime":"1541783040","scheduledArrivalTime":"1541782920","arrivalDelay":"60","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8841004/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"8","station":"Pepinster","stationinfo":{"locationX":"5.80615","locationY":"50.568179","id":"BE.NMBS.008844206","@id":"http://irail.be/stations/NMBS/008844206","standardname":"Pepinster","name":"Pepinster"},"time":"1541783940","delay":"0","platform":"2","platforminfo":{"name":"2","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541783940","scheduledArrivalTime":"1541783880","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8844206/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"9","station":"Verviers-Centraal","stationinfo":{"locationX":"5.854917","locationY":"50.588135","id":"BE.NMBS.008844008","@id":"http://irail.be/stations/NMBS/008844008","name":"Verviers-Centraal","standardname":"Verviers-Central"},"time":"1541784420","delay":"0","platform":"3","platforminfo":{"name":"3","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541784420","scheduledArrivalTime":"1541784360","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8844008/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"10","station":"Welkenraedt","stationinfo":{"locationX":"5.975381","locationY":"50.659707","id":"BE.NMBS.008844503","@id":"http://irail.be/stations/NMBS/008844503","standardname":"Welkenraedt","name":"Welkenraedt"},"time":"1541785200","delay":"0","platform":"5","platforminfo":{"name":"5","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541785200","scheduledArrivalTime":"1541785080","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8844503/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}},{"id":"11","station":"Eupen","stationinfo":{"locationX":"6.03711","locationY":"50.635157","id":"BE.NMBS.008844628","@id":"http://irail.be/stations/NMBS/008844628","standardname":"Eupen","name":"Eupen"},"time":"1541785680","delay":"0","platform":"2","platforminfo":{"name":"2","normal":"1"},"canceled":"0","departureDelay":"0","departureCanceled":"0","scheduledDepartureTime":"1541785680","scheduledArrivalTime":"1541785680","arrivalDelay":"0","arrivalCanceled":"0","departureConnection":"http://irail.be/connections/8844628/20181109/IC515","left":"0","isExtraStop":"0","occupancy":{"@id":"http://api.irail.be/terms/unknown","name":"unknown"}}]}}`

**Comment by xivk** [comment]
The problem is a URL in one of the alerts that is not included correctly. JSON validation fails here:

`alert":[
         {
            "id":"0",
            "header":"L 37: Werken aan het spoor tussen Welkenraedt en Pepinster.",
            "description":"Op weekdagen van 2 oktober tot 7 december werkt Infrabel aan het spoor. Sommige IC-treinen Oostende - Brussel - Eupen\/Welkenraedt maken een extra stop in Pepinster. Opgelet! De vertrektijden van deze treinen wijzigen tussen Verviers-Centraal en Eupen (in beide richtingen).De reisplanner houdt al rekening met deze aanpassingen. <a href=\\"            http:\/\/www.belgianrail.be\/jp\/download\/brail_him\/1538402042800_NL-09074 Verviers.pdf\\" target=\\"_blank\\">Info NL<\/a>"
         }`

**Comment by pietercolpaert** [comment]
I found the culprit: https://github.com/iRail/iRail/development/api/data/NMBS/vehicleinformation.php#L413 → for safety, we started encoding JSON in the formatter instead of before that. We should just remove this if clause and it should be fixed. Hotfixing!

**Comment by AlokSinghKol** [comment]
@pietercolpaert 
Started again getting the issue ,

Input :
?from=BE.NMBS.008883238&to=BE.NMBS.008891116&date=151118&time=1100&timesel=arrival&format=json&lang=nl&fast=false&typeOfTransport=trains&alerts=true&results=6

Error Response:

{"error":{"code":"invalid_response","message":"Message too large"}}

The format should be

**Comment by Bertware** [comment]
@AlokSinghKol /irail/v1/connections is not an endpoint of api.irail.be. Please correct this. Your response message 'message too large' is generated by your JSON parser because you're getting an HTML 404 page instead of an API response. As already stated in the other issue you created, please use api.irail.be and follow the documentation. Correct endpoint is http://api.irail.be/connections/
