### ISSUE TITLE
Error in /irail/v1/connections/

### ISSUE THREAD

**Issue by AlokSinghKol** [iRail/iRail#376]
On  /irail/v1/connections/ the and the following query strings:
?from=BE.NMBS.008883238&to=BE.NMBS.008891116&date=151118&time=1100&timesel=arrival&format=json&lang=nl&fast=false&typeOfTransport=trains&alerts=true&results=6

Error Response:

{"error":{"code":"invalid_response","message":"Message too large"}}

**Comment by Bertware** [comment]
please use api.irail.be (documentation at https://docs.irail.be) instead of irail.be. Api.irail.be is the official API and better maintained and documented

**Comment by pietercolpaert** [comment]
The Error response is not one given by us. When just testing this manually, the response seems to return fine: https://api.irail.be/connections/?from=BE.NMBS.008883238&to=BE.NMBS.008891116&date=151118&time=1100&timesel=arrival&format=json&lang=nl&fast=false&typeOfTransport=trains&alerts=true&results=6

**Comment by AlokSinghKol** [comment]
Using  below API
https://docs.irail.be/#connections

**Comment by AlokSinghKol** [comment]
Same kind of issue reported for vehicle 

pls find the ticket which was resolved.

https://github.com/iRail/iRail/issues/372
