### ISSUE TITLE
Occupancy missing for Vehicle info

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#378]
`occupancy` is not longer included in `vehicle` results, e.g.: http://api.irail.be/vehicle/?id=ic407
This used to work, and is also described in the fancy new docs: https://docs.irail.be/#vehicle

Thanks for fixing!

**Comment by Bertware** [comment]
Most likely there is an internal error when getting the occupancy data, as a fallback the field is left out. Don't have time at the moment, @pietercolpaert @brechtvdv one of you got time for this?

**Comment by jncn** [comment]
This seems to be fixed!
