### ISSUE TITLE
Error 502 for past train

### ISSUE THREAD

**Issue by YouriAckx** [iRail/iRail#38]
youri:Temp $ curl "http://api.irail.be/connections/?from=Ottignies&to=Louvain-la-Neuve&typeOfTransport=train&date=101114" | xmllint --format -
    <?xml version="1.0"?>
    <error code="502">Could not get data. Please report this problem to iRail@list.iRail.be.</error>

**Comment by pietercolpaert** [comment]
If it's too long ago, the NMBS will return an error. We cannot do a lot about it at this time I'm afraid. On the other hand, I agree that we should provide better errors.
