### ISSUE TITLE
Api result not the same that the SNCB app

### ISSUE THREAD

**Issue by algra4** [iRail/iRail#380]
Hi, 

**Reproduce :**

When I make this request around 17:45:
https://api.irail.be/connections/?from=Bruxelles-Central&to=Nivelles&date=160419&time=1630&timesel=departure&format=json&lang=fr&typeOfTransport=trains

I have a problem with the train at 16:49 and 17:05 for example leaving from Brussels Central

API result : 
![image](https://user-images.githubusercontent.com/6781230/56228704-9eea2d80-6078-11e9-9a19-026bce10678f.png)

So the SNCB application, the train arrived
![image](https://user-images.githubusercontent.com/6781230/56228800-d062f900-6078-11e9-8ec8-c80a8b97e1aa.png)

**Comment by Bertware** [comment]
Seems like there are 2 new fields in the NMBS response, which I now mapped to the left and arrived fields for the routeplanner. Will merge to development, where you can verify this through staging.api.irail.be

**Comment by Bertware** [comment]
Please verify through our staging environment, which can be accessed by using staging.api.irail.be instead of api.irail.be
