### ISSUE TITLE
Delay information seems to be missing

### ISSUE THREAD

**Issue by romintomasetti** [iRail/iRail#382]
Hi there !

I encountered some cases showing that staging.api.irail.be was not identifying the delays.

Example: Train 491 (type L) on 28th Aug. 2019 (https://staging.api.irail.be/vehicle/?id=BE.NMBS.S491&date=280819)

![Delays_S491_28082019](https://user-images.githubusercontent.com/22600251/64083630-de14d480-cd22-11e9-9f81-bb8e6667e552.png)

(picture from http://www.belgianrail.be/fr/service-clientele/attestation-de-retard.aspx)

However, the request to irail ends up in no delay at all. Example with the destination ANVERS-CENTRAL:
`<stop id="11" delay="0" canceled="0" left="0" isExtraStop="0">
<station locationX="4.421101" locationY="51.2172" id="BE.NMBS.008821006" URI="http://irail.be/stations/NMBS/008821006" standardname="Antwerpen-Centraal">Antwerp-Central</station>
<time formatted="2019-08-28T20:40:00">1567017600</time>
<platform normal="1">23</platform>
<departureDelay>0</departureDelay>
<departureCanceled>0</departureCanceled>
<scheduledDepartureTime formatted="2019-08-28T20:40:00">1567017600</scheduledDepartureTime>
<scheduledArrivalTime formatted="2019-08-28T20:40:00">1567017600</scheduledArrivalTime>
<arrivalDelay>0</arrivalDelay>
<arrivalCanceled>0</arrivalCanceled>
<departureConnection>http://irail.be/connections/8821006/20190828/S491</departureConnection>
<occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
</stop>`

Is this a bug or do I misuse your tool?

**Comment by Bertware** [comment]
This seems to be a bug in VehicleInformation.php. Probably a change in the NMBS HTML structure. We have a backup branch which gets data from another source (internal API), might be time to switch over.

**Comment by Bertware** [comment]
Fix this by fixing #332
