### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#386]
As a developer, I want to be able to run iRail in a local development container.

As a system administrator, I want to be able to run iRail on my own server in Docker, and place the Docker container behind an Nginx instance.

Add a dockerfile to run iRail in a docker container with PHP-FPM 7.3+ and Nginx. Occupancy (Spitsgids) support is optional, and when it is implemented, it should be implemented by running an additional MongoDb container.

- [x] Create a dockerfile for the iRail api.
- [x] Ensure that the iRail api /storage folder is stored on disk, even if the container is stopped
- [x] Use docker-compose to specify ports and directories, in order to make the usage as easy as possible.
- [x] Update readme.md to add instructions how to run the docker container.

**Comment by arc92** [comment]
Can i work on this issue??

**Comment by Bertware** [comment]
Sure, anyone can work on this. Create a fork of the project, make commits to your local repository, then create a pull request back to our development branch.

**Comment by arc92** [comment]
Hi @Bertware  because of 2 days pass and,I haven't anything from you.
I want to know the docker files is ok?

**Comment by Bertware** [comment]
Hi,

I couldn't review during the week due to a lack of time. While it's a good thing to remember members that a review is pending, I'd recommend giving volunteers at least a week time to review it before reminding them ;) Looked good, merged into development! Thanks a lot for contributing!

Regards,
Bert
