### ISSUE TITLE
When querying too far in the past, the error message is too generic

### ISSUE THREAD

**Issue by DylanDec** [iRail/iRail#392]
![image](https://user-images.githubusercontent.com/14364739/70631744-f0f64980-1c2d-11ea-841e-dfba7d03344f.png)

**Comment by Bertware** [comment]
Hi Dylan,

Your query contains a number of errors:
- You should specify either the id or the station name. While this won't cause errors on the server side, it can cause unexpected behaviour.
- Your query has the date set to 30/09/2017. This is what's causing the error. Generally speaking, you cannot search more than one day in the past. 

This error message should have been more specific. Debugging is needed to pinpoint the exact cause why we aren't showing the correct "Date is too far in the past" error message.
Text url (for future debugging): http://api.irail.be/liveboard/?id=BE.NMBS.008892007&date=300917&time=1230

Thanks for your bug report!

Regards,
Bert

**Comment by DylanDec** [comment]
Thank you, I had copied the URL without looking at it.

Thanks for the support!

**Comment by Bertware** [comment]
This error message needs to be clearer

**Comment by Bertware** [comment]
This (the unclear error) is still an issue that needs to be resolved, therefore it shouldn't be closed.
