### ISSUE TITLE
typeOfTransport=train includes MIVB in results, causing an error 500

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#397]
URL to query:

https://api.irail.be/connections.php?to=Brussels-schuman&from=Tournai&date=301219&time=1249&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true&alerts=true

Or in French:

https://api.irail.be/connections.php?to=Bruxelles-schuman&from=Tournai&date=301219&time=1249&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true&alerts=true

Will return 

error: 404,
message: "Could not find a station with id 00239731."

I don't see where this ID is coming from...

**Comment by Bertware** [comment]
For some reason, MIVB is included in the NMBS response:

"lid":"A=1@O=CENTRAAL STATION/GARE CENTRALE [STIB/MIVB]@X=4358770@Y=50846350@U=80@L=239731@","type":"S","name":"CENTRAAL STATION/GARE CENTRALE [STIB/MIVB]"

Works without the typeOfTransport field, so there is something wrong in the transport filter.

**Comment by ChristopheVersieux** [comment]
OK, I will push the update in the Play Store removing completely typeOfTransport , as the results users will get buses during the fix time, but I guess that most of the time, only trains will be returned.

**Comment by Bertware** [comment]
Fixed, this value was handled incorrectly after refactorings
