### ISSUE TITLE
hafasId is included with stations, this field should be private

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#398]
Apparently in some cases, Railer crashes due to the addition of `<hafasId>` to `<station>`. Is it possible to revert this for now? I'll add support to it in the next version. Thanks a lot!

**Comment by Bertware** [comment]
This field shouldn't be there in the first place, but as a temporary workaround I moved it to the attributes, like all other station information:
https://github.com/iRail/iRail/commit/f572ba164e98cbf028ae58975b4a5464b35ae2cc
