### ISSUE TITLE
Delay times are unavailable in the past

### ISSUE THREAD

**Issue by titivermeesch** [iRail/iRail#404]
I've been trying to fetch the delay for some trains, but the problem is that it seems like the delay is only available for trains that are on the day I'm looking at.

I've tried checking a train connection that I know there will be a delay of a few minutes but it's always 0. Is this because the delay is not saved for some reasons or am I using it wrong?

**Comment by Bertware** [comment]
The delays are fetched from the NMBS on the moment you make a request to iRail. The NMBS doesn't keep the delays in their app, and as a result the delays also disappear from iRail. What would you like to do with historical data?

**Comment by titivermeesch** [comment]
So I will have to store the data on my own then? Fetching the delays every day and basing my app on that?
I'm building an AI that will analyse the data and predict your journey, kind of.

But if I understand well I'll have to store those values by fetching them every day

**Comment by Bertware** [comment]
If you're working with analytics, (and you don't need platform informations), our experimental Linked Connections API is a perfect fit: https://graph.irail.be/sncb/connections

This API is a chronological list of every train departure. Every train journey is a series of departures, all these departures are sorted by their departure time and put in the list. This API keeps historical data (the last known delay) and allows you to look at snapshots (what was the delay at 14:00 for this departure? and at 13:30?) to see how delays have evolved. This way you don't have to scrape the traditional API, and you get better/more data in your use case. Departure platform isn't present in this new API at this moment, but I hope that's not too big of an issue for this case.

More information about how Linked Connections works can be found at https://linkedconnections.org/

**Comment by titivermeesch** [comment]
This is indeed a better fit.

I've seen that for a longer period of time the delay isn't show either. But at least I have the data for a few months.
This query will for example not return any delay data at all : https://graph.irail.be/sncb/connections?departureTime=2019-10-16T15:32:00.000Z

**Comment by Bertware** [comment]
That link works for me, you may need to retry (wait a second in between attempts). 

The repo for the LinkedConnections API is https://github.com/linkedconnections/linked-connections-server. The readme also contains a bit more information about historical data (as in, what did the data say 2 minutes ago and what does it say now about the same departure)

**Comment by Bertware** [comment]
ping @julianrojas87 @pietercolpaert don't know if one of you has something more to add about status/stability

**Comment by titivermeesch** [comment]
It works for me too now, I'll have a in-depth look at the LinkedConnections API, it seems pretty interesting and I think I have the data I need

**Comment by hermandebeukelaer** [comment]
> The delays are fetched from the NMBS on the moment you make a request to iRail. The NMBS doesn't keep the delays in their app, and as a result the delays also disappear from iRail. What would you like to do with historical data?

@Bertware NMBS now seems to store delays at least for some time in the past, but the iRail api still does not (at least I have not found any connections in the past mentioning a delay). One example I came across today:

https://api.irail.be/connections/?from=Merelbeke&to=Brugge&date=280622&time=1300&timesel=departure&format=json

Response:

```json
{
   "version":"1.1",
   "timestamp":"1656484939",
   "connection":[
      {
         "id":"0",
         "departure":{
            "delay":"0",
            "station":"Merelbeke",
            "stationinfo":{
               "locationX":"3.768889",
               "locationY":"51.017531",
               "id":"BE.NMBS.008893013",
               "name":"Merelbeke",
               "@id":"http:\/\/irail.be\/stations\/NMBS\/008893013",
               "standardname":"Merelbeke"
            },
            "time":"1656414780",
            "vehicle":"BE.NMBS.IC2233",
            "vehicleinfo":{
               "name":"BE.NMBS.IC2233",
               "shortname":"IC2233",
               "number":"2233",
               "type":"IC",
               "@id":"http:\/\/irail.be\/vehicle\/IC2233"
            },
            "platform":"1",
            "platforminfo":{
               "name":"1",
               "normal":"1"
            },
            "canceled":"0",
            "departureConnection":"http:\/\/irail.be\/connections\/8893013\/20220628\/IC2233",
            "direction":{
               "name":"Gent-Sint-Pieters"
            },
            "left":"0",
            "walking":"0"
         },
         "arrival":{
            "delay":"0",
            "station":"Brugge",
            "stationinfo":{
               "locationX":"3.216726",
               "locationY":"51.197226",
               "id":"BE.NMBS.008891009",
               "name":"Brugge",
               "@id":"http:\/\/irail.be\/stations\/NMBS\/008891009",
               "standardname":"Brugge"
            },
            "time":"1656417060",
            "vehicle":"BE.NMBS.IC1534",
            "vehicleinfo":{
               "name":"BE.NMBS.IC1534",
               "shortname":"IC1534",
               "number":"1534",
               "type":"IC",
               "@id":"http:\/\/irail.be\/vehicle\/IC1534"
            },
            "platform":"6",
            "platforminfo":{
               "name":"6",
               "normal":"1"
            },
            "canceled":"0",
            "direction":{
               "name":"Blankenberge"
            },
            "arrived":"0",
            "walking":"0"
         },
         "vias":{
            "number":"1",
            "via":[
               {
                  "id":"0",
                  "arrival":{
                     "time":"1656415200",
                     "platform":"9",
                     "platforminfo":{
                        "name":"9",
                        "normal":"1"
                     },
                     "isExtraStop":"0",
                     "canceled":"0",
                     "delay":"0",
                     "arrived":"0",
                     "walking":"0",
                     "direction":{
                        "name":"Gent-Sint-Pieters"
                     },
                     "vehicle":"BE.NMBS.IC2233",
                     "vehicleinfo":{
                        "name":"BE.NMBS.IC2233",
                        "shortname":"IC2233",
                        "number":"2233",
                        "type":"IC",
                        "@id":"http:\/\/irail.be\/vehicle\/IC2233"
                     },
                     "departureConnection":"http:\/\/irail.be\/connections\/8892007\/20220628\/IC2233"
                  },
                  "departure":{
                     "time":"1656415500",
                     "platform":"12",
                     "platforminfo":{
                        "name":"12",
                        "normal":"1"
                     },
                     "isExtraStop":"0",
                     "canceled":"0",
                     "delay":"0",
                     "left":"0",
                     "walking":"0",
                     "direction":{
                        "name":"Blankenberge"
                     },
                     "vehicle":"BE.NMBS.IC1534",
                     "vehicleinfo":{
                        "name":"BE.NMBS.IC1534",
                        "shortname":"IC1534",
                        "number":"1534",
                        "type":"IC",
                        "@id":"http:\/\/irail.be\/vehicle\/IC1534"
                     },
                     "stops":{
                        "number":"1",
                        "stop":[
                           {
                              "id":"0",
                              "station":"Aalter",
                              "stationinfo":{
                                 "locationX":"3.447848",
                                 "locationY":"51.092295",
                                 "id":"BE.NMBS.008891140",
                                 "name":"Aalter",
                                 "@id":"http:\/\/irail.be\/stations\/NMBS\/008891140",
                                 "standardname":"Aalter"
                              },
                              "scheduledArrivalTime":"1656416160",
                              "arrivalCanceled":"0",
                              "arrived":"0",
                              "scheduledDepartureTime":"1656416220",
                              "arrivalDelay":"0",
                              "departureDelay":"0",
                              "departureCanceled":"0",
                              "left":"0",
                              "isExtraStop":"0",
                              "departureConnection":"http:\/\/irail.be\/connections\/8891140\/20220628\/IC1534"
                           }
                        ]
                     },
                     "departureConnection":"http:\/\/irail.be\/connections\/8892007\/20220628\/IC1534"
                  },
                  "timeBetween":"300",
                  "station":"Ghent-Sint-Pieters",
                  "stationinfo":{
                     "locationX":"3.710675",
                     "locationY":"51.035896",
                     "id":"BE.NMBS.008892007",
                     "name":"Ghent-Sint-Pieters",
                     "@id":"http:\/\/irail.be\/stations\/NMBS\/008892007",
                     "standardname":"Gent-Sint-Pieters"
                  },
                  "vehicle":"BE.NMBS.IC2233",
                  "vehicleinfo":{
                     "name":"BE.NMBS.IC2233",
                     "shortname":"IC2233",
                     "number":"2233",
                     "type":"IC",
                     "@id":"http:\/\/irail.be\/vehicle\/IC2233"
                  },
                  "direction":{
                     "name":"Gent-Sint-Pieters"
                  }
               }
            ]
         },
         "duration":"2280",
         "remarks":{
            "number":"0",
            "remark":[
               
            ]
         },
         "alerts":{
            "number":"0",
            "alert":[
               
            ]
         }
      },
...
```

So the first connection given from Merelbeke to Brugge on 28/6 at 13h is the 13:13 train that actually had a departure delay of 12 minutes. This is still shown today (29/6) on both the mobile app (iOS) and NMBS website:

![Schermafbeelding 2022-06-29 om 08 43 27](https://user-images.githubusercontent.com/71495023/176371030-3f483528-b0c0-4a1f-a965-df59e3e2a3d6.png)
![Screenshot 2022-06-29 084424](https://user-images.githubusercontent.com/71495023/176370964-3ca4543c-f1aa-4e73-9181-ec14c1f1f9ff.png)

Is there any particular reason why iRail does not show this delay although NMBS apps do? Don't you get your data from the same source?

**Comment by Muspah** [comment]
The mobile API goes through an additional NMBS layer (Azure hosted), no direct HAFAS calls anymore.

**Comment by Muspah** [comment]
The same as the HAFAS instance that iRail uses. Sniff network traffic and it's "available" ;)

**Comment by hermandebeukelaer** [comment]
And has anyone ever done the sniffing of the mobile API for me? 😄

**Comment by pietercolpaert** [comment]
We also have an experimental interface containing an archive of the delays over here: https://graph.irail.be/sncb/connections/feed

**Comment by Muspah** [comment]
> And has anyone ever done the sniffing of the mobile API for me? 😄 

Yeah but without logging. Didn't have the time yet to document it. It's an easy job with mitmproxy and a few minutes time.

**Comment by Bertware** [comment]
> @Bertware NMBS now seems to store delays at least for some time in the past, but the iRail api still does not (at least I have not found any connections in the past mentioning a delay). One example I came across today:
> 
> https://api.irail.be/connections/?from=Merelbeke&to=Brugge&date=280622&time=1300&timesel=departure&format=json
> 
> So the first connection given from Merelbeke to Brugge on 28/6 at 13h is the 13:13 train that actually had a departure delay of 12 minutes. This is still shown today (29/6) on both the mobile app (iOS) and NMBS website:
> 
> Is there any particular reason why iRail does not show this delay although NMBS apps do? Don't you get your data from the same source?

iRail is based on the "old" NMBS app, while these screenshots are from the new NMBS app/website.

> The same as the HAFAS instance that iRail uses. Sniff network traffic and it's "available" ;)

Are they the same? Might be different APIs/product versions in parallel, given that some data seems to differ. If they are the same version, then the NMBS is enriching it themselves with some extra data.

**Comment by Muspah** [comment]
It seems like they're wrapping around HAFAS data, based on the naming of fields.

**Comment by Bertware** [comment]
> And has anyone ever done the sniffing of the mobile API for me? 😄

A while ago I looked at the new API, uploaded the requests made here: https://gist.github.com/Bertware/2aa121c84bc5ffda0dd4d4c712c6b4f5

**Comment by hermandebeukelaer** [comment]
@Bertware I tried some of the requests you listed for the new API but always get the same error respons:
```json
{
    "reasons": [
        {
            "language": "en",
            "message": "error : 1003 : _DetermineSecurityPolicy : Incoming Request cannot be mapped to an Generic Security Policy"
        }
    ],
    "details": {
        "msgId": "Id-9c91bc629625789a296eefdb"
    }
}
```
Did you actually manage to get valid data with these calls?

**Comment by Muspah** [comment]
Did you include the necessary headers (API key et cetera)?

**Comment by hermandebeukelaer** [comment]
Yes I did. Without the headers I got another error (saying that no valid API key was provided).

**Comment by Bertware** [comment]
HTTPS is required. They were from September 2021, I added some new ones as well as captured responses.

**Comment by hermandebeukelaer** [comment]
@Bertware Brilliant, worked like a charm! I am getting the data I need now from the mobile API. Thanks a lot.

**Comment by hermandebeukelaer** [comment]
If anyone's interested: I noticed the mobile API's response includes real-time timings (delays) up to three days in the past. I'd hoped for more, but three days I can work with.

**Comment by Muspah** [comment]
If you really need to be able to look far back, it might be an option to subscribe to GTFS-RT. If you don't want to wait on NMBS to give you access, give me a ping.

**Comment by hermandebeukelaer** [comment]
@Muspah I don't have any experience with GTFS but it might be an option. Do you think the NMBS realtime GTFS feed will contain delay data further in the past? Is there any way to get some examples of this data without having to apply for access through the NMBS site?

**Comment by Muspah** [comment]
GTFS-RT is RT, real-time. But it gives you the possibility to log as long as needed.

Examples (protobuf converted to JSON) of NMBS data: https://logs.ovdata.nl/csv/Vlaanderen/NMBS/

**Comment by hermandebeukelaer** [comment]
@Muspah I would like to explore the nmbs GTFS-RT data a bit more. What's the fastest way to get access?

**Comment by Muspah** [comment]
> @Muspah I would like to explore the nmbs GTFS-RT data a bit more. What's the fastest way to get access?

The official place to be is: https://www.belgiantrain.be/nl/3rd-party-services/mobility-service-providers/public-data

The "secret" link that NMBS will share with you after signing isn't unique tho, lol.

**Comment by pietercolpaert** [comment]
> The "secret" link that NMBS will share with you after signing isn't unique tho, lol.

There's a good reason to keep the URL the same though: HTTP caching becomes quite efficient

**Comment by Muspah** [comment]
> > The "secret" link that NMBS will share with you after signing isn't unique tho, lol.
> 
> 
> 
> There's a good reason to keep the URL the same though: HTTP caching becomes quite efficient

Yeah I can understand, but just find it funny how much paperwork they make you fill in to receive a "secret" static URL. I'm too much used to the Dutch setup I guess haha.

**Comment by pietercolpaert** [comment]
Agreed that there is way too much paperwork for what should have been an
entirely public dataset

**Comment by hermandebeukelaer** [comment]
Thanks everyone, I submitted the application form.

**Comment by hermandebeukelaer** [comment]
Does anyone have a clue how long it could take to get approval by NMBS? 😄 It has been about a week now since I submitted, I hope I won't have to wait many weeks or months to get access 😞

**Comment by Muspah** [comment]
I've waited for over a month, send the email again and got a response with apologies and the link with datasources. Might take longer now in the holiday season.

**Comment by DylanVanAssche** [comment]
It's GTFS-RT data, you need protobuf etc. to decode it.
