### ISSUE TITLE
Clean up composition XML

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#405]
@Bertware would it be possible to cleanup the composition XML a bit? 
Currently there are two `composition` levels which can be eliminated, in my opinion. This would make my parser a bit cleaner 😉 

I've barred the ones I'd get rid of:
<img width="613" alt="Screenshot 2020-02-22 at 00 35 12" src="https://user-images.githubusercontent.com/995815/75080274-d7199280-550b-11ea-81ab-fa7fd424f963.png">

Thanks a lot! Also for the great work on this.

**Comment by Bertware** [comment]
Whoops, thought I already answered this one. Sorry for the late reply.

Unfortunately this nesting and naming is a result of the XML printer, which is manually implemented and 9 years old. Changing this behaviour would affect all endpoints. The only way around this would be a complete rewrite, and would break all backward compatibility. While maintaining a /v1 and /v2 would be doable using a common data layer with different serializations, it's just a lot of work without much benefit for end users (compared to putting work into more/better data).

**Comment by jncn** [comment]
Clear! No problem 🙂
