### ISSUE TITLE
get train type (Sx,IC,L) and train number

### ISSUE THREAD

**Issue by tom-2015** [iRail/iRail#406]
In the API data I see train type and train number as one string like:

`<vehicle URI="http://irail.be/vehicle/S521880">BE.NMBS.S521880</vehicle>`

No problem for IC and L trains but not clear for S trains. This case the train type is S52 and train number is 1880. Suggested solution:

`<vehicle URI="http://irail.be/vehicle/S521880" type="S52" number="1880" operator="BE.NMBS">BE.NMBS.S521880</vehicle>`

I need this for my screen saver project [https://github.com/tom-2015/RailtimeScreenSaver](https://github.com/tom-2015/RailtimeScreenSaver). Right now I'm parsing NMBS html but I'm afraid one day they will change or put it down.

**Comment by Bertware** [comment]
I agree that it'd be nice. The code is already present, so we only have to move it to a shared class and use it in the other endpoints.

https://github.com/iRail/iRail/blob/master/api/data/NMBS/Composition.php#L383
