### ISSUE TITLE
<a> tags missing from disturbances end point

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#407]
When requesting disturbances via `/disturbances`, the `<a>` tags are missing from `<description>`. This renders the link as an orphan, just a word. They are however present in other end points through `<alert>`.

As-is http://api.irail.be/disturbances/
```XML
<description>
<![CDATA[
Sinds 4 mei rijden bijna alle treinen opnieuw op het volledige net, 
volgens een licht aangepaste dienstregeling. Plan uw reis via de 
NMBS-app of nmbs.be voor meer info. Details
]]>
</description>
```

Should be like https://api.irail.be/vehicle/?lang=nl&id=BE.NMBS.IC1712&alerts=true
```XML
<description>
<![CDATA[
Sinds 4 mei rijden bijna alle treinen opnieuw op het volledige net, 
volgens een licht aangepaste dienstregeling. Plan uw reis via de 
NMBS-app of nmbs.be voor meer info. 
<a href="https://www.belgiantrain.be/nl/news/coronavirus/maximalisatie-4mei" target="_blank">Details</a>
]]>
</description>
```

**Comment by Bertware** [comment]
Alright, I've added a richtext data field which includes a tags, a list of description links for easy access to the links (in case users want to present them in another way than as a link in the text), and the description remains plaintext with links removed. The reason for this is that the plaintext was an active choice as clients might not be able to show the HTML the nmbs includes (we strip away their "layout" for the same reason, it'd make it hard to use the content on mobile devices). Does this sound like a good solution to you @jncn ? Sorry it took a while!

**Comment by jncn** [comment]
Real nice! Thanks. Will implement it in a next version. Will this be equal for `/disturbances` and all other endpoints?

**Comment by Bertware** [comment]
Right now it's only for disturbances, but it should probably be applied to the other endpoints as well
