### ISSUE TITLE
Misformatted XML for the disturbances endpoint

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#408]
When the language is set to NL, the XML is misformatted, resulting in errors.
https://api.irail.be/disturbances/?lang=nl

<img width="870" alt="Screenshot 2020-06-03 at 21 26 12" src="https://user-images.githubusercontent.com/995815/83680138-dbf8e280-a5e0-11ea-8a04-8f84d02880a5.png">

**Comment by Bertware** [comment]
The problem lies in the use of & in the message title:

<title>Saint-Ghislain - Bergen & Doornik - Lille Flandres (FR)</title>

should be

<title>Saint-Ghislain - Bergen &amp; Doornik - Lille Flandres (FR)</title>

**Comment by Bertware** [comment]
Fixed in staging. Please verify that all other endpoints are still working as the change affects all XML output. 

https://staging.api.irail.be/disturbances/?lang=nl

**Comment by jncn** [comment]
Works on staging, thanks @Bertware !

**Comment by Bertware** [comment]
Did you have time to check other endpoints as well? I wouldn't expect issues but want to be sure before moving to production.

**Comment by jncn** [comment]
I've only checked `conntections`, `liveboard` and `vehicle`, as these are the only ones being used in Railer.

**Comment by Bertware** [comment]
Those are the ones I was after. Merging it to prod!

**Comment by jncn** [comment]
Thanks for the swift action!
