### ISSUE TITLE
Always return the requested format

### ISSUE THREAD

**Issue by cimm** [iRail/iRail#41]
It would be nice if the API would **always** returns XML or JSON (depending on the format in the query). Right now it might return XML or JSON when the query is successful but might return plain text when the station isn't found. Other errors might return the correct format.

Take http://api.irail.be/connections/?to=heaven&from=hell&format=xml for example, which returns plain text. This means the client implementation needs to call a different parser if the XML or JSON parser can't parse the result.

It does do the right thing when you send a broken query like http://api.irail.be/connections/?format=xml though.

**Comment by pietercolpaert** [comment]
Good point! Thanks for the issue!

**Comment by pietercolpaert** [comment]
Fixed
