### ISSUE TITLE
/stations endpoint retrieves no data

### ISSUE THREAD

**Issue by Itemshopp** [iRail/iRail#418]
Trying to call the /stations endpoint results in version and timestamp element retrieving only.
No stations are returned.

Documentation needs to be updated or endpoint should be repaired ?

**Comment by Bertware** [comment]
This is a bug and should be fixed, will investigate later today

**Comment by Bertware** [comment]
Apparently I forgot to map this type of Request class to its data class in the recent large update. Fixed and tests have been added to prevent this from happening again.

**Comment by Bertware** [comment]
Fixed! http://api.irail.be/stations/
