### ISSUE TITLE
Disturbances XML root element changed name

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#423]
The root element of https://api.irail.be/disturbances/ is now called `disturbance`, where it would be `disturbances` in the past. This could cause some issues, since its nodes are also called `disturbance`. Thanks in advance for reverting it back to  `disturbances` 🙂

I guess it's located here: https://github.com/iRail/iRail/blob/5ceb65824a034e0aeb12882b70e472b8f9e42467/src/api/APICall.php#L71

**Comment by Bertware** [comment]
Fixed, leaving this issue open until I added a test for it. Thanks for the code link, they help for these quick fixes in my lunch break.

**Comment by Bertware** [comment]
See https://github.com/iRail/iRail/commit/b328dd961295211b2adaa8465b3c0ffd4459a97c

**Comment by jncn** [comment]
You're faster than your own shadow, Bert! Thanks ✌🏼
