### ISSUE TITLE
/connections end-point doesn't show alerts any more

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#432]
Before when `&alerts=true`, alert objects could be attached to a `connection` on `/connections`. 
They are still present on the `/vehicle` end-point though.

e.g. https://staging.api.irail.be/connections/?lang=en&to=brussel-zuid&alerts=true&from=leuven

**Comment by jncn** [comment]
Feel free to let me know if there's something I can do to help with this one, would be nice to get it back 😇

**Comment by Bertware** [comment]
You know how to bump these issues at just the right times! There was a minor change in the NMBS dataformat, fixed the code, fixed some other bugs as well. Please test on staging, test routes which include walking parts as well. 

S32 400 trains should now be parsed correctly as well (were parsed as S3 2400 previously)

**Comment by jncn** [comment]
Alerts work beautifully, very nice. I'll remove the alerts parameter from my requests.

I get errors for this connection with `WALK` leg:
https://staging.api.irail.be/connections/?lang=nl&to=BE.NMBS.008811163&alerts=true&from=BE.NMBS.008833001

```
Warning: key_exists() expects parameter 2 to be array, null given in /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php on line 840

Warning: key_exists() expects parameter 2 to be array, null given in /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php on line 845

Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php:840) in /var/www/staging.api.irail.be/src/api/output/Printer.php on line 273

Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php:840) in /var/www/staging.api.irail.be/src/api/output/Printer.php on line 274

Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php:840) in /var/www/staging.api.irail.be/src/api/output/Xml.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /var/www/staging.api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php:840) in /var/www/staging.api.irail.be/src/api/output/Xml.php on line 43
```

**Comment by Bertware** [comment]
@jncn you can keep the parameters (it's easier leaving them in when they do nothing than adding them again later), but you should not "remove them with the expectation that alerts wont be sent" right now, in case it's an option somewhere in the settings. This can later be fixed decently with a proper decision to keep it or by a decision to remove the parameter.

I'll fix the bug, expected something would show up but couldn't find a walking transfer yesterday

**Comment by Bertware** [comment]
Fixed it, everything should work nicely now

**Comment by Bertware** [comment]
@jncn let me know when you have finished testing!

**Comment by jncn** [comment]
Oh sorry, somehow missed that previous message! All good, ready when you are 😉
