### ISSUE TITLE
Connection endpoint throws warning on Invalid argument supplied for foreach() in /var/www/api.irail.be/src/api/data/NMBS/ConnectionsDatasource.php on line 799

### ISSUE THREAD

**Issue by Desaka** [iRail/iRail#434]
Hello,
I sometimes (like once a week) receive errors in the response of connection endpoint
![image](https://user-images.githubusercontent.com/11273103/109053113-a7800600-76dc-11eb-831b-bbbc766668af.png)
https://api.irail.be/connections/?from=BE.NMBS.008864436&to=BE.NMBS.008843307&timesel=departure&typeOfTransport=nointernationaltrains&time=1408&date=240221&format=json&lang=fr

**Comment by Bertware** [comment]
Weird, the line is
` foreach ($trainRide['jny']['stopL'] as $rawIntermediateStop) {`
but the list of stops should always be set. Will investigate.

**Comment by Bertware** [comment]
There seems to be a bug at the NMBS side, they show a train leaving and arriving at the same time:

![image](https://user-images.githubusercontent.com/1094793/109071651-495f1d00-76f4-11eb-9252-2a1fd725e15b.png)
