### ISSUE TITLE
Empty `vias` tag

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#436]
In `/connections` every `connection` now shows the `vias` tag, even when there are none. This causes my app to crash (my bad!). Is it possible to (temporarily?) reverse this change until Apple approves my update?

Now:
```
</arrival>
<vias number="0"/>
<duration>1140</duration>
```

Desired:
```
</arrival>
<duration>1140</duration>
```

@Bertware, I guess it has something to do with this change: https://github.com/iRail/iRail/commit/e5369873cd734b235173bd1e3de69857deeb4890

**Comment by Bertware** [comment]
Alright, was testing with my girlfriends iPhone and couldn't reproduce, the vias tag explains it, it's two bugs introduced by fixing that one :facepalm: Empty vias should not be included, will fix.

**Comment by Bertware** [comment]
Fixed it in https://github.com/iRail/iRail/commit/c94111e7838d53216b76821eea6db6320f6c4e89.
