### ISSUE TITLE
No response from NMBS/SNCB

### ISSUE THREAD

**Issue by Desaka** [iRail/iRail#439]
{"error":504,"message":"Could not get data: No response from NMBS/SNCB. Please report this issue at https://github.com/irail/irail/issues/new"}
~21h54
Exemple : https://api.irail.be/connections/?from=BE.NMBS.008863008&to=BE.NMBS.008814001&timesel=departure&typeOfTransport=nointernationaltrains&time=1834&date=120321&format=json&lang=fr

**Comment by Bertware** [comment]
This was a server issue which was resolved by restarting the server
