### ISSUE TITLE
Alerts only in dutch

### ISSUE THREAD

**Issue by betasa** [iRail/iRail#443]
I keep getting alerts in dutch when asking for vehicle informations. Even if the "lang" parameter is specified in french (or another language) in the uri. Is it normal ?

```
$url = 'https://api.irail.be/vehicle/?id=IC2432&format=json&alerts=true&lang=fr';
$curlhandle = curl_init();
curl_setopt($curlhandle, CURLOPT_URL,$url);
curl_setopt($curlhandle, CURLOPT_RETURNTRANSFER, 1);
$json = curl_exec($curlhandle);
curl_close($curlhandle);
$response = json_decode($json);
```

**Comment by ChristopheVersieux** [comment]
I notices the same issue this morning and can confirm the bug.

**Comment by Bertware** [comment]
There are two requests made to fetch vehicle information - only one of them (which is used to obtain the correct vehicle id) carried the correct language code, the other one used a hardcoded one. Both requests now use the correct language code. Thanks for reporting!

**Comment by Bertware** [comment]
Live example of the fixed response: https://api.irail.be/vehicle/?id=IC2432&format=json&alerts=true&lang=fr&date=130921
