### ISSUE TITLE
Disturbances (json, nl) response includes SimpleXML parse error

### ISSUE THREAD

**Issue by Muspah** [iRail/iRail#447]
Hi all,

When querying the disturbance API, we've noticed the response containing a SimpleXML error a few minutes ago:

Endpoint:
https://api.irail.be/disturbances/?format=json&lineBreakCharacter=|&lang=nl

Response:
`<br />
<b>Warning</b>:  SimpleXMLElement::__construct(): Entity: line 2: parser error : Extra content at the end of the document in <b>/var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php</b> on line <b>136</b><br />
<br />
<b>Warning</b>:  SimpleXMLElement::__construct(): &lt;p&gt;You might possibly want to report this to the  in <b>/var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php</b> on line <b>136</b><br />
<br />
<b>Warning</b>:  SimpleXMLElement::__construct(): ^ in <b>/var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php</b> on line <b>136</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php:136) in <b>/var/www/api.irail.be/src/api/output/Printer.php</b> on line <b>273</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php:136) in <b>/var/www/api.irail.be/src/api/output/Printer.php</b> on line <b>274</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php:136) in <b>/var/www/api.irail.be/src/api/output/Json.php</b> on line <b>23</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api.irail.be/src/api/data/NMBS/DisturbancesDatasource.php:136) in <b>/var/www/api.irail.be/src/api/output/Json.php</b> on line <b>24</b><br />`

...and after that, valid JSON.

Full message (the timestamp and envelope are from our own logging):
[irail-php-error.txt](https://github.com/iRail/iRail/files/7428068/irail-php-error.txt)

Kind regards,
Simon

**Comment by Bertware** [comment]
Please verify if the problem is fixed in staging: https://staging.api.irail.be/disturbances/

**Comment by Muspah** [comment]
Will use that endpoint and see what happens. Thanks!

**Comment by Muspah** [comment]
Seems okay now, thanks very much!

**Comment by Bertware** [comment]
Alright, will release this on api.irail.be

**Comment by Bertware** [comment]
The fix has now been deployed to api.irail.be, so make sure you update your application URL back to the normal one.

**Comment by Muspah** [comment]
Thanks, switched back to the regular API now!
