### ISSUE TITLE
Change Vehicle Information datasource

### ISSUE THREAD

**Issue by brechtvdv** [iRail/iRail#45]
The RailTime site closes, so it needs the data from somewhere else, eg. NMBS

**Comment by jncn** [comment]
Indeed, this no longer works as of yesterday: http://api.irail.be/vehicle/?id=BE.NMBS.IC3639

**Comment by brechtvdv** [comment]
https://github.com/brechtvdv/iRail/tree/Fix-%2345 

Needs to be fixed:
- [ ] Add delay time
- [ ] 'Van'-time. Undefined offset: 0 in /vagrant/api/data/NMBS/vehicleinformation.php on line 64
- [ ] No support when there are multiple journeys for a specific train

The NMBS gives also 'Naar'-time back, but there is only one time used in the API?
