### ISSUE TITLE
All trains are type "TRN"

### ISSUE THREAD

**Issue by SIMPYbe** [iRail/iRail#450]
All the departures are labeled as type "TRN" instead of "IC", "L", "P", "Sxx", etc...

**Comment by Bertware** [comment]
This is a data issue in the NMBS application, I was able to get the same result in the (old) official app. The new app doesn't have the same issue, but is lacking some endpoints. Seeing that they added timetables for stations, the only thing that's missing now is the overview for a vehicle, then we can switch to the new app as a datasource.

**Comment by SIMPYbe** [comment]
The strange thing is that the types have already turned into "trn" a few days ago. But changed again a few hours later to the correct train-type. And now it returned again...

**Comment by Bertware** [comment]
I would expect this to be an error on the side of their route-planning partner, or an error in the delivery of the raw data. It would be strange for them to not report train types on purpose - they would either keep the entire timetable search working for use in some official (internal or external) service, or kill it completely. So we can keep an eye on this, but I'd expect it to be back to normal tomorrow.

**Comment by SIMPYbe** [comment]
I heard that the NMBS is working at "het fabriekje" that is regulating the internal dataflow. Hopefully this issue will be solved soon :)

**Comment by Muspah** [comment]
Hahaha, seems legit. Can't be worse then another national railway company in a country that speaks (almost) the same language as the Flemish that I'm not gonna mention by name, lol.

**Comment by Bertware** [comment]
Speaking from experience in a country that doesn't speak the same language, but has the same (only european?) partner(s), internal dataflows and legacy (vintage) systems get complicated and tend to have weird quirks.

**Comment by Muspah** [comment]
Haha yeah it is, NS used to have and has the same problems. I'm not sure about Hafas' position outside Europe, I've only worked with European train companies.

**Comment by SIMPYbe** [comment]
Problem is solved and stable the last week.
