### ISSUE TITLE
Crowd prediction no longer visible

### ISSUE THREAD

**Issue by WouterVanDorsselaer** [iRail/iRail#453]
The crowd prediction indicator no longer shows up in third-party apps such as the Railer app. They do still work in the official NMBS app.

**Comment by Bertware** [comment]
Seems to be related to a recent upgrade to PHP 8. Fixed most of the issues, but for some reason the predictions don't come out (yet)

**Comment by jncn** [comment]
Honestly, I'd love to see it replaced by the NMBS occupancy 😇

```
              "CommercialInfo": {
                "Occupancy": {
                  "Level": 1
                }
              }
```

**Comment by Bertware** [comment]
Done! Spitsgids is working again and NMBS data is used as well.
