### ISSUE TITLE
Canceled trains not always indicated

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#454]
https://api.irail.be/connections/?from=antwerpen-centraal&to=gent-sint-pieters&time=9:00&date=040522&format=json ==> first connection should be canceled, but it is not indicated as such

**Comment by Bertware** [comment]
IC1830, departing 09:06:00, should be canceled but is not indicated as such by iRail. Raw data for this query:

[issue454.json.zip](https://github.com/iRail/iRail/files/8626834/issue454.json.zip)

**Comment by Bertware** [comment]
Looks like `isRedir: true` matches redirected in Hacon open-data APIs
`redirected: Will be true if this journey is redirected.`

**Comment by Bertware** [comment]
Canceled trains have been tested in #512 so this should be fixed now
