### ISSUE TITLE
Realtime information not available

### ISSUE THREAD

**Issue by SIMPYbe** [iRail/iRail#459]
It seems that the NMBS doesn't push realtime information to HAFAS anymore.
Delay information is not shown in irail.

I would also recommend to return NULL (no delay information) instead of 0 (delay = 0, so "on time")...
https://github.com/iRail/iRail/blob/54ee375d795191df5b24fede489423392daba593/src/api/data/NMBS/LiveboardDatasource.php#L454

**Comment by SIMPYbe** [comment]
The data is magically available again...

**Comment by Bertware** [comment]
Closing since this issue originated in an external service which is fixed now
