### ISSUE TITLE
Luxembourg is in stations.csv but does not appear in the API

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#46]
See: https://github.com/iRail/stations/blob/master/stations.csv#L614

And compare to http://api.irail.be/stations.php

If Luxembourg doesn't appear in the API list, we cannot use it as a start/stop point easily!

A lot of people use BeTrains in Luxembourg, and that's a problem.

**Comment by pietercolpaert** [comment]
Thanks for this issue! One of the next days I'll make this list a proxy for the CSV file

**Comment by Tjoosten** [comment]
Any news on this?

**Comment by pietercolpaert** [comment]
Working on it as we speak: first up is fixing #94

**Comment by Tjoosten** [comment]
Alright!
