### ISSUE TITLE
Compositions return error 404

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#461]
The API returns an error, but the data is still available on https://trainmap.belgiantrain.be

**NMBS**
<img width="677" alt="image" src="https://user-images.githubusercontent.com/995815/181208290-c8b069b9-2185-4468-92dc-76ba229fb445.png">

**iRail API**
https://staging.api.irail.be/composition/?lang=en&id=BE.NMBS.L2781 → `<error code="404">Could not find vehicle 2781</error>`

Probably related to #460.

**Comment by Bertware** [comment]
Fixed!
