### ISSUE TITLE
Composition API doesn't return a result for most of the trains

### ISSUE THREAD

**Issue by tasozgurcem11** [iRail/iRail#464]
[https://staging.api.irail.be/composition/?lang=en&id=BE.NMBS.EUR9116](https://staging.api.irail.be/composition/?lang=en&id=BE.NMBS.EUR9116)

returns `<error code="404">Could not find vehicle 9116</error>`

Most of the vehicles/trains that I tried returned this response. 

I also looked for #461 but I couldn't solve it.

**Comment by KoenVW1978** [comment]
Is there any plan to work in this issue?
I came accross the same problem:
https://api.irail.be/composition/?format=json&id=BE.NMBS.IC2845&data=all&lang=en
{"error":404,"message":"Could not find vehicle 2845"}

**Comment by Bertware** [comment]
The "fix" to this issue is likely to improve the error message, and specify that composition only is available for trains that have started their journey
