### ISSUE TITLE
Connections throws error when `lang=en` and station IDs

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#47]
Does work: `http://api.irail.be/connections/?to=BE.NMBS.008814001&from=BE.NMBS.008892007&lang=nl`

Does not work: `http://api.irail.be/connections/?to=BE.NMBS.008814001&from=BE.NMBS.008892007&lang=en`

**Comment by pietercolpaert** [comment]
Fixed. While fixing  https://github.com/iRail/hyperRail#98

Can you confirm and close?

**Comment by jncn** [comment]
Thanks Pieter!
