### ISSUE TITLE
Error getting details for vehicle (nmbs)

### ISSUE THREAD

**Issue by orbatec** [iRail/iRail#470]
We use the iRail api to get NMBS timetable info. When we click no a journey to view the details, we get the details back of the journey, but we also get an error. We are executing 2 calls in a row:

1. `https://staging.api.irail.be/connections?format=json&lang=nl&from=008895000&to=008891702&typeOfTransport=trains&timesel=departure&time=0958&date=310123`
2. `https://staging.api.irail.be/vehicle?format=json&lang=nl&id=BE.NMBS.IC1833&date=3101231`

It is call 2 that fails

`{"timestamp":"2023-01-31T08:55:53+0000","status":500,"error":"Internal Server Error","message":"503 Could not get data: GTFS data is being processed. Please try again later.. Please report this issue at https://github.com/irail/irail/issues/new: \"{\"error\":503,\"message\":\"Could not get data: GTFS data is being processed. Please try again later.. Please report this issue at [https://github.com/irail/irail/issues/new\"}\"`

**Comment by orbatec** [comment]
It seems to be that this is the call that is in error:
`https://staging.api.irail.be/vehicle?format=json&lang=nl&id=BE.NMBS.IC1833&date=3101231`

**Comment by SIMPYbe** [comment]
Possible cause: The GTFS feed from NMBS/SNCB is down (hafas.de).

**Comment by xivk** [comment]
Yep also empty here:

https://gtfs.irail.be/nmbs/gtfs/

**Comment by xivk** [comment]
@Bertware Could it be a solution to use an earlier version of the GTFS for now?

**Comment by Bertware** [comment]
Solution is, as you stated, to use an earlier version, as well as replacing the "latest" folder with an unpacked version of yesterdays data.
Latest.zip and latest/ points now to yesterdays (valid) file, and should fix the issue. It seems however that there are still some issues with the reading of calendar_dates.txt.
