### ISSUE TITLE
Static GTFS is outdated compared to NMBS static GTFS

### ISSUE THREAD

**Issue by RailwAI** [iRail/iRail#471]
Hi,

The GTFS static feed from https://gtfs.irail.be/nmbs seems to be outdated to the static GTFS feed from NMBS (via [this page](https://www.belgiantrain.be/nl/3rd-party-services/mobility-service-providers/public-data/use-our-data)). I had some problems downloading the NMBS GTFS feed a few days ago and decided to switch to the irail GTFS, but it gave me some issues yesterday, since some trip_id values are missing in your GTFS feed.

Best regards, Rens

**Comment by Bertware** [comment]
We disabled the feed update earlier this week to prevent ingesting empty files, but have not re-enabled this yet. I'd expect the file to be up to date again either tomorrow or on monday.

**Comment by Bertware** [comment]
Hi Rens,

latest.zip points now correctly to todays GTFS file and will update automatically again. The unpacked folder will be updated automatically when tomorrows file is fetched. You can verify this tomorrow and close the issue if it works as expected again.

Regards,
Bert
