### ISSUE TITLE
Planning data

### ISSUE THREAD

**Issue by pcoenen** [iRail/iRail#475]
Not really an issue or request, but is there an easy way to get information on which days of the week a certain train is driving?

For example, I want to know on which days of the week IC2019 is driving, the answer could be from Monday-Friday.

**Comment by DylanVanAssche** [comment]
Hi!

iRail does not have this data exposed as an API AFAIK, but it is inside the GTFS dumps `calendar.txt` and `calendar_dates.txt`. Would require some work though to do a lookup between vehicle IDs and the GTFS.

**Comment by Muspah** [comment]
The underlying HAFAS API does include a bitmap of the service days, it should be fairly trivial to add this to the iRail API.

https://gist.github.com/Muspah/7713ebfc36e9a355077ce64c52675293
"sDaysB": "7CF9F3E7CF9F3E7CF9F3E7CF9F3E7C79F3E3CF9D3E3CF9F3E7CF9F3C7CF9F2E7CF9F3E7CF9F3E7CF9B3E7CF9F3E0",
