### ISSUE TITLE
Adjust "please report this message" when an underlying data service did not respond

### ISSUE THREAD

**Issue by Mariusthvdb** [iRail/iRail#478]
getting this in Home Assistant logs:
```
Logger: homeassistant.components.nmbs.sensor
Source: components/nmbs/sensor.py:303 
Integration: nmbs (documentation, issues) 
First occurred: 16:43:13 (15 occurrences) 
Last logged: 19:39:41

API returned invalid connection: {'error': 500, 'message': 'Could not get data: This request failed due to internal errors.. Please report this issue at https://github.com/irail/irail/issues/new'}
API returned invalid connection: {'error': 504, 'message': 'Could not get data: An upstream server experienced a timeout while obtaining this data. Please report this issue at https://github.com/irail/irail/issues/new'}

```

not sure what else to report,
please have a look?
thanks

**Comment by Bertware** [comment]
`An upstream server experienced a timeout while obtaining this data` means the underlying data sources (NMBS internal APIs) did not return a response, something we can't do anything about. The 504 status code identifies this issue from other server issues (which typically will cause a 500 error). This can happen now and then, and as long as it doesn't hamper usage of the API, you can ignore any errors. 

The "please report this issue" text is a bit unfortunate for these upstream errors, it might be valuable to not include that in the error message on these 504 errors.

Thanks for reporting anyway!

**Comment by Mariusthvdb** [comment]
well, its is happening for prolonged periods of time. as a matter of fact, its always there....

```
Logger: homeassistant.components.nmbs.sensor
Source: components/nmbs/sensor.py:303 
Integration: nmbs (documentation, issues) 
First occurred: 16 juni 2023 om 20:16:28 (3022 occurrences) 
Last logged: 11:26:55

API returned invalid connection: {'error': 500, 'message': 'Could not get data: This request failed due to internal errors.. Please report this issue at https://github.com/irail/irail/issues/new'}
API returned invalid connection: {'error': 404, 'message': 'No results found'}
API returned invalid connection: {'error': 504, 'message': 'Could not get data: An upstream server experienced a timeout while obtaining this data. Please report this issue at https://github.com/irail/irail/issues/new'}
API returned invalid connection: {'error': 504, 'message': 'Could not get data: No response from NMBS/SNCB. Please report this issue at https://github.com/irail/irail/issues/new'}
```

**Comment by Muspah** [comment]
We're mass-querying SNCB too and experience the same issue, requests just fail sometimes because SNCB's upstream service fails.

**Comment by Muspah** [comment]
We're mass-querying SNCB too and experience the same issue, requests just fail sometimes because SNCB's upstream service fails.

**Comment by Mariusthvdb** [comment]
on ignoring the errors:
though I really feel we shouldnt ignore errors (rather lower the level to warning maybe) we can do this in the ,ogre:
```
filters:
  homeassistant.components.nmbs.sensor:
    - API returned invalid connection
    - API failed in NMBSSensor
```

let's wait and see what that results in, cleaning the logs, and keeping the integration useful
the for anything you might be able to do to reduce the hammering

**Comment by Bertware** [comment]
Will see if this can be achieved easily, otherwise the HTTP status already reflects this "source data unavailable" issue through the HTTP 504 error which is exclusively used for errors of this kind.

> The HyperText Transfer Protocol (HTTP) 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request.

**Comment by Bertware** [comment]
The message has now been clarified, feel free to reopen if further changes are needed
