### ISSUE TITLE
Staging not aligned with production

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#480]
On staging sometimes Charleroi-Central is still displayed as Charleroi-Sud. On production this issue is not present.

e.g. https://staging.api.irail.be/connections/?lang=nl&to=BE.NMBS.008872009&from=BE.NMBS.008814001

Staging:
<img width="1429" alt="Screenshot 2023-05-06 at 23 36 41" src="https://user-images.githubusercontent.com/995815/236647537-3a265590-ee9c-4cb1-a90d-7ee203086944.png">

Production:
<img width="1504" alt="Screenshot 2023-05-06 at 23 34 27" src="https://user-images.githubusercontent.com/995815/236647516-b4692884-f592-435c-b14e-040befc84e13.png">

**Comment by Bertware** [comment]
Fixed!
