### ISSUE TITLE
Compostion of train not working

### ISSUE THREAD

**Issue by LucasMiserez** [iRail/iRail#482]
Everytime I try to get the composition of a train, I get: <error code="404">Could not find vehicle 1507</error>

I tried many different ways to identify the train and even used the api url on the website. But same result.

**Comment by Muspah** [comment]
Compositions are only available for trains that are running at the moment of requesting. Is that what you're trying?

**Comment by LucasMiserez** [comment]
> Compositions are only available for trains that are running at the moment of requesting. Is that what you're trying?
> 
> (Or iRail should start querying bikeontrain)

Is it only for the trains that are running at the moment of requesting? Because most trains thats I tested do not work atm

**Comment by Muspah** [comment]
Yes, iRail's source (NMBS trainmap) only provides data for trains that are running. Planned or historical data isn't available.
