### ISSUE TITLE
Liveboard gives error on certain departure times

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#484]
Compare these two requests:
`https://staging.api.irail.be/liveboard/?date=270523&arrdep=departure&time=1550&station=BE.NMBS.008814001` 
`https://staging.api.irail.be/liveboard/?date=270523&arrdep=departure&time=1430&station=BE.NMBS.008814001`

Apart from `time` these requests are identical, however the one with `time=1430` throws `<error code="404">Could not find a station with id 008748100.</error>`. Which makes sense, because there is indeed no station with that id. The station id in the error is not about the requested station.

**Comment by Muspah** [comment]
87 is France, 8748100 is Nantes. I'd expect an international train service that is not in the GTFS files.

**Comment by Muspah** [comment]
![image](https://github.com/iRail/iRail/assets/43544407/b1b6d2f2-b45e-43bb-89f7-358347c17a06)
TGV to Nantes. One might add the station to [iRail/stations](https://github.com/iRail/stations) to fix this.

**Comment by Bertware** [comment]
Nantes is already present with 008748100, will update staging which also fixes #480

**Comment by Bertware** [comment]
Fixed!

**Comment by jncn** [comment]
Oh so this issue was only present on staging? It didn't occur to me to test on production. Thanks for fixing both issues!
