### ISSUE TITLE
Could not find a station with id 008032318

### ISSUE THREAD

**Issue by jeanbaptistemarie** [iRail/iRail#486]
Hello there,

The live departure endpoint return an error for Bruxelles-Midi station 
{"error":404,"message":"Could not find a station with id 008032318."}

This is the same issue as described in #476 but for station id 008032318

Can you add it to the stations data? I could not find what station has this uic code.

Thanks

**Comment by Muspah** [comment]
80 means a German station at least. I'm not able to lookup which one at the moment.

**Comment by Bertware** [comment]
I can't find this station in any european datasets either. Should this error occur again, please make a request resulting in this exception with the `&debug=true` to save additional debug data which could help in identifying the station.

**Comment by jeanbaptistemarie** [comment]
> Berlin Lichtenberg

May I ask where you found the station for this UIC code? I could not find it in Deutsche railway Bahn stations repository.
Thanks

**Comment by stefaandesmet2003** [comment]
Working for the company that this repo is scraping
