### ISSUE TITLE
Compositions are not retrieved anymore - starting 07/06/23 14:40

### ISSUE THREAD

**Issue by 121593** [iRail/iRail#487]
Since Wednesday 07/06/23 14H40, Irail is returning `Could not find vehicle xxx` for every `/composition` request.

The problem lies probably in the Trainmap Api authentication or data parsing as :

* No recent changes have been done in Irail
* The composition is shown when navigating on Trainmap (`https://trainmap.belgiantrain.be/data/composition/xxx` answers as expected) 

As additional context, most Trainmap composition responses now contains `confirmedBy: "IDA"`. To my knowledge it was not previously the case, which would indicate an update in the API. 

Any info on this matter ?

**Comment by Muspah** [comment]
Single quotes (') around the word _tmAuthCode_ have been replaced with dual (""), the regex pattern won't match the code.

ConfirmedBy can be both IDA or Mistral, that's from a previous update. Didn't bother to look through all my archive files, but it's from before May '23 at least.

**Comment by jncn** [comment]
Is this fix live already? I still get the error on production

**Comment by jncn** [comment]
And an XML error on staging: https://staging.api.irail.be/composition/?lang=nl&id=BE.NMBS.S11785

**Comment by 121593** [comment]
Well seen @jncn, indeed the regex failed to parse the token. Should work with the new PR.
