### ISSUE TITLE
Could not find a station with id 008065969

### ISSUE THREAD

**Issue by jeanbaptistemarie** [iRail/iRail#491]
Hello there,

The live departure endpoint return an error for Bruxelles-Midi station ID
`{"error":404,"message":"Could not find a station with id 008065969."}`

https://api.irail.be/liveboard/?id=BE.NMBS.008814001&arrdep=departure&lang=fr&format=json&alerts=true&debug=true

This is the same issue as described in #486 

Can you add it to the stations data? I could not find what station has this uic code.

Thanks

**Comment by Bertware** [comment]
Should be fixed by https://github.com/iRail/stations/commit/47c2da00e1922c5fd4dfaa6962a10218f8a8db15
It seems like Berlin HBF has two UIC codes, likely for the old and new station. The code has now been changed to the one in use by NMBS.

Please reopen should a new issue arise around Berlin HBF.
