### ISSUE TITLE
Could not get data at specific times (due to exp trains?)

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#492]
For example in Ghent the 27/06; at 06:22 the departures are working:

https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=270623&time=0622&arrdep=departure&lang=en&format=json&alerts=false

However, by changing the time where exp trains are running, i just receive an error (HTTP error 500)i:

https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=270623&time=0922&arrdep=departure&lang=en&format=json&alerts=false

**Comment by Bertware** [comment]
Seems like I missed this issue, but it may have been caused by either EXP trains as you stated, or (most likely) by station IDs which could not be resolved. Please update this issue with a new date/time for the current timetable should it occur again.
