### ISSUE TITLE
Error 500 often pops up on production 

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#494]
e.g. https://api.irail.be/connections/?lang=nl&format=json&from=BE.NMBS.008896115&to=BE.NMBS.008833126&timesel=departure&date=131023&time=1355

```
{"error":500,"message":"Could not get data: This request failed due to internal errors.. Please report this issue at https://github.com/irail/irail/issues/new"}
```

A few seconds later the error is gone. Happens ever so often.

**Comment by koeleboe** [comment]
I dont know if it has something to do with it, but lately the liveboards are pretty buggy, especially when going into the past. Often not all trains are shown (only one or two or even nothing - error)

**Comment by Bertware** [comment]
Closing since the codebase has been replaced (with better error tracking as well, any error should come with a request-id now)
