### ISSUE TITLE
Spam(?) link on blog

### ISSUE THREAD

**Issue by Gaelan** [iRail/iRail#495]
I happened to notice that, half way through [this blog post](https://hello.irail.be/2018/03/16/one-million-daily-requests-where-do-they-come-from-and-how-well-cope-with-them/), under the paragraph "Why clients use iRail", there's a random link in the middle of a sentence to a seller of inflatable water slides.

Presumably this is an attempt at SEO spam added by someone who's gained access to your WordPress install.

**Comment by Bertware** [comment]
Hi!

Thanks for reporting this, I removed the link. The intrusion (through a plugin with a malicious update) was noticed and cleaned up, but seems like I missed this change.

Regards,
Bert
