### ISSUE TITLE
Platform "normal" flag not updated

### ISSUE THREAD

**Issue by dingcycle** [iRail/iRail#496]
In the [liveboard](https://docs.irail.be/#liveboard) as well as in the [connections](https://docs.irail.be/#connections) iRail API routes, it looks like the platform info is now faulty, it's always set to `1`, whatever the train, and whether there's a platform change of not

Let's compare the late trains leaving from Gent-St-Pieters, between the Liveboard from [Trainmap](https://trainmap.belgiantrain.be) and the [iRail API](https://api.irail.be/liveboard/?id=BE.NMBS.008892007&station=Gent&date=251023&time=1938&arrdep=departure&lang=en&format=json&alerts=false):

**Trainmap**:
![Trains leaving from Ghent](https://github.com/iRail/iRail/assets/1681985/89cafe06-66ce-4579-8c59-d9c70ed37f4d)

**iRail**: (`$ grep  -B2 -A30 'delay.*"[0-9]\{3,\}\+"' dump_liveboard_gent.json`)
```json
      {
        "id": "0",
        "delay": "1140",
        "station": "Genk",
        "stationinfo": {
          "locationX": "5.497685",
          "locationY": "50.967057",
          "id": "BE.NMBS.008831765",
          "name": "Genk",
          "@id": "http://irail.be/stations/NMBS/008831765",
          "standardname": "Genk"
        },
        "time": "1698255540",
        "vehicle": "BE.NMBS.IC1518",
        "vehicleinfo": {
          "name": "BE.NMBS.IC1518",
          "shortname": "IC1518",
          "number": "1518",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC1518"
        },
        "platform": "8",
        "platforminfo": {
          "name": "8",
          "normal": "1"  <=====================issue here=============== ?
        },
        "canceled": "0",
        "left": "0",
        "isExtra": "0",
        "departureConnection": "http://irail.be/connections/8892007/20231025/IC1518"
      },
--
      {
        "id": "7",
        "delay": "1080",
        "station": "Brussels Airport - Zaventem",
        "stationinfo": {
          "locationX": "4.482076",
          "locationY": "50.896456",
          "id": "BE.NMBS.008819406",
          "name": "Brussels Airport - Zaventem",
          "@id": "http://irail.be/stations/NMBS/008819406",
          "standardname": "Brussels Airport - Zaventem"
        },
        "time": "1698256800",
        "vehicle": "BE.NMBS.IC2819",
        "vehicleinfo": {
          "name": "BE.NMBS.IC2819",
          "shortname": "IC2819",
          "number": "2819",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC2819"
        },
        "platform": "9",
        "platforminfo": {
          "name": "9",
          "normal": "1"  <=====================issue here=============== ?
        },
        "canceled": "0",
        "left": "0",
        "isExtra": "0",
        "departureConnection": "http://irail.be/connections/8892007/20231025/IC2819"
      },
```
We can see that the `platforminfo` is always set to `"normal": "1"`, which is not true because there *is* a change of platform, as the Trainmap liveboard hints with the little squares around the platform number.

**Comment by Bertware** [comment]
Can confirm the issue for departures, where this was left as a TODO since it was not clear how this information could be obtained after the NMBS did a major overhaul of their data services. Nowadays this function seems to have been implemented by the NMBS and can be implemented in iRail, will fix this.

Can't reproduce the issue for connections though, seems to be working correctly there.

**Comment by Bertware** [comment]
Both platform changes and cancellations are now detected correctly! Thanks for pointing this out.

**Comment by dingcycle** [comment]
Thanks for fixing it so quickly :)
