### ISSUE TITLE
Subtype of composition of AM96 is empty

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#498]
When checking the composition of a train with AM96:
https://[api.irail.be/composition/?format=json&id=IC3637](https://api.irail.be/composition/?format=json&id=IC3637)
the returned subtype is unknown. For the other trains, there is a subtype (AM80 does have them).
```
"unit": [
                                {
                                    "id": "0",
                                    "materialType": {
                                        "parent_type": "AM96M",
                                        "sub_type": "unknown",
                                        "orientation": "LEFT"
                                    },
```
This breaks the ability to show the composition in hyperrail.

**Comment by Bertware** [comment]
This one has been fixed in https://github.com/iRail/iRail/commit/1114e71c751db6a86e1b81c0374a35ad78ebcdf6 and https://github.com/iRail/iRail/commit/22fadd845e35cfecddb3574365dea8d33a2d645b
