### ISSUE TITLE
GTFS data is being processed

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#499]
GTFS data is being processed (https://[api.irail.be/vehicle/?id=530&date=031123&format=json&lang=nl](https://api.irail.be/vehicle/?id=530&date=031123&format=json&lang=nl). The GTFS seems to be wrong on the server as well (empty).

![image](https://github.com/iRail/iRail/assets/72651779/804ec943-b072-4c9d-b05d-b1da0225a4f1)

**Comment by Bertware** [comment]
Fixed now by replacing both `latest.zip` and the `latest/` folder with the file from November 2nd.

Those GTFS files are being created by an old shell script on a cron-job, without any checks on whether the file is valid. It should be updated to include a check to see if the downloaded file was valid, and if not, the script should either retry or abort.

```
#!/bin/bash

FTPURL="https://sncb-opendata.hafas.de/gtfs/static/c...e"
TMPFOLDER="/tmp/nmbs-gtfs/"
TMPFILE=$TMPFOLDER/nmbs-gtfs.zip

echo "## Cleaning up..."
rm -rf $TMPFOLDER
rm -rf /var/www/gtfs.irail.be/public/nmbs/gtfs/latest/
mkdir -p $TMPFOLDER

echo "## Downloading and extracting new zip file..."
wget --mirror $FTPURL -O $TMPFILE
DATE=$(date +%Y-%m-%d);
echo "## copy to gtfs.irail.be"
cp $TMPFILE /var/www/gtfs.irail.be/public/nmbs/gtfs/latest.zip
cp $TMPFILE /var/www/gtfs.irail.be/public/nmbs/gtfs/gtfs-nmbs-$DATE.zip
unzip $TMPFILE -d /var/www/gtfs.irail.be/public/nmbs/gtfs/latest/
```

**Comment by Bertware** [comment]
Added 

```
if [ -s $TMPFILE ]; then
        # The file is not-empty.
        echo "Download completed"
else
        # The file is empty.
        echo "Failed to download file"
        exit 1
fi
```

Directly after the file download now, which should prevent this problem in the future. I'm still open for further improvements here though.

**Comment by Bertware** [comment]
gtfs.irail.be has gotten an update to be more stable, which solves this issue
