### ISSUE TITLE
TLS v1.3

### ISSUE THREAD

**Issue by vhdirk** [iRail/iRail#500]
Hi,

I'm working on an iRail client on an embedded device (https://github.com/vhdirk/papertrain). I'd like to use https, but my preferred crypto library only supports tls v1.3. Apparently, that is not yet supported by iRail? https://www.cdn77.com/tls-test/result?domain=https%3A%2F%2Fapi.irail.be

Would it be possible to enable TLS 1.3?

Thanks!

**Comment by Bertware** [comment]
Hi!

I looked into this on Saturday, but could not get nginx to accept TLS 1.3 yet. I definitely agree on adding support for it though!

**Comment by Bertware** [comment]
Can you try again? TLS 1.3 should now be working

**Comment by vhdirk** [comment]
Yep, working as expected. Thanks!
