### ISSUE TITLE
Composition API in SNCB Lab App

### ISSUE THREAD

**Issue by HybridFox** [iRail/iRail#502]
The new SNCB Lab App now shows the composition in the app using the `mobile-riv.api`. Might be interesting using this instead of the trainmap API. Haven't had the chance to see if there is a difference between the two.
```
curl --request GET \
  --url 'https://mobile-riv.api.belgianrail.be/api/v1/commercialtraincompositionsbetweenptcars?TrainNumber=2934&From=8821600&To=8821006&date=2023-11-14&FromToAreUicCodes=true&IncludeMaterialInfo=true' \
  --header 'Accept: application/json; charset=utf-8' \
  --header 'x-api-key: IOS-v0001-20190214-YKNDlEPxDqynCovC2ciUOYl8L6aMwU4WuhKaNtxl'
```

**Comment by HybridFox** [comment]
Digging a bit deeper, it seems the API requires `From` and `To` query parameters, those are ones that (afaik) iRail does not require, making it seem like the switch wouldnt be a simple replacement. Except for those two query parameters, the trainmap and mobile-riv api seem identical

**Comment by SIMPYbe** [comment]
I had a meeting with the railways last week, and they announced to phase out the train map this year... I warned them that the train composition "feature" is used by others and that they should publish it as open data instead. They will take a look into it, hopefully there will be a nice solution for this.

**Comment by Bertware** [comment]
> I had a meeting with the railways last week, and they announced to phase out the train map this year... I warned them that the train composition "feature" is used by others and that they should publish it as open data instead. They will take a look into it, hopefully there will be a nice solution for this.

Sounds like they may move over to their own composition endpoint mentioned by @HybridFox? I can now easily get the start and end station for each vehicle without issues, so moving to that endpoint shouldn't be a problem. That would mean they keep the composition but can ditch the trainmap while keeping the underlying data for use in their other existing apps

**Comment by SIMPYbe** [comment]
Train map is offline... The end of this data source :(

**Comment by Bertware** [comment]
The data is however still available in the NMBS internal API, and can still be loaded, so it should be up and running again soon

**Comment by Bertware** [comment]
I can't backport this code in the old API, but can hopefully switch production to the new codebase in one of the next days. Until then, you can try replacing api.irail.be with lumen.api.irail.be as the new codebase should be a drop-in replacement

**Comment by Bertware** [comment]
The new codebase is live, with this new datasource. Thanks for tipping this @HybridFox !
