### ISSUE TITLE
Mismatch between haltelink/Irail with composition

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#505]
In the irail composition query (vehicle numbers are 8158 and 8148: 
version":"1.2","timestamp":"1700672482","composition":{"segments":{"number":"1","segment":[{"id":"0","origin":{"locationX":"4.715866","locationY":"50.88228","id":"BE.NMBS.008833001","name":"Leuven","@id":"http:\/\/irail.be\/stations\/NMBS\/008833001","standardname":"Leuven"},"destination":{"locationX":"4.715866","locationY":"50.88228","id":"BE.NMBS.008833001","name":"Leuven","@id":"http:\/\/irail.be\/stations\/NMBS\/008833001","standardname":"Leuven"},"composition":{"source":"Mistral","units":{"number":"6","unit":[{"id":"0","materialType":{"parent_type":"AM08M","sub_type":"a","orientation":"LEFT"},"hasToilets":"1","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8158","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"27","standingPlacesFirstClass":"9","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"76","seatsFirstClass":"16","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_c","tractionPosition":"1","hasPrmSection":"1","hasPriorityPlaces":"1","hasBikeSection":"1"},{"id":"1","materialType":{"parent_type":"AM08M","sub_type":"b","orientation":"LEFT"},"hasToilets":"0","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8158","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"40","standingPlacesFirstClass":"0","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"104","seatsFirstClass":"0","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_b","tractionPosition":"1","hasPrmSection":"0","hasPriorityPlaces":"1","hasBikeSection":"0"},{"id":"2","materialType":{"parent_type":"AM08M","sub_type":"c","orientation":"RIGHT"},"hasToilets":"0","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8158","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"37","standingPlacesFirstClass":"9","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"68","seatsFirstClass":"16","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_a","tractionPosition":"1","hasPrmSection":"0","hasPriorityPlaces":"1","hasBikeSection":"0"},{"id":"3","materialType":{"parent_type":"AM08M","sub_type":"a","orientation":"LEFT"},"hasToilets":"1","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8148","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"27","standingPlacesFirstClass":"9","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"76","seatsFirstClass":"16","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_c","tractionPosition":"2","hasPrmSection":"1","hasPriorityPlaces":"1","hasBikeSection":"1"},{"id":"4","materialType":{"parent_type":"AM08M","sub_type":"b","orientation":"LEFT"},"hasToilets":"0","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8148","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"40","standingPlacesFirstClass":"0","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"104","seatsFirstClass":"0","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_b","tractionPosition":"2","hasPrmSection":"0","hasPriorityPlaces":"1","hasBikeSection":"0"},{"id":"5","materialType":{"parent_type":"AM08M","sub_type":"c","orientation":"RIGHT"},"hasToilets":"0","hasTables":"1","hasSecondClassOutlets":"1","hasFirstClassOutlets":"1","hasHeating":"1","hasAirco":"1","materialNumber":"8148","tractionType":"HV","canPassToNextUnit":"0","standingPlacesSecondClass":"37","standingPlacesFirstClass":"9","seatsCoupeSecondClass":"0","seatsCoupeFirstClass":"0","seatsSecondClass":"68","seatsFirstClass":"16","lengthInMeter":"27","hasSemiAutomaticInteriorDoors":"1","hasLuggageSection":"0","materialSubTypeName":"AM08M_a","tractionPosition":"2","hasPrmSection":"0","hasPriorityPlaces":"1","hasBikeSection":"0"}]}}}]}}}

Using haltelink: 
https://project.haltelink.be/treinsamenstelling/?TrainNumber=4117
We see the correct numbers (8097 and 8092 as I'm sitting in that train).

It happens often.

**Comment by Bertware** [comment]
Irail should always provide correct compositions now
