### ISSUE TITLE
Most IC parentype/subtype UNKNOWN in composition

### ISSUE THREAD

**Issue by koeleboe** [iRail/iRail#506]
Since today, a lot of trains have an unkown composition. Only the materialSubTypeName is present. The first class/second class seats are also not available.

For example: https://[api.irail.be/composition/?format=json&id=IC1809](https://api.irail.be/composition/?format=json&id=IC1809)
` "composition": {
                        "source": "ITR",
                        "units": {
                            "number": "9",
                            "unit": [
                                {
                                    "id": "0",
                                    "materialType": {
                                        "parent_type": "unknown",
                                        "sub_type": "unknown",
                                        "orientation": "LEFT"
                                    },
                                    "hasToilets": "0",
                                    "hasTables": "0",
                                    "hasSecondClassOutlets": "0",
                                    "hasFirstClassOutlets": "0",
                                    "hasHeating": "0",
                                    "hasAirco": "0",
                                    "materialNumber": "65060",
                                    "tractionType": "unknown",
                                    "canPassToNextUnit": "0",
                                    "standingPlacesSecondClass": "0",
                                    "standingPlacesFirstClass": "0",
                                    "seatsCoupeSecondClass": "0",
                                    "seatsCoupeFirstClass": "0",
                                    "seatsSecondClass": "0",
                                    "seatsFirstClass": "0",
                                    "lengthInMeter": "0",
                                    "hasSemiAutomaticInteriorDoors": "0",
                                    "hasLuggageSection": "0",
                                    "materialSubTypeName": "M6BXCT",
                                    "tractionPosition": "1",
                                    "hasPrmSection": "0",
                                    "hasPriorityPlaces": "0",
                                    "hasBikeSection": "0"`

I think there are some changes implemented in the API from NMBS?

**Comment by Bertware** [comment]
This seems to affect their own applications as well:
![Screenshot of trainmap](https://github.com/iRail/iRail/assets/1094793/af22ff07-3f98-42d8-abeb-26172142c8e8)

The response data is almost empty:

```json
"materialUnits": [
      {
        "diagramServiceNumber": 9,
        "materialNumber": 76049,
        "materialDiagram": "B4",
        "uicCode": "918886960494",
        "isLocoInUse": true,
        "inDirection": false,
        "tractionPosition": 1,
        "positionInComposition": 1,
        "materialSubTypeName": "M7BMX",
        "materialTypeName": "M7BMX"
      },
      {
        "diagramServiceNumber": 61,
        "materialNumber": 69012,
        "materialDiagram": "JR",
        "uicCode": "508882720123",
        "isLocoInUse": false,
        "inDirection": true,
        "tractionPosition": 2,
        "positionInComposition": 2,
        "materialSubTypeName": "M6BDU",
        "materialTypeName": "M6"
      },
...
]
```

I have now pushed a fix (https://github.com/iRail/iRail/commit/c9d0cd87bf36b18500b5d7eb0f15131afec5dfa8) which improves parsing in these cases where no `tractionType` is present. The number of seats etc will however still be 0 until this is fixed at the source.
