### ISSUE TITLE
Composition of vehicle can't be found

### ISSUE THREAD

**Issue by VandeVoordeMatthias** [iRail/iRail#510]
Since yesterday, I have found that the composition of trains cannot be found. I discovered this via HyperRail app. After making a request on the endpoint composition myself, it was never found.

Request
`https://api.irail.be/composition/?format=json&id='IC3610'&data="&lang=en`

Response
`{"error":404,"message":"Could not find vehicle 3610"}`

**Comment by Bertware** [comment]
It seems like the data source we use for this is currently unavailable:
https://trainmap.belgiantrain.be/

**Comment by VandeVoordeMatthias** [comment]
Just checked, and see that it works again!
