### ISSUE TITLE
iRail composition doesn't match with NMBS

### ISSUE THREAD

**Issue by VandeVoordeMatthias** [iRail/iRail#515]
I took this train today and found out in Gent-Sint-Pieters that the train was split. So iRail showed the composition after the split.

<img width="781" alt="Screenshot 2024-04-30 at 08 59 02" src="https://github.com/iRail/iRail/assets/145774004/d27a3fdb-4d86-4025-ad4c-7ebd33ebbf83">

**The request:**
`https://api.irail.be/v1/composition/?id=S51778&date=300424&lang=nl&alerts=true&format=json`

**The response:**
```json
{
  "version": "1.3",
  "timestamp": "1714454330",
  "composition": {
    "segments": {
      "number": "1",
      "segment": [
        {
          "id": "0",
          "origin": {
            "@id": "http://irail.be/stations/NMBS/008892007",
            "id": "BE.NMBS.008892007",
            "name": "Gent-Sint-Pieters",
            "locationX": "3.710675",
            "locationY": "51.035896",
            "standardname": "Gent-Sint-Pieters"
          },
          "destination": {
            "@id": "http://irail.be/stations/NMBS/008892908",
            "id": "BE.NMBS.008892908",
            "name": "Ronse",
            "locationX": "3.602552",
            "locationY": "50.742506",
            "standardname": "Ronse"
          },
          "composition": {
            "source": "Mistral",
            "units": {
              "number": "4",
              "unit": [
                {
                  "id": "0",
                  "materialType": {
                    "parent_type": "AR41",
                    "sub_type": "b",
                    "orientation": "LEFT"
                  },
                  "hasToilets": "1",
                  "hasSecondClassOutlets": "1",
                  "hasFirstClassOutlets": "1",
                  "hasHeating": "1",
                  "hasAirco": "1",
                  "materialNumber": "4154",
                  "tractionType": "AM/MR",
                  "canPassToNextUnit": "0",
                  "seatsFirstClass": "0",
                  "seatsCoupeFirstClass": "0",
                  "standingPlacesFirstClass": "0",
                  "seatsSecondClass": "74",
                  "seatsCoupeSecondClass": "0",
                  "standingPlacesSecondClass": "20",
                  "lengthInMeter": "25",
                  "hasSemiAutomaticInteriorDoors": "0",
                  "materialSubTypeName": "AR41_b",
                  "tractionPosition": "1",
                  "hasPrmSection": "1",
                  "hasPriorityPlaces": "0",
                  "hasBikeSection": "0"
                },
                {
                  "id": "1",
                  "materialType": {
                    "parent_type": "AR41",
                    "sub_type": "a",
                    "orientation": "RIGHT"
                  },
                  "hasToilets": "0",
                  "hasSecondClassOutlets": "1",
                  "hasFirstClassOutlets": "1",
                  "hasHeating": "1",
                  "hasAirco": "1",
                  "materialNumber": "4154",
                  "tractionType": "AM/MR",
                  "canPassToNextUnit": "0",
                  "seatsFirstClass": "12",
                  "seatsCoupeFirstClass": "0",
                  "standingPlacesFirstClass": "8",
                  "seatsSecondClass": "68",
                  "seatsCoupeSecondClass": "0",
                  "standingPlacesSecondClass": "24",
                  "lengthInMeter": "25",
                  "hasSemiAutomaticInteriorDoors": "0",
                  "materialSubTypeName": "AR41_a",
                  "tractionPosition": "1",
                  "hasPrmSection": "0",
                  "hasPriorityPlaces": "0",
                  "hasBikeSection": "1"
                },
                {
                  "id": "2",
                  "materialType": {
                    "parent_type": "AR41",
                    "sub_type": "b",
                    "orientation": "LEFT"
                  },
                  "hasToilets": "1",
                  "hasSecondClassOutlets": "1",
                  "hasFirstClassOutlets": "1",
                  "hasHeating": "1",
                  "hasAirco": "1",
                  "materialNumber": "4156",
                  "tractionType": "AM/MR",
                  "canPassToNextUnit": "0",
                  "seatsFirstClass": "0",
                  "seatsCoupeFirstClass": "0",
                  "standingPlacesFirstClass": "0",
                  "seatsSecondClass": "74",
                  "seatsCoupeSecondClass": "0",
                  "standingPlacesSecondClass": "20",
                  "lengthInMeter": "25",
                  "hasSemiAutomaticInteriorDoors": "0",
                  "materialSubTypeName": "AR41_b",
                  "tractionPosition": "2",
                  "hasPrmSection": "1",
                  "hasPriorityPlaces": "0",
                  "hasBikeSection": "0"
                },
                {
                  "id": "3",
                  "materialType": {
                    "parent_type": "AR41",
                    "sub_type": "a",
                    "orientation": "RIGHT"
                  },
                  "hasToilets": "0",
                  "hasSecondClassOutlets": "1",
                  "hasFirstClassOutlets": "1",
                  "hasHeating": "1",
                  "hasAirco": "1",
                  "materialNumber": "4156",
                  "tractionType": "AM/MR",
                  "canPassToNextUnit": "0",
                  "seatsFirstClass": "12",
                  "seatsCoupeFirstClass": "0",
                  "standingPlacesFirstClass": "8",
                  "seatsSecondClass": "68",
                  "seatsCoupeSecondClass": "0",
                  "standingPlacesSecondClass": "24",
                  "lengthInMeter": "25",
                  "hasSemiAutomaticInteriorDoors": "0",
                  "materialSubTypeName": "AR41_a",
                  "tractionPosition": "2",
                  "hasPrmSection": "0",
                  "hasPriorityPlaces": "0",
                  "hasBikeSection": "1"
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

**Comment by Bertware** [comment]
The raw composition data for debugging this later today/tomorrow: [compositionrawdata.json](https://github.com/iRail/iRail/files/15159843/compositionrawdata.json)

**Comment by GaspardMerten** [comment]
Regarding the composition, I was a bit estranged by the fact that the API relies on "https://trainmapjs.azureedge.net/data/composition/" which is down...  Is it the cache doing the work or am I missing something ?

Btw is the SNCB Website using Irail as the source? If not I wrote the first embryo of a script to fetch the composition from the web app:

  import re
  from datetime import datetime
  from functools import lru_cache
  from typing import Literal, Union
  
  import bs4
  import pydantic
  import requests
  
  RAW_HEADER = """Host: www.belgiantrain.be
  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
  Accept-Language: en-US,en;q=0.5
  Accept-Encoding: gzip, deflate, br
  Connection: keep-alive
  Upgrade-Insecure-Requests: 1
  Sec-Fetch-Dest: document
  Sec-Fetch-Mode: navigate
  Sec-Fetch-Site: none
  Sec-Fetch-User: ?1
  Pragma: no-cache
  Cache-Control: no-cache
  TE: trailers"""
  
  
  FIXED_CARRIAGE_SIZE = 18.4
  FACILITIES_CLASS = "train-details-visual__facilities"
  TRAIN_FACILITIES_CLASS = "train-details-facilities"
  
  SOURCE_URL = (
      "https://www.belgiantrain.be/api/routeplanner/GetTrainComposition/?from={FROM_ID}&to={TO_ID}&trainNumber={"
      "TRAIN_NUMBER}&depDateTime={DEPARTURE_TIME}&hasdeparted=False&occupancyLevel=1"
  )
  
  
  class Carriage(pydantic.BaseModel):
      carriage_type: str
      model: str
      classes: list[int]
      facilities: list[Literal["accessible_toilet", "toilet", "bike"]]
      carriage_size: float
  
  
  class Train(pydantic.BaseModel):
      facilities: list[Literal["airconditioning", "heating"]]
      occupancy: Literal["low", "medium", "high"]
      carriages_count: int
      carriages: list[Carriage]
  
  
  @lru_cache(maxsize=1)
  def make_session():
      session = requests.Session()
      session.headers = {
          header.split(": ")[0]: header.split(": ")[1]
          for header in RAW_HEADER.split("\n")
      }
  
      return session
  
  
  def parse_carriage(li: bs4.Tag) -> Carriage:
      classes = list(map(int, re.findall("<span>([1-2])</span>", str(li))))
      # carriage type is the class of the li
      carriage_type = "_".join(li["class"])
      model = li["title"]
      # Faciltieis can be extracted from the child div with the facilities class
      # then each svg possesses a title child with the facility name
      facilities = [
          svg.find("title").text
          for svg in li.find("div", class_=FACILITIES_CLASS).find_all("svg")
      ]
      # Replace spaces with underscores
      facilities = [facility.replace(" ", "_") for facility in facilities]
  
      carriage_size = FIXED_CARRIAGE_SIZE  # meters
  
      return Carriage(
          carriage_type=carriage_type,
          model=model,
          classes=classes,
          facilities=facilities,
          carriage_size=carriage_size,
      )
  
  
  def parse_carriages(soup: bs4.BeautifulSoup) -> list[Carriage]:
      return [parse_carriage(li) for li in soup.find("ol").find_all("li")]
  
  
  def parse_train_composition(
      soup: bs4.BeautifulSoup, carriages: list[Carriage]
  ) -> Train:
      # Get the train facilities
      ul_container = soup.find("ul", class_=TRAIN_FACILITIES_CLASS)
      air_conditioning = ul_container.find("li", title="Airconditioning") is not None
      heating = ul_container.find("li", title="Heating") is not None
      # occupancy can be extracted occupancy-row-title-32
      occupancy = (
          ul_container.find("div", class_="occupancy-row-title-32")
          .text.replace("Expected occupancy: ", "")
          .lower()
      )
  
      train_facilities = []
      if air_conditioning:
          train_facilities.append("airconditioning")
  
      if heating:
          train_facilities.append("heating")
  
      return Train(
          facilities=train_facilities,
          occupancy=occupancy,
          carriages_count=len(carriages),
          carriages=carriages,
      )
  
  
  def parse_sncb_html_compositions(html_data: str) -> Train:
      soup = bs4.BeautifulSoup(html_data, "html.parser")
  
      carriages = parse_carriages(soup)
  
      return parse_train_composition(soup, carriages)
  
  
  def get_train_composition(
      from_id: str, to_id: str, train_number: str, departure_time: datetime
  ) -> Union[Train, None]:
      """
      Get the train composition from the SNCB website
      :param from_id: The station id of the departure station
      :param to_id: The station id of the arrival station
      :param train_number: The SNCB train number
      :param departure_time: The departure time of the train
      :return: The train composition, or None if an error occured
  
      >>> get_train_composition("008814001", "008814008", "IC", datetime(2024, 4, 24, 12, 15))
      """
      # Remove leading zeros
      from_id = from_id.lstrip("0")
      to_id = to_id.lstrip("0")
  
      response = make_session().get(
          SOURCE_URL.format(
              FROM_ID=from_id,
              TO_ID=to_id,
              TRAIN_NUMBER=train_number,
              DEPARTURE_TIME=departure_time.strftime("%m/%d/%Y %H:%M:%S"),
          )
      )
      response.raise_for_status()
  
      try:
          return parse_sncb_html_compositions(response.text)
      except AttributeError:
          return None
  
  
  if __name__ == "__main__":
      get_train_composition("008814001", "008814008", "IC", datetime(2022, 1, 1, 12, 0))

**Comment by Bertware** [comment]
> Regarding the composition, I was a bit estranged by the fact that the API relies on "https://trainmapjs.azureedge.net/data/composition/" which is down... Is it the cache doing the work or am I missing something ?

iRail is using an internal API, more regarding this can be found in #502. Since this weekend we're not running the master branch, since we moved to a new server running a new codebase from a new branch (see #512). This is something which will be fixed today or tomorrow, once the last server-side changes can be applied in order to completely finish the migration.

**Comment by Bertware** [comment]
@VandeVoordeMatthias The composition fetched by iRail matches with the iRail output, which matches your description. iRail determines the origin/destination stations itself to be able to request composition data from the NMBS, and this seems to be going wrong.

Could you clarify how the train splits? At which station does the train split? Do you know the train numbers and origin/destination for each leg?

**Comment by Bertware** [comment]
I was able to find the trips in the GTFS data, where the splitting train is described by two trips in the same block:

```
Station ids
008893708 Eeklo
8892007 gent
8892908 ronse

route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
672,NMBS/SNCB,S51,Gand-Saint-Pierre -- Eeklo,,100,,,
705,NMBS/SNCB,S51,Renaix -- Eeklo,,100,,,
735,NMBS/SNCB,S51,Gand-Saint-Pierre -- Renaix,,100,,,
741,NMBS/SNCB,S51,Audenarde -- Eeklo,,100,,,
752,NMBS/SNCB,S51,Gand-Saint-Pierre -- Audenarde,,100,,,

route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,trip_type
705,002736,88____:G70::8893708:8892007:8:746:20241214,Renaix,778,,31220,,1
705,002736,88____:G70::8892007:8892908:8:846:20241214,Renaix,778,,31220,,1
```

Since iRail can't determine which one is requested, compositions for both stretches should be fetched. The vehicle endpoint already returns the correct data for this train, but this may be a coincidence as it queries using the Gent - Ronse segment.

**Comment by Bertware** [comment]
Fixed, I was aware of the case while coding the GTFS logic, but was missing a real example to test with. Fixed support for these trains and iRail makes the right query now, returning the composition for both journey parts.

https://api.irail.be/v1/composition/?id=IC2241&date=300424&lang=nl&alerts=true&format=json

**Comment by VandeVoordeMatthias** [comment]
Wow, the speed you fix these bugs. Nice work!

**Comment by koeleboe** [comment]
But now, it appears that another bug is introduced. The site from nmbs shows 4 carriages, but this shows 6 carriages after Ghent. This train does not get split, nor it couples with another train in Ghent.
`https://api.irail.be/v1/composition/?id=S51787&date=300424&lang=nl&alerts=true`
