### ISSUE TITLE
Disturbances broken depending on the params

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#522]
Disturbances currently gives an error on production when:
- `format=json`
- No `lang` param is specified
- `lang=de`
- A `lineBreakCharacter` is specified

So basically only this url works now (with nl/en/fr as value): https://api.irail.be/v1/disturbances/?lang=en

**Comment by Bertware** [comment]
The cause for this issue is an unhandled case in the source data (missing id on a disturbance). English is the default, and happened to be cached better/later in the fallback cache (which handles downtime/issues on the upstream side), but ultimately all requests failed. Should be fixed now.

**Comment by jncn** [comment]
Faster than his shadow! Way to go @Bertware ❤️
