### ISSUE TITLE
CORS on redirects

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#526]
Trying to requesting the old API calls are broken due to there is no `access-control-allow-origin: *` header on the first response that redirects that request.

```
Access to XMLHttpRequest at 'https://api.irail.be/stations.php?format=json' from origin 'https://linkedconnections.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by Bertware** [comment]
Fixed! The headers are now included in all redirects to /v1 endpoints
