### ISSUE TITLE
Timesel not taken into account anymore?

### ISSUE THREAD

**Issue by xivk** [iRail/iRail#527]
We had a problem reported to us with using the API in the KBC/Olympus app. There seems to be an issue with requesting connections using the timesel parameter. 

These two give identical results for example:

https://api.irail.be/v1/connections/?from=Gent-Sint-Pieters&to=Mechelen&timesel=departure&format=json&lang=en&typeOfTransport=automatic&alerts=false&results=6

https://api.irail.be/v1/connections/?from=Gent-Sint-Pieters&to=Mechelen&timesel=arrival&format=json&lang=en&typeOfTransport=automatic&alerts=false&results=6

**Comment by Bertware** [comment]
Seems to be an uppercase/lowercase issue, will fix

**Comment by Bertware** [comment]
Should be fixed now, can you re-test and close if it's working as expected?

**Comment by xivk** [comment]
Hey @Bertware I think this issue is back, timesel is case-sensitive again. 

I have recommend to change this to use timeSel client-side from now on but I thought it was important for you to know, this could potentially break existing applications. If the fix could be re-done somehow that would be even better.

Let me know if I can help!
