### ISSUE TITLE
Support PSR-2

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#53]
http://www.php-fig.org/psr/psr-2/

We should follow some coding standards. TODO:
 * [ ] namespace everything
 * [ ] add better README.md to set it up for test purposes
 * [ ] 4 whitespaces indent
 * [ ] ...

**Comment by Tjoosten** [comment]
@pietercolpaert i made a PR where this in implemented. But not all the files

**Comment by pietercolpaert** [comment]
Closing this for now as it's a bad issue: we cannot close it at a certaub point.
