### ISSUE TITLE
504 Gateway Timeout on /v1/liveboard and /v1/vehicle Endpoints

### ISSUE THREAD

**Issue by meesakveld** [iRail/iRail#537]
Hi!

Since last night, my app has been encountering 504 Gateway Timeout errors when querying the following iRail API endpoints:

- `https://api.irail.be/v1/liveboard`
- `https://api.irail.be/v1/vehicle`

These errors started occurring without any changes on my end, and they persist across multiple requests.

Is this a known issue? Any help would be appreciated.

Thank you!

**Comment by Bertware** [comment]
Thanks for pointing this out, for some reason the application wasn't automatically restarted when the healthcheck failed, and status monitoring (from another provider) didn't return anything either. Forcing a redeploy and added independent status monitoring from in DigitalOcean to make sure I'm getting notified.

Everything seems to work as expected again now

**Comment by pgm-meesakveld** [comment]
Yes! My app is working again! Thanks a lot for the quick fix! :)

**Comment by meesakveld** [comment]
Yes! My app is working again! Thanks a lot for the quick fix! :)
