### ISSUE TITLE
Vehicle and Compositions of previous day still visible

### ISSUE THREAD

**Issue by siwieme** [iRail/iRail#539]
When I send a GET-request to the vehicle and composition endpoint, it gives me back the information of the day before.
I tried retrieving the data via the Railer app as well (which uses iRail as well) and there it's also the data from the previous day.

Example: S53 on Monday shows Desiro and/or Breaks instead of the AR41
<img height="400" alt="image" src="https://github.com/user-attachments/assets/89084da2-2537-40e7-98ac-7664eb483c11">
Used request URL: https://api.irail.be/v1/composition/?id=687&format=json&lang=nl

Example: S53 showing the delays of the day before (but that's an issue Railer doesn't seem to have)
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/c1a38d77-89d8-4e0b-9f44-319e44138a6e">
Used request URL: https://api.irail.be/v1/vehicle/?id=681&format=json&lang=nl

**Comment by Bertware** [comment]
The start date logic seems to have gotten disrupted in a merge, and has been fixed now. Thanks for the clear issue description!
