### ISSUE TITLE
Connections for Vienna return error 

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#544]
Request: https://api.irail.be/v1/connections/?lang=nl&to=BE.NMBS.008814001&from=BE.NMBS.008101003
Response:
```xml
<error code="404" requestId="9dbfe524-2fba-497c-b7d7-04b1f2a07eb1">Location not found</error>
```

This used to work in the past.

**Comment by Bertware** [comment]
There are no trains to Vienna. The station is no longer present in the routeplanning data (since it's unused), therefore the routeplanner throws an error. The error message could be a bit more clear though.
