### ISSUE TITLE
Logging using Monolog

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#55]
Use monolog for logging instead of our own error and request logger

**Comment by Tjoosten** [comment]
And remove logging to the database?

**Comment by pietercolpaert** [comment]
yes!

**Comment by Tjoosten** [comment]
@pietercolpaert any update on this?

**Comment by pietercolpaert** [comment]
Not yet! Sorry that it's taking a bit longer!

**Comment by Tjoosten** [comment]
No problem i'm back for development. Just shout if i can do something!
