### ISSUE TITLE
Stations not up to date

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#60]
http://api.irail.be/stations.php doesn't contain stations added in the latest version of https://github.com/iRail/stations

This causes some strange results when displaying a train. e.g.: http://api.irail.be/vehicle/?id=BE.NMBS.ice15

This should also resolve issue #46.

**Comment by jncn** [comment]
Any progress on this one?

**Comment by pietercolpaert** [comment]
Yes! It's fixed

**Comment by jncn** [comment]
Thanks a lot, @pietercolpaert!
