### ISSUE TITLE
Route data platform incorrect

### ISSUE THREAD

**Issue by dirkvranckaert** [iRail/iRail#62]
This is the query: http://api.irail.be/connections/?lang=NL&format=json&to=008814001&from=008895802&sel=depart&date=210515&time=0737

Error is both in XML and JSON, although behaviour is different.

For both the first and the third train there's a platform change for the arrival station if I compare with the website belgianrail.be. For the first route the arrival platform should be platform 10, for the third it should be platform 13.

Both XML and JSON are the same for the first route and don't show any platform change.
For the third route there is a difference:
XML: according to the XML everything is ok: <platform normal="1">12</platform>
JSON: in the JSON blob I can see something is wrong, but not what (normal is zero so something is up, but the platform hasn't changed) :
``` 
				"platform": "12",
				"platforminfo": {
					"name": "12",
					"normal": "0"
				},
```

So anyway, whatever the problem at the server is exactly, there is difference between the output in XML and JSON which shouldn't be. According to the JSON output I suppose that you know the platform has changed and to what it changed.

This is quite an urgent one as we cannot be sure what is correct...

Dirk

**Comment by pietercolpaert** [comment]
It's in production
