### ISSUE TITLE
Direction in route calculation (in via) is incorrect

### ISSUE THREAD

**Issue by dirkvranckaert** [iRail/iRail#63]
Both in XML and JSON WS's I'm having this issue.
When I calculate a route on the NMBS website from "Brussel-Noord" to "Okegem" I can see that I have certain routes with 1 stop ( or "via" in iRail terms ) in Denderleeuw. The first train from Brussel-Noord goes to direction "Oudenaarde", the second one goes to direction "Schaerbeek".

However there is an inconsistency with the webservices.
This webservice call for instance gives me the same routes as I can find on the website:
http://api.irail.be/connections/?lang=NL&format=xml&to=008895778&from=008812005

So for the departure station I can see that it's going direction "Oudenaarde" which is fine, but for the via the direction is also "Oudenaarde" where it should be "Schaerbeek".

I have added the extract of the JSON result where the data is wrong. I do see however that the correct destination is in the arrival station. However the 'via' should also include this the correct destination station...

    {
	"connection": [
		{
			... NOT RELEVANT DATA
		},
		{
			"arrival": {
				"delay": "0",
				"direction": {
					"name": "Schaarbeek"
				},
				"platform": "1",
				"platforminfo": {
					"name": "1",
					"normal": "1"
				},
				"station": "Okegem",
				"stationinfo": {
					"@id": "http://irail.be/stations/NMBS/008895778",
					"id": "BE.NMBS.008895778",
					"locationX": "4.054557",
					"locationY": "50.857712",
					"name": "Okegem",
					"standardname": "Okegem"
				},
				"time": "1432645260",
				"vehicle": "BE.NMBS.L1564"
			},
			"departure": {
				"@id": "http://irail.be/stations/NMBS/008812005/departures/201505261415447021ebb3998f00d3559b2897f96afe",
				"delay": "0",
				"direction": {
					"name": "Oudenaarde"
				},
				"platform": "2",
				"platforminfo": {
					"name": "2",
					"normal": "1"
				},
				"station": "Brussel-Noord",
				"stationinfo": {
					"@id": "http://irail.be/stations/NMBS/008812005",
					"id": "BE.NMBS.008812005",
					"locationX": "4.360846",
					"locationY": "50.859663",
					"name": "Brussel-Noord",
					"standardname": "Brussel-Noord/Bruxelles-Nord"
				},
				"time": "1432642500",
				"vehicle": "BE.NMBS.L2285"
			},
			"duration": "2760",
			"id": "1",
			"vias": {
				"number": "1",
				"via": [
					{
						"arrival": {
							"platform": "6",
							"platforminfo": {
								"name": "6",
								"normal": "1"
							},
							"time": "1432644240"
						},
						"departure": {
							"platform": "8",
							"platforminfo": {
								"name": "8",
								"normal": "1"
							},
							"time": "1432644900"
						},
						"direction": {
							"name": "Oudenaarde"
						},
						"id": "0",
						"station": "Denderleeuw",
						"stationinfo": {
							"@id": "http://irail.be/stations/NMBS/008895802",
							"id": "BE.NMBS.008895802",
							"locationX": "4.071825",
							"locationY": "50.891925",
							"name": "Denderleeuw",
							"standardname": "Denderleeuw"
						},
						"timeBetween": "660",
						"vehicle": "BE.NMBS.L2285"
					}
				]
			}
		},
		... NOT RELEVANT DATA
	],
	"timestamp": "1432639097",
	"version": "1.1"
    }

**Comment by pietercolpaert** [comment]
Hey Dirk,

It's just a bad way we've decided to structure the JSON back in the days. In a via, the first part will be repeated and should be combined with what you've indicated as no relevant data

**Comment by dirkvranckaert** [comment]
That is indeed bad design... However other apps probably already depend on that.
So we should always take the next VIA, or arrival station if last VIA, his direction to show in this VIA... Strange but ok, should work with some extra coding :-)

**Comment by pietercolpaert** [comment]
Thanks!

I agree that it is bad design and indeed apps already depend on that so there's not much we can do anymore... We went with that idea as it reflected the data object we needed for the iRail.be website back in 2010 (time flies)
