### ISSUE TITLE
All English station results are returned in Dutch

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#64]
https://github.com/iRail/iRail/blob/master/api/data/NMBS/vehicleinformation.php#L17

Could we just delete this line? @brechtvdv

**Comment by ChristopheVersieux** [comment]
As discussed on Gitter, this fix also creates 2 empty stations on every request... http://api.irail.be/vehicle/?id=3734&fast=false&lang=en 
I think it would be a good idea to revert it....

**Comment by pietercolpaert** [comment]
Reverted! Will investigate later

**Comment by brechtvdv** [comment]
See #66 too
