### ISSUE TITLE
Replace mysql with pdo.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/iRail#70]
Hi, 

I've browsed trough the code; And what i see that you guys are still use `mysql` function like `mysqli_real_escape_strong()` But the functions are no longer support in the newer php functions. 

So i was thinking maybe we could change them to `mysqli` or even better `PDO`! 
[Line where mysql functions are used](https://github.com/iRail/iRail/blob/master/api/data/NMBS/stations.php#L21)

Can u guys give feedback on this? I you want i can also make a PR for this.

**Comment by coreation** [comment]
Good catch, although I have 0 familiarity with this codebase, the soon obsolete mysql functionality will need to change.

**Comment by Tjoosten** [comment]
@coreation Indeed, Jan so i would like to give this a small priority.
@pietercolpaert  What u think?

**Comment by Tjoosten** [comment]
I just noticed also that the mysql functions a written with procedural methods. Maybe we can change them with Object-Oriented functions. So you have a Object-Oriented written system. And not Objected-Oriented and Procedural.

**Comment by pietercolpaert** [comment]
Good idea indeed!

Op za 4 jul. 2015 00:53 schreef Tim Joosten <notifications@github.com>:

**Comment by Tjoosten** [comment]
@pietercolpaert  I close this issue. 

reason: #55 and #54
