### ISSUE TITLE
Project files should not mix end of lines

### ISSUE THREAD

**Issue by Tjoosten** [iRail/iRail#74]
Some files contain mixed and/or invalid end of lines ( \r\n instead of \n). Homogenize them to improve compatibility across different platforms.

file(s): 
- includes/simple_html_dom.php

Command to solve:
`sed -i "s/\r//g" 'includes/simple_html_dom.php'`

**Comment by pietercolpaert** [comment]
This is fixed I believe. Reopen if closed wrongly :)
