### ISSUE TITLE
Improvement idea for Pieter

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/iRail#8]
As we talked a few minuts before with Pieter, I add this improvement in the issue section.
This will be moved in the future in the project page, but for "alzeihmer victim" purpose, i write it now.

For now, when we have more than one train to take and change gate at the station, the API gives:

     <trains>
          <train>
          IR 1234
          </train>
          <train>
          IC 6969
          </train>
     </trains>

I really would like to make something smarter and use the "detail for all" button on SNCB/NMBS website. That will provide a new web page with a really lot informations:

BEFORE: http://img.skitch.com/20100810-qi8yki9qnaxiyw8hh998a226yq.jpg

AFTER: http://img.skitch.com/20100810-fq2imqjh26cd2rsyxmwtaryxc7.jpg

So as you can understand, this feature might be a problem with the "KISS"
(Keep It Short & Simple) way of thinking, but we can do something smart.

1) keep the train tag for the train number, so that won't change a lot of stuff for developers
2) add informations with "link" tag (maybe there is a better english word)

     <links>
     <link>
         <startcity>
          Brussel
          </startcity>
          <starttime>
          13:03
          </starttime>
          <startgate>
          6
          </startgate>
          <train>
          IR 1234
          </train>
        <stopcity>
          Liege
          </stopcity>
          <stoptime>
          13:33
          </stoptime>
          <stopgate>
          11
          </stopgate>
     </link>
     <link>
         <startcity>
          Liege
          </startcity>
          <starttime>
          14:23
          </starttime>
          <startgate>
          3
          </startgate>
          <train>
          IC 6969
          </train>
        <stopcity>
          Aachen
          </stopcity>
          <stoptime>
          14:53
          </stoptime>
          <stopgate>
          1
          </stopgate>
     </link>
     </links>

Maybe you will find something better but I found these informations really usefull.

Having all these informations in one request seem amazing!

**Comment by pietercolpaert** [comment]
I will not implement this: seems like it would break existing applications
