### ISSUE TITLE
Dead link in docs/

### ISSUE THREAD

**Issue by Tjoosten** [iRail/iRail#86]
De hyperlink in docs/INSTALL is a dead-end. ik get 

404 Not Found.

The requested URL /cgi-bin/trac.fcgi/wiki/InstallingTheCode was not found on this server.

**Comment by pietercolpaert** [comment]
I will remove that folder. That documentation dates back to 2011 and hasn't been updated since

**Comment by Tjoosten** [comment]
alright.

**Comment by pietercolpaert** [comment]
Removed docs in development
