### ISSUE TITLE
No proper error response when NMBS website is down

### ISSUE THREAD

**Issue by jncn** [iRail/iRail#90]
API response when NMBS website is down, is in HTML rather than a JSON/XML error response.

<img width="1245" alt="screen shot 2015-08-06 at 13 45 00" src="https://cloud.githubusercontent.com/assets/995815/9110877/a361bef0-3c41-11e5-935d-eca1e5b1cc62.png">

**Comment by Tjoosten** [comment]
Could this be related to the downtime of nmbs.be from today?

**Comment by jncn** [comment]
@Tjoosten Yep. But if this is the case, iRail API should be able to communicate this to its clients. With a proper error response, this can be achieved. Ex:
```
<error version="1.0" timestamp="1289951590" code="3">
   NMBS website time out, please try again in a little while.
</error>
```

**Comment by Tjoosten** [comment]
And what u think of json?

**Comment by jncn** [comment]
I like JSON, but the current Obj-C wrapper makes use of XML. Besides the current API provides other errors just fine in JSON and XML.

**Comment by Tjoosten** [comment]
Then i will make tomorrow a xml solution.

**Comment by pietercolpaert** [comment]
As we've moved to curl, this should now show a JSON or XML error (untested though). I will close this in favor of fixing issue #56
