### ISSUE TITLE
Train location in vehicle not up to date

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/iRail#92]
After the updates from railtime to NMBS by @brechtvdv , the location of the vehicle is not properly indicated any more.

See comments here: https://hello.irail.be/api/1-0/

**Comment by ChristopheVersieux** [comment]
Hello,
Just a question related to this issue: the location is set to lat/lon coordinates in the API, but is there an easy way to know where the vehicle is (one of the biggest feature request from users). For instance, at station x or between station x and station y?
the big red line, in belgianrail.be screenshot: 

![capture](https://cloud.githubusercontent.com/assets/356214/13081708/229175f6-d4ce-11e5-8d26-fb1b41baa6fa.PNG)

**Comment by pietercolpaert** [comment]
We should add this again to the API within the scope of this issue indeed!

**Comment by ChristopheVersieux** [comment]
Hello guys,
Any update on this one? I haven't tried for a long time and I receive some users requests about the real time train  location.
Would be awesome.

**Comment by Bertware** [comment]
@ChristopheVersieux 
The NMBS now colours a timeline next to the trains. A simple parser for this timeline has been added, marking every "visited" station with left=true. See PR #288. This isn't live yet, but if everything goes well, it should be soon.

**Comment by modulebaan** [comment]
Great! Just what I need for harbour-berail :)

**Comment by Bertware** [comment]
@modulebaan @ChristopheVersieux this feature is now implemented.
@jncn This might interest you too for railer.

**Comment by jncn** [comment]
Perfect, well done. Thanks.
